### ISSUE TITLE
Null pointer exception when COFH and chisel are installed

### ISSUE THREAD

**Issue by xkforce** [CoFH/Feedback#1016]
Here's the crash log:
https://pastebin.com/NAmecFM5

The weird thing is that if I enable everything else in the pack, the game doesn't crash but it does have serious lag issues when getting close to mobs.  If I then disable thermalfoundation, the lag goes away.

Here is the minecraft log for everything enabled w/ lag issues: https://paste.ee/p/wxCRe

Here is the minecraft log for everything enabled except thermalfoundation w/out lag issues: https://paste.ee/p/Jd1jn

**Comment by KingLemming** [comment]
Okay so you have a couple of different issues here.

The crash happens when something has already wrecked Minecraft. Basically, the font renderer doesn't load, and the game is about to crash anyways.

However, a client tick event is still called so we execute and it appears that we cause the crash. We aren't.

The second issue seems to be some *extremely* improperly configured CraftTweaker stuff.

**Comment by tterrag1098** [comment]
You have Chisel but not CTM. Install CTM.

**Comment by KingLemming** [comment]
Well, you have a LOT of errors in that log from CraftTweaker.

**Comment by xkforce** [comment]
Well half the mods that had scripts for them were disabled by that point in testing so I'd be surprised if it wasn't complaining a little.

In any case, it's highly improbable that thermalfoundation is the cause because further testing determined that disabling support for thermalfoundation ores in the ore stone variants config also alleviates the tick rate lag.

**Comment by KingLemming** [comment]
Well yeah, TF absolutely isn't the cause.

The mod doesn't have any "ongoing" effects or code, it's basically a library mod.
