### ISSUE TITLE
[Suggestion] Thermal Innovation Fluxbore Control

### ISSUE THREAD

**Issue by CammyKun** [CoFH/Feedback#1017]
I'm loving the new Fluxbores, and they're now my go-to all purpose tool. That being said, in some cases I actually would like it to be able to slow down. Drills and boring machines generally have a level of power control to stay efficient in real life, It'd be pretty awesome if we had control option to change drilling speeds from maximum to 50%, or 150%. This could be tied to the amount of power used per block for drilling. For example (numbers probably not balanced), drilling at 50% speed could use 25% less energy, and drilling at 150% speed could use 75% more energy. Many of the systems in the Thermal series have dual purposes between V and Shift+Right Click, so I'd love to see Fluxbores have the same option as a good end-game all purpose digger.

**Comment by KingLemming** [comment]
Unfortunately, I don't have fantastic control over the digging speed. If you add Efficiency for example, it basically is WAY more mining speed by itself than the drill at any setting.

So already the issue is that any sort of control on the drill itself is essentially negated due to Enchantments.

Digging speed has been adjusted somewhat in dev. There's a chance that sneak + click will end up being used to open a GUI, so I don't think it's all that feasible to have it do any sort of adjustment like you're thinking.

**Comment by CammyKun** [comment]
Yeah, I'll be honest my main reason for this suggestion is due to having efficiency on my drill, and basically drilling myself tunnels straight into lava pools before I can even hear the lava boiling. Likewise it makes it difficult to use it for any kind of building projects since it can accidentally take two or three blocks at once if there's a frame drop of any kind. I do look forward to seeing the GUI though, and if it ever comes to the case that you have greater control over it (say a slider in the gui that chooses your base mining speed up to a limit based on your tier), then that'd be an awesome little touch that'd make it unique from all of the other mining drills out there in other mods. So far though I'm still really happy with it ^_^

**Comment by KingLemming** [comment]
Okay, so I've looked into this and at the moment it just isn't feasible in any way even halfway approaching the orbit of elegant.

I'm going to see about possibly getting a new thing added to Forge. If that goes in, then it's a maybe. But right now, I have to call it "unpossible," sorry.
