### ISSUE TITLE
[Thermal Expansion 4.1.1-237] Crash when trying to edit teleport plate with multimeter

### ISSUE THREAD

**Issue by scalda** [CoFH/Feedback#1023]
Hi i am having a crash to desktop when trying to shift right click a new teleport plate please find log attached.

http://pastebin.com/vzm9ZAem

regards

scalda

**Comment by R4isen** [comment]
Same issue here

http://pastebin.com/mgQpBfDw

Regards,
Raisen

**Comment by skyboy** [comment]
These are two separate and unrelated crashes.

@scalda Your crash is caused by another mod injecting broken logic into GuiContainer. I don't know what mod is doing it though, so you're on your own for tracking it down.

@R4isen Your crash is caused by either some mod incorrectly modifying how GUIs init, causing the gui's `mc` instance to be null; or by some mod setting the client-side `thePlayer` reference on `Minecraft` to null. Again, I have no way to determine what mod is causing it, but at least you don't have a hundred mods to check.

However, neither of these are caused by nor fixable from my code.

**Comment by vsilvar** [comment]
Just reproduced this bug in SMP with only NEI and CoFH mods.
To note, that the bug didn't happen in single player.

http://pastebin.com/GmwU1aey

**Comment by skyboy** [comment]
@vsilvar Your crash is a third separate and unrelated crash, which is also in fact a bug in my code that I will need to fix. Please open a new issue for it.

**Comment by vsilvar** [comment]
@skyboy I've just opened a new issue for it.
On a side note, the first crash log appears to be very similar if not equal to mine,
I just copied the whole console output because it had more information.

**Comment by R4isen** [comment]
@skyboy I've done some tests and it fails also with Thermal mods installed only.
It fails when running it on server (does not fail for single player nor for LAN game).

Please find client log: http://pastebin.com/tjavgLC3
Server log: http://pastebin.com/wtSJKEYn

Can you take a look at this?

Thanks,
R.

**Comment by skyboy** [comment]
@R4isen The crash you just posted (http://pastebin.com/tjavgLC3) is the same as @vsilvar's crash, and will be fixed. However, your first posted crash (http://pastebin.com/GmwU1aey) is entirely different, and not related.

**Comment by R4isen** [comment]
@skyboy it does not fail with all mods loaded on single player. I'm not an expert on your mods but it looks similar.

Thanks anyway. Really appreciate your job!
Really good mods :)

**Comment by scalda** [comment]
Hi i have just got up this morning and double checked this in a SSP world and that works great so it seems to be when connected to a smp world that it causes the crash. and the mods are the same on both machines.

sorry i should of checked SSP last night.

Any other ideas @skyboy ?
