### ISSUE TITLE
[Suggestion] Forge Lexicon Block

### ISSUE THREAD

**Issue by EvilBastard** [CoFH/Feedback#1029]
While being able to convert items to their ore dict variants is great.  How about something to do that to liquids too? My main thought about that has to do with the various liquid XP/mob essence out there.  It'd be great to be able to convert stores of that from one to another via something like the Lexicon.

**Comment by KingLemming** [comment]
No. The experience fluid was a very intentional balance point and the only reason people ask to convert it is because some other fluid is apparently absurdly trivial to acquire, which negates yet another resource. I don't want to enable that, sorry.

I've made a minor exception in the Tome of Experience to allow it to convert TO Essence of Knowledge, but bidirectionality isn't a thing I want. With ores it's a convenience measure, with fluids it is guaranteed to be exploitative arbitrage.
