### ISSUE TITLE
[Thermal Expansion 1.7.10]  Crash when hovering over a tesseract

### ISSUE THREAD

**Issue by NotNP** [CoFH/Feedback#104]
Hi! We very long time try to understand in what a problem, but and could not understand. We need help :(

Tesseract with a sinal lock.
Сrash not only when hovering, but also when opening an inventory of tesseract:
Client crash-log: http://pastebin.com/K8wWLmn6

Thank you in advance for your help

**Comment by KingLemming** [comment]
Try and make this happen with only CoFH mods.

Also, please update to the final 1.7.10 versions. (They're final because frankly 1.7.10 is unsupported now so... :/)

This seems to be xmod interference, but I'll leave this up so we can at least figure out what it is. There's nothing that can or will be done on our end though.

**Comment by iamomicron** [comment]
If I remember rightly this was caused by using an alpha version of CoFHLib. Using the release version works fine. Has been a long while since I had this, but it was definitely the usage of one of the alpha builds from Curseforge that caused this.

**Comment by KingLemming** [comment]
It's definitely not the latest Core, so yes - your diagnosis is probably correct.
