### ISSUE TITLE
[1.10.2] [Question] Sand to Silicon Recipe

### ISSUE THREAD

**Issue by SnowShock35** [CoFH/Feedback#109]
In 1.7.10 there was a recipe for turning sand to silicon. I'm unsure whether this was added by another mod or if it was native to Thermal Expansion  itself. If it was a recipe from Thermal Expansion, would there be a chance of it coming back?

**Comment by KingLemming** [comment]
Come on...you know not to misuse the issue tracker. -_-

[Question] is not an issue. It's a question. I'll answer this time, but in the future I'm gonna close these outright. That recipe was native to TE, but it required other mods to add silicon with a proper oredict name.

The code is still present in TE, so if the recipe isn't showing up, it's because no other mod is adding an itemSilicon.

**Comment by SnowShock35** [comment]
Well I thought best to ask here rather than spamming you with a message on Twitch or Twitter, but fine I wont ask questions anymore. Also, there are two mods adding silicon both with itemSilicon on them and the recipe is still not added so call it a bug then.

**Comment by KingLemming** [comment]
Twitch/Twitter is preferable.

**Comment by SnowShock35** [comment]
Okay well now I know for future reference. 🙂
