### ISSUE TITLE
Interesting bug regarding the leadstone energy cell

### ISSUE THREAD

**Issue by karrthus1** [CoFH/Feedback#1096]
I have a few mods together, but the main ones i am talking about that are performing a very interesting and game breaking bug

These are:
Thermal Expansions
Team Fortress 2 dispensers

The TF2 dispenser is set to repair items with damage duribility bars. 
When i stand infront of the dispenser while holding a leadstone energy cell the dispenser it attempts to repair the said energy cell the leadstone energy cell turns into a creative mode energy cell

**Comment by XFactHD** [comment]
This seems to be a bug on their side because an an item or itemBlock saying that it is damageable doesn't mean that the damage value is stored in metadata (which in case of the energy cells distinguishes the different energy cell types). They should probably make a blacklist for certain items. The list should be accessible via IMC for other mods to add their items without needing explicit compatibility code.

**Comment by KingLemming** [comment]
This is on TF2's dispensers.
