### ISSUE TITLE
Major Issue - Crash Serverside Mc 1.12.2 please see crash log

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CoFH/Feedback#1108]
I tried by itself - it seems the forge version has something to do with it. Also before you say - the crashlog doesn't say that - its because crash was the same eitherway - seems clientside is fine.

https://gist.github.com/P3rf3ctXZer0/d8f59c83a131dc9c5ae5f00251465323

**Comment by KingLemming** [comment]
This is a major issue, you're right. Just not in the way you're thinking. It shows that you didn't bother searching closed issues for the 7 duplicates of this.

It also shows that you aren't telling the truth when you say "tried by itself," because this is caused by BaseMetals.

Disable Thermal Expansion compatibility in its config.

**Comment by P3rf3ctXZer0** [comment]
Make a note on a wiki - that is always the first place I look. Thank you by the way. Also wikis prevent duplicate Questions.

**Comment by Drullkus** [comment]
Duplicate of #1053
