### ISSUE TITLE
[Thermal Expansion] Server stall, cofh.thermalexpansion.block.ender.TileTesseract.sendFluid

### ISSUE THREAD

**Issue by vadimyer** [CoFH/Feedback#1146]
Server suddenly stopped responding and wouldn't start every new time. Luckily Thermos's instant-removal feature helped to fix that a little by removing all tesseracts.

No crash report, just a stall report:
http://pastebin.com/Hp5r8TLD

Either ThermalExp or IC2, I don't really know. Please look into this.

**Comment by KingLemming** [comment]
Unfortunately we can't really provide Cauldron support. There are just too many differences in how code works vs how it is expected to work.

What we can say is that Tesseracts have never caused anything like this before, so it almost certainly isn't the Tesseract itself, but rather the systems that are attached to them.

**Comment by skyboy** [comment]
It's potentially the quantity of tesseracts, their instant nature makes them slower to process than most tiles on large networks; and that server has 14,000 ticking tile entities in 90 chunks. It's not inconceivable that there's a couple hundred tesseracts there, which would take excessively long to iterate if all of them are trying to send one or more things on the same network, being `O(n^2)`. With there only being 90 active chunks, it would appear to be just one person's base as well, instead of several so they could all even be on the same network.

But yes, suffice to say, this isn't an addressable problem nor a problem with the tesseracts, it's a problem with your players having too many things running at once.

**Comment by XFactHD** [comment]
I would rather say it is a problem with IC2 as their fluid transfer methods in multiple things are mentioned in the stacktraces.
