### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by SmEdD86** [CoFH/Feedback#1152]
FTB Package 2.5.0

CoFHCore-[1.7.10]3.1.2-325
CoFHLib-[1.7.10]1.1.1-181
ThermalDynamics-[1.7.10]1.1.0-161
ThermalExpansion-[1.7.10]4.1.2-240
ThermalFoundation-[1.7.10]1.2.3-112

Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Java Args "$JAVACMD" -server -Xms5G -Xmx5G -XX:NewRatio=3 -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=80 -XX:+UseG1GC -XX:+UseStringDeduplication  -jar FTBServer-1.7.10-1614.jar nogui

Also tested on "$JAVACMD" -server -Xms5G -Xmx5G -XX:NewRatio=3 -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=15 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+ExplicitGCInvokesConcurrent -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -jar FTBServer-1.7.10-1614.jar nogui

We have been having issues with our server running out of memory so we have spent quite a bit of time tracking it down. We have narrowed it down to the ducts from thermal expansion (possibly servos, retrievers and filters). The world was run the same, started up and I stayed within the same 4 chunks.

I would be willing to provide a copy of the map and a couple of areas to test.

I have attached an image of our memory use before (bottom) and after (top) the removal of all TE ducts.

![2016-05-12](https://cloud.githubusercontent.com/assets/19321865/15207411/132206a8-17f4-11e6-8b2c-e5611d796eb5.png)

**Comment by skyboy** [comment]
Both images display a memory leak of the same magnitude.
It's less obvious that the rate is the same in the bottom image due to an increased amount of allocated garbage, but the low point after the garbage collector runs, around the same point the top image ends, is at approximately the same location as it is in the top image. Ducts are not causing any memory leak in the data you have presented.
