### ISSUE TITLE
[sugestion] Thermal Mods Flux Duct animation.

### ISSUE THREAD

**Issue by ThatHuman** [CoFH/Feedback#1157]
Good night, subreddit r/feedthebeast advised to put this here as a way to have more possibilities to be seen and answered.

_The original post can be found here:_ https://redd.it/8rmsh6

Quote: "My question is if it is possible to put the same type of animation that the Dynamos have but in cables that are not transparent, of course. There is a picture to explain me better: **Put ball 1 on ball 2** - https://i.imgur.com/mo5XFdN.png

**Thank you!**

**Comment by KingLemming** [comment]
It is not, due to how the model is constructed. The animation would emanate outward from the center of the duct (or inward to it, but there would be no good way to handle flow without completely overhauling the model and the artwork.

And at the moment, I basically have a lack of texture artists available to me anyways.

So I'm afraid not, this isn't really all that feasible.

**Comment by ThatHuman** [comment]
Oh. Thanks. Fantastic mod, btw. xD

**Comment by Drullkus** [comment]
KL actually means a lack of time on my part. 😰

**Comment by KingLemming** [comment]
And Cynycal too. But honestly, I don't think this one was all that feasible anyways just because the texture is rotated, there are junctions, etc.
