### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Ar97x** [CoFH/Feedback#1168]
Hi, my game keeps crashing when I try to create/open a new world. The cause is the custom ore generation from CoFH Core. I have tested it out: first started a new world without modifying any config. Everything alright. Then I modified the world configs, the game crashes. A contributor from Ender IO GitHub page (mod that first shown some diagnostic on the logs) pointed out for me that it is something about your mod, but it might be a mod conflict between CoFH Core and Mekanism. 

Crash report:
https://www.dropbox.com/s/de5ugtelwt43yih/crash-2016-06-05_03.38.22-server.txt?dl=0
Modified config files (folder):
https://www.dropbox.com/sh/pjvph9n5rzvygm5/AABMQb_gEYq_lvE7CkOTSR-4a?dl=0

Core Version: CoFHCore-[1.7.10]3.1.2-325
Mekanism version (if pertinent): Mekanism-1.7.10-9.0.2.271

If you need the entire modlist, I can send a screenshot.

**Comment by skyboy** [comment]
Your log implies that `Blocks.stone` is null. Whatever mod is causing that is breaking far, far more than just our mod.

**Comment by Ar97x** [comment]
Can you tell which mod is doing it? Because for what I've tested, the game
only crashes when I modify the world ore generation configs.

**Comment by KingLemming** [comment]
Given that Fastcraft is in the stack and has a whole lot of "optimizations" that aren't really known...I'd say there's a real good chance that it's trying to be clever with world generation and failing.

**Comment by Ar97x** [comment]
But I've never had issues with Fastcraft and I have used it for a long
time, with your mods even. Don't think it is the reason. I did some more
testing and your mods (CoFH Core and Thermal Foundation), by themselves
don't cause any issues even with modified configs, so it must be another
mod conflicting with it, because when I try to create a new world with the
whole modpack and without altering the config files it goes alright too. I
tested it again without your mods, and it works just fine. It must be some
kind of mod that has some world generation feature, if it was Fastcraft it
would crash by itself, at least I think so.

**Comment by KingLemming** [comment]
No, Fastcraft wouldn't necessarily crash by itself. It optimizes by assuming things always work a certain way, like vanilla. When you add other mods in there, those assumptions no longer hold.

And it's not just Fastcraft - all mods work this way. However, Fastcraft is in the stack trace and it's pretty notorious for getting deep into the guts of things. Also, nobody actually knows how it works because it's not only closed-source (which is fine), but actively obfuscated (which is lunacy).

But, since you've figured out that it's likely not us (and I agree, or we'd see this a LOT), I'm gonna go ahead and shut this one down.

**Comment by Ar97x** [comment]
Somehow, when I disabled the flat bedrock from configs, everything worked
just fine, even with custom ore gen. So now my problem is solved, I just
thought this info might have some value for you on other issues.
