### ISSUE TITLE
Not displayed IC2 Names of items and blocks

### ISSUE THREAD

**Issue by Tsyklop** [CoFH/Feedback#117]
Please fix this .
This is not a problem IC2.  http://bt.industrial-craft.net/view.php?id=1533

**Comment by 61352151511** [comment]
#83 Already reported this

**Comment by KingLemming** [comment]
This is only *sort* of on our end. The reason IC2 screws up is because it's doing something very hacky. We are too, but our hacks play nicely with more modern hacks. Theirs does not.

We're looking into a solution.

**Comment by chloeprince** [comment]
Took me a week to find this bug by narrowing down 180 mods to find it. I rolled back to the Dec 13th Beta versions of all CoFH Mods and it seems to have returned everything back to normal. 

Mods that I tried that conflict with IC2

industrialcraft-2-2.2.676-experimental.jar
CoFHCore-[1.7.10]3.0.0B9-138  (thru)  CoFHCore-[1.7.10]3.0.0B9-147.jar

**Comment by skyboy** [comment]
Both IC2 and CoFHCore have custom implementations for language parsing (because of features not offered by vanilla). IC2's method is not compatible with our method, but our method is compatible with other similar methods; The only way for this to be resolved is for IC2 to use the forge-provided language table like we do, instead of their present hack.

**Comment by KingLemming** [comment]
Okay, so after talking with all the parties involved, this is ultimately something that Forge needs to fix.

IC2 is doing some ModLoader-era stuff and they just aren't going to play nicely with anyone else. CoFHCore injects lang entries in a proper manner but has the side effect of wiping IC2's out because they are directly hacking into vanilla code (this is a no-no in the Forge age).

1.7.10 Forge will not be introducing the necessary fixes, so the onus at this point is on IC2 to correctly use lang files like every other modern mod.

**Comment by sfPlayer1** [comment]
That's not correct and has nothing to do with legacy code. In fact you are abusing an internal facility to inject your translations AND reset the vanilla localization maps in the process. That's by no means a result of IC2 hacking into vanilla code, it's simply you calling a method clearing all previous entries.

"We are too, but our hacks play nicely with more modern hacks" is total nonsense and exactly opposite to the truth. Your method is the *only* one which even has the potential to not play nice by causing said reset, while IC2 only ever adds extra translations, but never removes any.

By the way, "correctly use lang files like every other modern mod" isn't what you are doing either, we both have valid reasons not to do so.

Either way it's pretty obvious that you are the offender here, you remove the other mods' entries while we don't.

**Comment by skyboy** [comment]
There's a persistent forge-provided mod language table for adding localization data, which we are using. You're not, and a side effect of you not using it is that your localization entries are volatile while ours are not. It's worth noting that IC2 is the only mod impacted by this due to your reluctance to use forge's localization facilities for the remainder of 1.7 since this isn't something lex is going to consider critical enough to make a release for.

**Comment by sfPlayer1** [comment]
That's fine, but rather unrelated since vanilla also has language tables, which you reset. Forge's are also deprecated for removal.

Anyway I have implemented a workaround by populating the LanguageRegistry map as well and made IC2's lang loading asynchronous while I was at it...

**Comment by KingLemming** [comment]
After a bit more discussion, this only happens with MFR and/or NO present - we know why and while it's something we can work around, it's good that you've handled it on your end.

We understand that Forge's are deprecated for removal, but they won't be in 1.7.10 - which is the target right now. 1.8 is a mess.
