### ISSUE TITLE
[TE] Cyclic Assembler MagicCrop essence operation "hang"

### ISSUE THREAD

**Issue by Paul17041993** [CoFH/Feedback#1187]
When attempting to craft multi-essence (eg; logs from 3 nature and 1 water) items in the C.A., the machine will take the total number of essences of only one essence, then hang permanently until the machine is destroyed (cres ham, pick, etc).

All essences are registered in the oreDictionary according to their essence tier, and it appears that the C.A. incorrectly pulls items based on only the oredict into its cache, then continues to fail to craft due to not matching the requirements. This part of the code will need to be altered to account for the demanded items when they don't match, or have a toggle to disable oredict matching.

**Comment by KingLemming** [comment]
Technically this is an issue with MagicCrops.

If two items are not equivalent for crafting, they absolutely SHOULD NOT have the same OreDict registration. They're misuing it and are kind of stupid for doing so.

**Comment by Paul17041993** [comment]
Except MagicCrops has used this system since at least mc1.6 and it cant be changed as it's a critical component of its crafting mechanism.
This has been the first time in many in-game systems that I've had a crafting mechanism fail like this, so if you want the C.A. to not exhibit this behaviour you'll have to either provide a fix or propose a change to forge's oreDict system. The former can be fixed by simply supplying a oreDict match button.

I could imagine the C.A. may show this bug with other recipes as there's many items around many mods that are oreDict registered but will only supply a certain result with certain materials.

**Comment by KingLemming** [comment]
As a general rule, it's not really our job to fix other mod's bugs. This is a misuse of the Ore Dictionary, plain and simple. The entire purpose is crafting equivalency. If they don't have 100% crafting equivalency, they shouldn't be in there, period. End of story.

And the fix isn't nearly as simple as you are suggesting, because it indicates that you really don't understand how the schematics are saved.

I won't rule it out, but I'm considering it super low priority. MagicCrops should probably reconsider how they're doing things.

**Comment by skyboy** [comment]
I've already rewritten the schematic logic to be smarter, but the issue is intractable with current minecraft. The error occuring is here:

```java
ArrayList<String> oreNames = OreDictionaryArbiter.getAllOreNames(craftSlots.getStackInSlot(i));
if (oreNames != null) {
	String validName = "";
	int validSize = 0;
	for (String oreName : oreNames) {
		if (oreName.equals(OreDictionaryArbiter.UNKNOWN)) {
			continue;
		}
		l: {
			copyInventory(craftSlots, workingSet);
			int size = 0;
			for (ItemStack stack : OreDictionaryArbiter.getOres(oreName)) {
				NBTTagCompound tag = stack.getTagCompound();
				int damage = Math.max(0, stack.getItemDamage());
				if (damage == OreDictionary.WILDCARD_VALUE) {
					damage = 0;
					// may or may not work. woo. can't iterate, may crash. could be 37k valid values. could have invalid values in the middle.
					// wish net.minecraft.item.Item.getSubItems worked on server
				}
				stack = new ItemStack(stack.getItem(), 1, damage);
				if (tag != null) {
					stack.setTagCompound((NBTTagCompound) tag.copy());
				}
				workingSet.setInventorySlotContents(i, stack);
				if (!recipe.matches(workingSet, world)) {
					break l;
				}
				++size;
			}
			if (size > validSize) {
				validName = oreName;
				validSize = size;
			}
		}
	}
	if (validSize > 1) { // don't use ore names for single registrations. might break in the future.
		nbt.setString("Ore" + i, validName);
	}
}
```

Most likely source of issue is the damage logic, next most likely is the `recipe.matches()` logic, which is in magic crops and not us.

**Comment by Paul17041993** [comment]
MagicCrops essence doesn't use damage as the possible available types are infinitely variable with the total mods present, similarly, the recipe system _has_ to use tiered oreDict registration to avoid registering _a near infinite amount of possible recipes_. For example, if there are 8 tier 1 essences, the amount of recipes to upgrade the stone would be 8^8; 16,777,216 recipes needed to be registered... hence why MagicCrops has used the oreDict in such a way and for a long time now.

And by "current minecraft" do you mean the current, majorly used, 1.7.10 that I don't see any updates for? or the, unsupported, 1.8...? Also you didnt mention whether that code is in the schematic writing or the actual crafting, I presume it's the former as that's a stupid amount of string compares and instance creations to run each tick...

I'm currently too busy doing my own coding shenanigans to rummage through TE's source again, so I cant directly debug it all myself.

**Comment by skyboy** [comment]
MagicCrops could absolutely use metadata for its essences, which would allow it to use more than a single oredict entry, and also allow our detection logic to function by nature of there existing things like "essenceEarth" existing.

By "current minecraft" I mean "mojang" essentially. The server has no way to get a list of sub-items for items that have multiple, which would resolve this issue entirely.

Additionally, the code posted runs once when the schematic is created, to write out what items are used for the schematic.

<hr>

Finally, we use the item as-is for comparisons if none of the oredict entries match the recipe. Since the recipe *should* reject the presumably invalid item we drop into it during the check above, this is an issue in the code for MagicCrop's recipe.

**Comment by Paul17041993** [comment]
Ok then, but it still hasn't been established why the C.A. _pulls items out before actually checking them_, then breaks its own functionality in the process. Unless it does in fact check the recipe validity and we're actually looking at a forge bug?

If you need a list/tree of sub-items in the oredict, why not get it added to forge? it seems quite silly for the oredict not to have one, unless I missed what you meant.

NBT isn't a concern here, but I believe magiccrops already used the metadata previously for plant growth progress when you broke it. FYI though I replaced the problem C.A. with an enderIO crafter that does the job, albeit with a lot more RF at a much lower speed. I will also note that MFR doesn't recognise the magiccrops plants for some reason.

**Comment by XFactHD** [comment]
MFR doesn't recognise them because they are special plants which need to be registered. There is a mod which does exactly that.
In terms of the recipe stuff, you seem to still not have understood what KingLemming and skyboy are telling you. The OreDictionary is meant to be used for items that are completely equal in crafting. I also don't see any problem in the use of metadata for the items as their can be over 32000 different sub items for one item. When the seed is planted, the level of the crop and the type of seed could be stored in NBT data.

**Comment by Paul17041993** [comment]
I know perfectly well how the oreDict is "supposed" to be used and that item metadata can be used to unify items in a similar way, but as I already said, the metadata for each item was already in use and possibly still is. FYI I'm an ex-modder myself, I already know this stuff.

**Comment by XFactHD** [comment]
Before you said "but I believe magiccrops already used the metadata previously for plant growth progress when you broke it" but this doesn't have any influence on the item's metadata because the growth of the plant is not needed for placing the seed down as the seed is not the ItemBlock of the crop.

**Comment by Paul17041993** [comment]
MagicCrops seeds used to store their block's metadata (growth) if the block was destroyed, retaining its progress when re-planted. Or at least I'm pretty sure what the metadata was used for at the time (1.6.4), I haven't fully tested if it's still the case.

**Comment by XFactHD** [comment]
This is not the case anymore in 1.7.10.
