### ISSUE TITLE
Thermal Dynamics Performance Issues

### ISSUE THREAD

**Issue by Sir-Will** [CoFH/Feedback#1189]
The performance with itemducts is pretty bad. Is there anything which can be improved or maybe some debugging/profiling to find the grid or inventory causing the issues?

![](https://i.imgur.com/A0p9o55.jpg)
![](https://i.imgur.com/UMvGIIY.jpg)
![](https://i.imgur.com/wxekB24.jpg)
![](https://i.imgur.com/WXV7gGi.jpg)

**Comment by KingLemming** [comment]
Afraid not, sorry. This is caused by an inventory though and not TD itself.

LagGoggles may help in finding laggy tile entities.

**Comment by Sir-Will** [comment]
But the main issue seems to be the ItemStack copy.

**Comment by covers1624** [comment]
You are miss understanding. TD uses a tick handler for ALL duct grids in the world, that means the 'load' isn't spread out like say a Pulverizer would be, we get blamed for having high tick time when in reality its because of the things connected to the ducts. TD is as optimised as it can be and there is nothing we can do about the performance of ItemStack.copy, all sorts of stuff happens there that we have no control over, but we need to copy the stack.
