### ISSUE TITLE
[mod interaction] Mekanism steel recipes in induction smelter

### ISSUE THREAD

**Issue by BionicFelps** [CoFH/Feedback#12]
The induction smelter recipes for Mekanism steel are a bit odd... Steel dust (which has already had the "carbon" added in mekanism machines) is required to be smelted with either coal or charcoal, and it takes 2 dusts to make 1 steel, but of course, you could just put it in the redstone furnace to get 1 steel ingot per dust...

And a related request... If Railcraft is installed, can we get Railcraft steel out of that?

Seems like TE is detecting something odd about the mekanism steel... It handles the Railcraft steel pretty well (although to be fair I don't know if that's hard-coded)

**Comment by KingLemming** [comment]
You are correct, TE detects something odd about Mekanism steel. The steel itself is odd.

It's being registered to the oreDict as dustIron. This is a Mekanism issue with improper OreDict usage. I refer you to:
https://github.com/aidancbrady/Mekanism/issues

As far as the RailCraft steel goes, it chooses the first ingot in the OreDict, since we don't add it. If that happens to be RailCraft, then so be it.
