### ISSUE TITLE
(COFHCORE) Possible incompatibility with F&A

### ISSUE THREAD

**Issue by Sunconure11** [CoFH/Feedback#1203]
https://github.com/FossilsArcheologyRevival/FossilsArcheology1.7/issues/342#issuecomment-231621756

After some deduction, it appears I have found a weird issue when CoFHCore and F&A are installed.

**Comment by KingLemming** [comment]
There is literally nothing in that log that points to CoFHCore.

**Comment by skyboy** [comment]
The [crashing line](https://github.com/FossilsArcheologyRevival/FossilsArcheology1.7/blob/79fb116093b24b0434cf8dbc3d58c527913a1de7/src/main/java/fossilsarcheology/Revival.java#L82) is such that if CoFHCore was responsible, then not even our own mods would function without crashing.

Your problem is in another castle.

**Comment by Sunconure11** [comment]
Weird, because removal of this mod stops the issue.

**Comment by Sunconure11** [comment]
It's not related to F&A, but LLibrary.

**Comment by gegy1000** [comment]
So I've been looking into this problem, and it looks like CONFIG is null. This means somehow CoFH Core has broken LLibrary's ASM. The llibrary/debug folder usually contains this: http://i.imgur.com/06WOjr8.png, but when CoFH Core is installed, only these are added: http://i.imgur.com/PEcochZ.png

Do you have any idea which part of CoFH could be causing this?

**Comment by skyboy** [comment]
I have no idea what the images even mean, let alone what could be causing the difference.

**Comment by gegy1000** [comment]
Those images are of the llibrary/debug folder, this is where all classes that have been modified with ASM go. It helps us test if the ASM worked correctly. So somehow CoFH is preventing LLibrary from making changes to the missing classes.

**Comment by skyboy** [comment]
I tested this on my own (just the CoFH mods and LLibrary), and the only class you do not get to transform is FMLModContainer because CoFHCore adds its own type of mod, via the `ChildMod` annotation. Not that this is a class you should be altering in the first place.

This is both not fixable, and not my problem, and based on the code you actually have is because you're seeking to get the same data CoFHCore gathers in a wholly inappropriate way.

<hr>

As for RenderPlayer not showing up - don't know, maybe you crash before it loads, maybe another mod is loading it in their core mod.

**Comment by Alex-the-666** [comment]
The code in LLibrary causing this conflict is currently being fixed, and a patch should be released soon.
