### ISSUE TITLE
Capabilities for RF-API

### ISSUE THREAD

**Issue by thilokru** [CoFH/Feedback#1215]
Forge introduced capabilities to avoid the implementation of interfaces on TileEntities.
In contrast to that, the RF-API requires the implementaton of, i.e. IEnergyReceiver on the TEs.
I know, this will break backwards compatability to older versions, but at least for MC v1.9 the RF-API should switch to a Capability-based aproach.

I can work on a pull request for the above mentioned changes, but first I'd like to know, whether you'd approve.

**Comment by KingLemming** [comment]
Capabilities are not entirely a good thing. There's a performance hit, due to per-tick checking, and additional loss of functionality when you realize that capabilities cannot be cached the same way that interface objects can.

If we migrate to capabilities, we'll handle it, but I definitely won't be accepting any PRs for it, sorry.
