### ISSUE TITLE
Freeze/Crash when putting a storage drive from reborn storage in a strongbox

### ISSUE THREAD

**Issue by Darthip** [CoFH/Feedback#1261]
> Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes

![capture](https://user-images.githubusercontent.com/42181820/44242043-ece82200-a1c7-11e8-9c17-caf82e2b8a57.PNG)

When putting a 1024k (with 100k items) storage drive from reborn storage in a strongbox

The crash is 100% reproducible

I don't know if you could do anything about it but warn players not to do that

**Comment by Tahakk** [comment]
Blacklisting it is the way to go. 

btw. I thought that RS is storing it's resources into file, to prevent this from happening, would be weird if Reborn Storage wouldn't do the same.

What version are you running on?

**Comment by Yamza** [comment]
I'm trying to reproduce this, but I've no idea how to even use Reborn storage.
Here's a bit more info on it: https://www.reddit.com/r/allthemods/comments/981aee/crash_when_putting_a_storage_disk_from_reborn/
RebornStorage-1.12.2-3.1.0.50
ThermalExpansion-1.12.2-5.5.0.29-universal 
I suspect the issue is more on the Reborn Storage side.

**Comment by Darthip** [comment]
According to the mod creator of rebornstorage, it is fixed in a newer version of the reborn storage mod
