### ISSUE TITLE
[Feature Request] Blacklist for Autonomous Activator

### ISSUE THREAD

**Issue by andrewring** [CoFH/Feedback#127]
Ability to blacklist certain blocks to stop autonomous activator from clicking on them.  This would be useful in stopping erroneous interactions with other mod blocks (such as Steve's Factory Manager) which cause crashes.

Could theoretically also be used as a control by server ops, though I don't know if that would see any use...

**Comment by KingLemming** [comment]
Hrm...traditionally, the expectation is that other mods correctly prevent this, as it's 1000x easier on their end. Basically, they just deny fake player interaction.

Maintaining a blacklist requires some extra checks and logic and can slow the operation down considerably.

We'll see, but if the only example you have offhand is SFM, I'd suggest you send this over to them and request that fake players not be allowed to interact.

**Comment by andrewring** [comment]
Fair enough.  I can't find his bug tracker, so I just sent him a message.  Thanks.

**Comment by KingLemming** [comment]
So just curious - do you actually have a crash log for this sort of interaction?

**Comment by andrewring** [comment]
Not at the moment.  I suppose I could load up a creative and cause the problem...

**Comment by KingLemming** [comment]
After thinking about it, there's no good way for us to do this on our end, sorry. The AA emulates player behaviors, and that may include using AE tools. So even if we prevented direct clicks, we couldn't prevent indirect.

And the fake player isn't allowed to open GUIs, so that really shouldn't be an issue. Fake player detection is the standard among mods and we're going to have to rely on it.

Sorry, but we did look into it. We were just changing things in the activator and tried to come up with a way to do this.
