### ISSUE TITLE
Thermal Dynamics - Thermal Dynamics preventing TileEntities from getting removed

### ISSUE THREAD

**Issue by Tschipp** [CoFH/Feedback#1307]
Hi, I was recently notified by @Darkosto of a weird interaction between Thermal Dynamics and my mod, Carry On. Carry On allows you to pick up blocks while conserving their contents and move them around in the world.
To accomplish that, it first removes the TileEntity from the world by calling `							world.removeTileEntity(pos);`. After that it sets the block to air. This removes the item contents and works in  _most_ cases. 
Now, when a shulker box (or a TileEntity similar to a shulker box) gets placed beside any duct, it doesn't need to be an itemduct, and the shulker box then gets carried, the shulker box gets duplicated and an item spawns. 
[This gif](https://i.gyazo.com/4f5c98181201babd7adf2a614f218280.gif) shows exactly what I mean.

When a shulker box (or any block, in fact) gets broken, `Block#breakBlock` gets called. I went through the code with the debugger and found this main difference:
When the shulker box **isn't** placed against a duct, the tile entity is null:
https://i.imgur.com/lSRz8Ku.png

When the shulker box is placed against a duct, the tile entity is not null:
https://i.imgur.com/jU83cIM.png

This issue appears to also happen with modded shulker boxes, like those from IronChests.
It also happens when they are connected to mekanism cables, but it doesn't happen when connected to cyclic pipes.

Since Thermal Dynamic's node system is quite large and complicated, I thought it would be best to ask you directly. I hope you can point me in a direction. 
Thank you for your time!

**Comment by KingLemming** [comment]
So this is kind of tricky. Basically there's a contract for how things should happen, and it sounds like you're sort violating that. And that can often work. The problem is that when you get into efficiencies - things like caching Tile Entities happens.

When a Tile Entity is cached, removing it doesn't outright delete it. It queues it up for deletion. If that tile is cached, welp. The way Forge has done this is that Tile Entities actually stick around until AFTER the block is gone. The reason for this is so that the Tile Entity can control how drops are handled. By removing the Tile Entity before you remove the block, you're sort of going against the flow.

Offhand I don't have a good solution for you here. Perhaps a blacklist for blocks which already have similar behavior to what your mod is providing?

**Comment by Tschipp** [comment]
Interesting... so I'm guessing Thermal Dynamics caches Tile Entities conntected to its network? There is probably no way to "force" delete the TileEntity, even from cache, right?
If there's not, I guess I'll just have to resort to writing exceptions for these specific cases.

**Comment by KingLemming** [comment]
You may have to, but the problem is that you're sort of hacking the block removal contract in general.

What you could do is add the block position of the tile to a map, and then have an event handler for the block drops, and just return an empty drop list. This should ensure that there are no dupes and catch all edge cases.

**Comment by KingLemming** [comment]
Sure thing. Good luck. :)

**Comment by Tschipp** [comment]
This has worked, thank you for your support!

**Comment by KingLemming** [comment]
Excellent!
