### ISSUE TITLE
A simple fix to prevent huge frustrations with other mods that stop working

### ISSUE THREAD

**Issue by ssotangkur** [CoFH/Feedback#132]
I'm not sure how this happens but eventually I see a .DS_Store file appears in the <install>/config/cofh and <install>/config/cofh/world directories. This causes the "[CoFHWorld/CoFHCore]: Critical error reading from a world generation file: <path to .DS_Store file>" and from that point one weird things stop working in other mods such as: ModularPowerSuits powerfist stops digging.

I think the fix is really quite easy. I believe all that's needed is a change to cofh.core.world.FeatureParser.java : addFile(ArrayList<File> list, File folder)
Instead of:
```
File[] fList = folder.listFiles();
```
Use a FilenameFilter to get only files that end in *.cfg
```
File[] fList = folder.listFiles(
    new FilenameFilter() { 
        public boolean accept(File dir, String name) { return name.toLowerCase().endsWith(".cfg");}
    }
);
````

I know you could say, "Not my problem/Somebody else caused this, they should fix it." but considering how easy it would be to add this and just avoid the situation for lots of people would be a good thing. Thanks for taking the time to look into this :)

**Comment by KingLemming** [comment]
Okay so here's the thing - CoFHCore not being able to read a world gen file should not cause any other mod to stop working. So that part is something else entirely and you should talk to MPS about it.

However, this is worth considering, although we'd be looking for ".json" files. I'll make sure it doesn't cause any other issues and if not, it sounds reasonable.
