### ISSUE TITLE
Fluid Allocator cannot access tile entities tanks except the first

### ISSUE THREAD

**Issue by Keridos** [CoFH/Feedback#1333]
Using TE 5.5.2.39 and CoFHCore 4.6.1.22 on Forge 1.12.2-14.23.5.2768.

The Fluid Allocator can only pump out fluids from the first slot of AE2 Fluid interfaces.

**Comment by KingLemming** [comment]
That is 100% on AE2's end. Just how caps work.

**Comment by Keridos** [comment]
Well it seems this is Forges "feature" the fluid handler is apparently far more stupid than the ItemHandler capability.

**Comment by KingLemming** [comment]
Forge isn't at fault here. If something has multiple tanks, the Fluid Handler returned needs to be written to support that.

The Fluid Allocator itself does this. Don't blame Forge here; it's on AE2 to support this.

**Comment by KingLemming** [comment]
The more precise version is semantically incorrect here, as the Allocator is not looking for a specific fluid, and there's not an elegant way to specify "any" using that interface.

In fact, it's not even part of the IFluidTank interface and may well not be part of IFluidHandler either in 1.13.

Also, the Fluid Allocator itself is literally "a continuously refilling tile with multiple tanks," and it is able to do this. This absolutely can be resolved by AE2.

**Comment by yueh** [comment]
Feel free to suggest a solution as long as does not involve randomly access tanks each time.

Also just in case, it's not about draining any fluid, but draining a specific one e.g. in case the config for them is locked.

**Comment by KingLemming** [comment]
`for (int j = tanks.length - 1; j >= 0; j--) {
	if (tanks[j].getFluidAmount() <= 0 || isLocked(tanks[j].getFluid)) {
		continue;
	}
	return tanks[j].drain(Math.min(maxDrain, amountOutput), doDrain);
}`

**Comment by yueh** [comment]
How does `isLocked()` magically resolve, if the Fluid Allocator/Servo/Retriever/Filter is locked to this particular fluid? As this is the information I need to skip a particular tank when draining something they won't accept? Also how will this work with every other machine out there?

**Comment by KingLemming** [comment]
Oh I thought you meant if somehow *your* logic had a lock on the fluid. As in your stuff wouldn't *allow* for it to be drained.

**Comment by yueh** [comment]
Yes, that's what we already do and iterating is exactly the issue here.

Given this scenario:

**Source**
Any fluidhandler with 2 tanks (ordered) filled with
1. Water
2. Lava

**Requester**
* Any TE machine, TD servo/retriever. Could be the allocator.
* Whitelist for Lava *or* blacklist for water *or* destination tank locked to lava

In this case it will always request any fluid, which will be the one stored in the first tank. Which will then be rejected by the whitelist/blacklist/config. Rinse repeat every tick/update. It will never drain the requested lava, because there is neither a way we can anticipate it needs lava nor does the requester ever ask for lava instead of any.

Most likely it will apply to other mods as well. If the allocator allows access to its internal tanks in a pull configuration, it might even work with it and some fluiduct + servo/retriever.

**Comment by Tora-B** [comment]
Fluid allocators are somehow able to magically figure this out, when pulling from each other. However, I have found that there are cases where if one tank in the destination is full, it will not attempt to pull any other fluid, even if there's room for it in the appropriate tank. Or even if there's an empty tank in the destination.
