### ISSUE TITLE
Smashing enchant not working in Vanilla+ Environment

### ISSUE THREAD

**Issue by VallenFrostweaver** [CoFH/Feedback#1348]
I have CoFH Core (4.6.1.22), and both Vanilla+ (satchels & tools) mods installed. I do not have Foundation installed. With these 3 mods the Smashing enchant is available to get (by default in configs) but doesn't do anything as it would result in a pulverized version (from Foundation) being made. I suggest either adding in the pulverized variants or removing the enchant from CoFH Core by default if Foundation isn't installed.

**Comment by KingLemming** [comment]
So, it's tricky, because it doesn't look for *only* Thermal Foundation stuff. It will actually work with any other properly Oredict'd dust.

I'm aware of this, and it's something that will be handled in the next framework, but I don't know if I want to "backport" all of the new enchant logic to the current stuff.
