### ISSUE TITLE
Pulverized Iron -> Iron dust from IC2

### ISSUE THREAD

**Issue by 34486** [CoFH/Feedback#1364]
I just realized I am having an issue where pulverizing iron turns it into IC2 iron dust, I have no forceful oredict mod to change that, and I can't find in configs for TE OR IC2 to change this...

No clue what is going on!

1.12.2 2768 forge.

**Comment by KingLemming** [comment]
This has nothing to do with us. You have some sort of unification mod installed.

**Comment by 34486** [comment]
No, I said I don't have any forceful oredict mod, (any ore unification mod), I can give you my list
https://www.modlister.com/user/34486
I JUST updated ic2 to latest AND the thermal mods to the latest as of 11/12/2018 3:50 PM Eastern.

I had also deleted the config file, and created a new forge profile to test this. I'll go ask IC2 now.

**Comment by 34486** [comment]
Everything is default configuration, what would have it configured that way? I can't find anything in IC2 configs or Thermal configs with any substituting or ore-unification or what a machine will produce. 

Maybe I am looking in the wrong place?

**Comment by MauveCloud** [comment]
@KingLemming Instead of making assertions about configurations causing this, you might want to look at pulverizer_ores.json (in the assets/thermalexpansion/content/machine/pulverizer folder of the jar file, no decompiling required).  Most of the outputs appear to be ore dictionary entries, rather than specifically TE/TF items.

**Comment by 34486** [comment]
Am I allowed to change this? If so what is Thermal Expansions iron dust ID???

**Comment by MauveCloud** [comment]
Why would you need to change it?  You mentioned in the forum thread that IC2 iron dust wouldn't work in recipes, but I'm having trouble confirming that - with just IC2, TE (plus minimum requirements), and JEI, it looks to me like pulverized iron (which FWIW is technically defined by Thermal Foundation) is interchangeable with IC2 iron dust in all crafting and machine recipes that use it.

**Comment by 34486** [comment]
Oh its autocrafting from AE2. Even though I make my patterns with oredict substitute on so it SHOULD put ic2 iron dust in automatically to make my invar, it didn't. Still having an issue with it anyways. I think thats on ae then? 
I even made a pattern with iron dust from ic2 and then thermal's pulverized nickel and it says I am missing thermal expansions iron dust... which I didn't use in the recipe....

Strange things. :/

**Comment by KingLemming** [comment]
@MauveCloud - instead of lecturing me on what my .json files say, take a moment to figure out how they work first.

See the _oredict.json? That's what TE machines unify to. You'll notice that by default, it's all the Thermal Foundation materials. Funny that, it's like I wrote it that way on purpose or something.

**Comment by MauveCloud** [comment]
I noticed _oredict.json, but it does not include an entry for iron dust, even though it does for copper, lead, silver, and tin (so presumably IC2 registers its iron dust first and that becomes the default since TE does nothing to specify otherwise).  Also, I have since _personally tested_ with the bare minimum of mods, and seen for myself that a TE pulverizer outputs IC2 iron dust.  On the other hand, it's mostly a moot point, since IC2 iron dust is mostly interchangeable with TF pulverized iron, except for the weird AE2 issue that 34486 mentioned.

**Comment by Tora-B** [comment]
Presumably iron and gold dust, gears, and plates will all be affected, since none of them are listed in _oredict.json. Ingots and nuggets for those two materials are vanilla, which is probably why they got overlooked.

**Comment by 34486** [comment]
For my autocrafting of the gears and stuff? I have had no issue with ae autocrafting gears and ingots from te with te materils, this is so strange.
