### ISSUE TITLE
Missing items Thermal Expansion 1.10.2

### ISSUE THREAD

**Issue by Taquios** [CoFH/Feedback#1393]
I am missing a few items with thermal expansion such as the metallurgical recovery augment, tesseract, and nutrient recovery to name only a few. Not sure exactly why they’re missing. Using Minecraft 1.10.2, skyfactory 3 modpack with all the thermal series mods installed.

**Comment by Tora-B** [comment]
This would really be more appropriate to ask on Discord, rather than the bug tracker, but here goes: Metallurgical Recovery and Nutrient Recovery weren't added until 1.12, and KL doesn't generally backport because the code has changed so much from version to version. Tesseracts haven't been in since 1.7.10, because he wasn't happy with them, and has wanted to redesign them to make them more interesting, but hasn't had the time. There isn't a lot of reason to stick with 1.10-1.11, or really anything from 1.8-1.11. Most mods that survived past 1.7.10 have been kept current and are available on 1.12.2, and there's little benefit for mod authors to maintain old versions, particularly relative to the amount of effort required to do so.
