### ISSUE TITLE
[SUGGESTION] A way to"clear" reusable morbs with incompatible mobs for an automated mob farm

### ISSUE THREAD

**Issue by BigKid1973** [CoFH/Feedback#1414]
I really try to like the idea of the reusable morbs and the augmented centrifugal seperator for a mob farm. However currently there is no way to automate it because the incompatible mobs are captured but then there is no way to process them. After a while the farm is stuck because no empty reusable morbs are left.
Could you please make the seperator accept the morbs and then just "clear" them without loot ?

**Comment by KingLemming** [comment]
Sorry, not possible with the current framework. Maybe with the rewrite.

**Comment by KingLemming** [comment]
That'd be good yeah but without some ugly hardcoding and hackery it just isn't really a thing in the current system.

**Comment by BigKid1973** [comment]
The Problem is - I just cant find a way to detect those bloody morbs... for me it just seems to be the anrgy zombie - but it seems impossible to make a filter or servo just detecting that one :(

**Comment by Tora-B** [comment]
You need to filter on NBT, but the problem is that each mob captured retains a bunch of tags that make otherwise identical morbs distinct from each other. Like I said, you can either blacklist those mobs from the morbs using the config file and handle them using some other method, or you can pick them out of a buffer container.

You might be able to automate that process by periodically shutting off the flow to the buffer, waiting for all the compatible morbs to be pulled out and processed, then switching on a servo to drain the remaining morbs from the buffer. The tricky part is determining when to switch, so that you don't accidentally dump compatible morbs.
