### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by bookerthegeek** [CoFH/Feedback#148]
Hello wonderful people!
#
As a player, I am loving your mod. As a pack maker... Not so much. As I don't java very well the IMC method of changing recipes is a bit of a barrier. So.... May I humble request either:
 - A config for the machine recipes similar to how IC2 does it.
   - A file in the config folder with a modifiable list of all recipes for all machines.
- ModTweaker Support.
  - As ModTweaker (to my knowledge) can not support IMC messages (I might totally be wrong) this would require you to add the support somehow.
- Some other way for non-java pack makers to customize recipes

I look forward to your guys wonderful work.

**Comment by KingLemming** [comment]
This is something I want to do, but it's kind of tricky. I'm not generally a fan of MT given their previously intrusive "compatibility" with TE, but I talked with the new team a while ago and they said they'd add it on their end.

So I'm not really sure what to do here. It should be coming to MT, although I do have a json parser mostly finished. On some level, I kind of dislike extreme functionality and recipe changes anyways, but we'll see.

**Comment by bookerthegeek** [comment]
> On some level, I kind of dislike extreme functionality and recipe changes anyways
> - KingLemming

Can I ask what you mean by extreme functionality?  Also either way is good. I usually prefer using the mods built in way to change things, but some of the things you can do in ModTweaker never show up in most mods "Here is how you change my recipies".

Curious, what would be the better option in your opinion for the modpacks that want ro customize stuff? Just courious as i am currently making a modpack and would enjoy hearing you opinion on that topic.

**Comment by KingLemming** [comment]
So basically, I put a fair bit of effort into the machine recipes, having them do things like scan the oredictionary and automatically construct appropriate recipes from what they find, things like that.

So on some level it's a bit upsetting when people want to go in and alter/remove 50+% of that. It's sort of a weird thing like, "Hey I really like your mod, just not <somewhat large portion of it>" or "I really like your machines, but they're too slow and I only ever want to build one."

I know that's not what you're saying here, but it's sort of why I'm hesitant to open up *too* much functionality. Too much customization and the mod sort of loses its own soul, and then we start hearing reports on how the machines either do too much/too little or whatever because there's no "standard" for what they really do anymore, depending on the modpack.

As I said though, I do want to handle this somehow.

**Comment by bookerthegeek** [comment]
I though as much. It is a really good point and one I would most likely make if I also made a mod. Thank you also for replying to that question.

I'll let you get back to mod making stuff.

**Comment by KingLemming** [comment]
So ModTweaker is out and has pretty comprehensive support in 1.12. So I think that satisfies the original conditions.

A json-based system is in the cards later, but I'm still waiting on Forge to clean things up a bit.
