### ISSUE TITLE
Configs that change GUI sizes aren't sync'd to client

### ISSUE THREAD

**Issue by skyboy** [CoFH/Feedback#1528]
I see no particular reason this *can't* be done, but it hasn't yet and the result isn't a crash anymore, so some method of handling it needs to exist somewhere, even if it's just a crash on login if the sizes don't match.

**Comment by KingLemming** [comment]
There are configs that change GUI sizes?

**Comment by KingLemming** [comment]
I've given it some thought and while it's not ideal, it's just not going to be addressed. There are config options that *require* that modpacks properly sync server and client configs already. If they don't do that, cest la vie.

Sorry, not touching in 1.12 because it just slippery slopes into completely rewriting literally every config option to sync.
