### ISSUE TITLE
[Suggestion] Redstone Arsenal

### ISSUE THREAD

**Issue by Karmacopper** [CoFH/Feedback#17]
As much as I like the flux-infused armour, it is no longer my go to top tier choice. While it is strong and highly enchant-able it loses out in utility to EIO Dark Armour or Machine Muses MMPS.

While I would not wish to simply see features of these mods duplicated in RA armour, it would be nice to have some kind of augmentation system similar to that added to Thermal Expansion machines.

Perhaps use a similar crafting system to the upgrading existing machines ala TE allowing 1 to 3 additional augment slots.

Possible augs might include addition of:
*(Only requiring 1 aug [highest allowed])
Flux Capacitor to increase energy capacity
Flux Goggles(tm) (Infused Obsidian Rod + 2 emeralds) for (true) night vision [green filtered, entity highlighting]
*Machine Speed upgrades for speed increase of legs.
*Fuel Efficiency upgrades for heat resistance.
Pneumatic Servo for Step Assist (Hardened/Reinforced/Resonant versions to add increasing levels of fall damage mitigation)
Machine Secondary upgrades for water breathing, swim boost.

I'm sure other possibilities will come to mind, however I feel this is a long enough post already...

Oops, not Redstone Arsenal, Thermal Expansion

**Comment by skyboy** [comment]
@KingLemming Thoughts? Close this, or have it as a separate mod?

**Comment by KingLemming** [comment]
Not sure where I sit with this...RSA is sort of meant to be a simple mod. It might be worth adding some enchants and minor things but I'm not sure if I want to go the augment route.

That's more of a TE thing. We'll see.

**Comment by Badcholo** [comment]
I added Simply Jet packs mod. They added a jetpack to the redstone arsenal Armor. We just need a way to not take fall damage from the redstone arsenal boots. With a jetpack it's still my top tier Armor Better than EIO. Plus it has a huge increase in RF capacity and charges the rest of your armor and held tool items.

**Comment by NullMagic** [comment]
To be honest there are several mods that are already taking some of this into their own hands, such as Simply Jetpacks, which adds a battery pack (four tiers, Lead, Invar, Redstone and Enderium) with the same amount of power storage as the Energy Cells of the same level, and Jetpacks that follow the same tier system, both the battery pack and jetpacks can be "armored" which allows them to be used as a chest piece. In addtion if Redstone Armory is also present a 5th tier is added that allows you to put both the battery pack and the jetpack into the RA chest piece.

I realize that this isn't entirely what is being asked for, but I think it helps me make my point, which is that this is the kind of functionality that maybe should be kept to other mods that build off of TE, Fluxed Baubles is another good example, although that one seems to have died, as there's been no movement on it since November, that said I do hope it picks back up as I think it was a good idea.

**Comment by Badcholo** [comment]
I like the paxel idea. like mekanism. and no fall damage for the boots.

**Comment by KingLemming** [comment]
Closing this down. No plans to do augments in RSA armor. It'll be another mod. :)
