### ISSUE TITLE
Feature suggestion: WorldGen JSON includes.

### ISSUE THREAD

**Issue by Tylian** [CoFH/Feedback#172]
Would it be possible to add a property to world generation templates that allow you to include/shadow other templates into them, as a sort of "default"? Would help a bunch with organizing, especially with large mod packs that replace most mod's world generation with CoFHCore.

For example:

```json
{
  "populate": {
    "overworld_blob": {
      "distribution": "uniform",
      "enabled": false,
      "generator": {
        "block": "stone",
        "material": "stone",
        "cluster-size": 33
      },
      "cluster-count": 10,
      "min-height": 0,
      "max-height": 256,
      "retrogen": false,
      "biome": "all",
      "dimension": {
        "restriction": "blacklist",
        "value": [-1, 1]
      }
    },
    "diorite": {
      "include": "overworld_blob",
      "enabled": true,
      "generator": {
        "block": {
          "name": "stone",
          "properties": {
            "variant": "diorite"
          }
        }
      },
      "cluster-count": 5
    },
    "granite": {
      "include": "overworld_blob",
      "enabled": true,
      "generator": {
        "block": {
          "name": "stone",
          "properties": {
            "variant": "granite"
          }
        }
      },
      "cluster-count": 6
    },
    "andesite": {
      "include": "overworld_blob",
      "enabled": true,
      "generator": {
        "block": {
          "name": "stone",
          "properties": {
            "variant": "andesite"
          }
        }
      },
      "cluster-count": 7
    }
  }
}
```

Thanks!

**Comment by KingLemming** [comment]
So if it were up to me, the answer to be solid, "Absolutely not," because there's no way that the time saved by the entirety of the modding community will break even with the time it would take us to code this.

Also, there are just too many edge cases and it's not entirely clear what "include" is meant to do here - any field you also add counts as an overwrite?

However, I'll leave it up to @skyboy - his call if he thinks this is worthwhile.

**Comment by Tylian** [comment]
> Also, there are just too many edge cases and it's not entirely clear what "include" is meant to do here - any field you also add counts as an overwrite?

The only real edge case I can think of would be arrays, since those aren't really defined well when it comes to deep merges, and I'd personally say just overwrite them. Merge objects, overwrite everything else.

But now that I think of it, it might be easier to just write a JSON preprocessor. Doing this kind of processing in Java sounds... a lot more tedious than I originally anticipated when making this request.

**Comment by skyboy** [comment]
It's actually already supported. Technically our worldgen config in 1.10 is not JSON, but [HOCON](https://github.com/typesafehub/config/blob/master/HOCON.md); which does support including other files. To prevent it being parsed and generating errors just don't have the file extension for your included files be `.json`.

We keep the base files as pure JSON so that they remain approachable, as the HOCON syntax is anything but; though it is very powerful as you'll quite enjoy.

**Comment by Tylian** [comment]
Oh dang, HOCON actually supports exactly what I want, neat!

Closing this, then. Thanks!
