### ISSUE TITLE
Thermal Expansion blocks/recipes missing

### ISSUE THREAD

**Issue by ChaoticLogic** [CoFH/Feedback#184]
While playing with Thermal Expansion (fairly new to me), I got a book with Holding III from a dungeon chest. Not knowing what it was, I went to the Team CoFH website to find out. This is when I noticed that Strongboxes are supposed to exist. They, along with MANY other Thermal Expansion blocks/items, do not exist in my game.

Thinking to eliminate chances of a mod conflict, I created a new instance of Minecraft with just Thermal Foundation, Expansion, the libraries, and JEI. They still do not exist.

Am I missing a piece?

Setup:
MultiMC: 0.5.1
Minecraft: 1.10.2
Forge: 12.18.3.2185
CoFHCore: 4.1.1.156
ThermalFoundation: 2.0.5.81
ThermalExpansion: 5.0.4.90
CodechickenLib: 2.5.7.241
JEI: 3.14.4.04

**Comment by KingLemming** [comment]
Nothing is wrong, they just aren't in yet. And nothing should be dropping Holding books. That's being added by a mod.

**Comment by Gamemaster2198** [comment]
Hey ChaoticLogic, the reason that several items and other machines is because the CoFH Team did a complete overhaul for Thermal Expansion when porting it from 1.7.10 to 1.10.2. Overhauls such as: Removed the way to upgrade machines and adding Upgrade and Conversion kits to upgrade machines, Removed strongboxes, and other some other stuff.

Also, if you are wondering why the Fluxducts and others don't exist anymore, it's because they have not yet ported the mod "Thermal Dynamics" to 1.10.2 which includes the transference stuff. 

Hope this clear things up.
