### ISSUE TITLE
Magmatic, Compression dynamos generate slightly more than intended

### ISSUE THREAD

**Issue by mconwa01** [CoFH/Feedback#205]
Magmatic and Compression dynamos generate a few extra RF under some combinations of augments and input fluids. The resulting amount seems to be consistent (I've tried each of the following at least twice). The following are the ones I've confirmed on the most recent versions (using default configs):

Compression (L. Coal):
Fuel Efficiency I: 1100800 RF (should be 1100000)
Fuel Efficiency II: 1350400 (1350000)
Fuel Efficiency III: 1851200 (1850000)
Power Output I: 851200 (850000)
Power Output II: 755200 (750000)
Power Output III: 704000 (700000)
FE I, PO I: 950400 (950000, I think)

Magmatic (Lava):
FE II: 243040 (243000)
FE III: 333040 (333000)

I've also seen Forestry Ethanol in previous versions generate 500500 instead of 500000 without any augments, so it might not just be the augments. Haven't tested on the newest CoFH versions yet.

I've yet to see Steam Dynamos affected, though I haven't tried feeding them steam instead of solid fuel. I haven't tried Reactant or Enervation Dynamos.

MC Forge 10.13.2.1291
CoFHCore 3.0.0RC2-195
ThermalDynamics 1.0.0RC2-77
ThermalExpansion 4.0.0RC2-129
ThermalFoundation 1.0.0RC3-56

**Comment by KingLemming** [comment]
Intentional. This is an artifact of how the calculation is done for performance reasons and the "error" is bounded. It also doesn't really have anything to do with the augments.

Basically in these cases, the dynamo winds up with negative a negative fuel value left inside it, so the *next* bucket will not generate as much, and over time the average energy delivered is exactly as stated.

The steam dynamo is a straight conversion from steam->RF, so this won't happen.
