### ISSUE TITLE
Ownership impossible after Mojang Name Change

### ISSUE THREAD

**Issue by Fogger** [CoFH/Feedback#213]
If a player changes their name at https://account.mojang.com/me , any secured items they currently have __or create in future__ will be locked to their old name and thus, the Owner tab is inaccessible!

__Versions tested:__
* Forge `1291`
* CoFHCore `3.0.0RC2-195`
* ~~CoFHLib `1.0.0B9-118`~~
* ThermalDynamics `1.0.0RC2-77`
* ThermalExpansion `4.0.0RC2-129`
* ThermalFoundation `1.0.0RC3-56`
* RedstoneArsenal `1.1.0RC2-43`

EDIT: If I create a new world, the names are fine, it's just the old server that refuses to update.

**Comment by olee** [comment]
That's why all mods should have moved to using UUIDs for permissions, storage and co. since Minecraft 1.7.

**Comment by skyboy** [comment]
Remove CoFHLib from your mods.

**Comment by Fogger** [comment]
I removed CoFHLib from both client and server. No change, still old name & no access on a freshly crafted tesseract.

**Comment by tivec** [comment]
I don't know, but closing this as "user error" feels wrong when there is a system in place from Mojang to change names. If you look at the original post, it's mentioned "any secured items they currently have *or create in future*" - that's a bug, and not a user error.

**Comment by KingLemming** [comment]
The error is having both Lib and Core in the same install.

**Comment by Fogger** [comment]
the lib is gone, so that cannot be

**Comment by KingLemming** [comment]
Alright, seems to be a bug with Mojang's caching system. We'll figure something out.

**Comment by luacs1998** [comment]
KL, it falls on the mod to persist data in a way that can survive the name change system. Ideally, you'd use UUIDs to store data, then use the Forge UsernameCache or something similar to convert UUIDs to  usernames for display/entry.

Support for this needs to be added to CoFHCore or something, seeing as the underlying problem is most likely you guys storing the user data by username. So if the username changes, your storage system thinks it's a different user.

**Comment by KingLemming** [comment]
Actually no luacs, swing and a miss. We use the local cache, which apparently fails to update. ;)

**Comment by GibbsFrance** [comment]
I had the same problem on a server.

Just to clarify, I set up the tesseract and it took my old username as the owner (I changed it two days ago). In addition, if we make the command /cofh friend gui, my new name appears in the list.

**Comment by skyboy** [comment]
Yeah, the server's cache of your UUID and username has the old username (largely just display-related), while your client has the new one (for display in GUIs like the friend GUI). There's a logic disconnect in the owner tabs that compares your name instead of UUID because it was assumed the server's cache would update to the new name when you logged in; since it did not the GUI is preventing you from opening the tab (despite if you actually make those changes they will be permitted). Everything has converted properly, it's just a small issue with the GUI we need to fix.
