### ISSUE TITLE
Information Tab inside the machines stays open when switching to other machines

### ISSUE THREAD

**Issue by mcpecommander** [CoFH/Feedback#22]
As it says in the title: when you open the information tab or the tutorial tab in one machine, it keeps it open in any other machine. While it does not open the wrong information tab, it does seem strange that only these two tabs "info and tutorial" are the only ones that keep opening.
I just double checked. It seems to happen too when opening the energy tab in any two machines that have this tab.
so it is only the config tab that closes upon exiting the GUI and entering another machine GUI.

**Comment by mcpecommander** [comment]
by the way, I am testing this without any extra mods beside JEI and optifine "for fps of course"

**Comment by KingLemming** [comment]
This is 100% intentional behavior and how it has always worked. The tab on the left or right side that you have open is tracked and stays open.

This includes the configuration tab. What you're probably seeing there is going from a device to a machine, as Devices have a different Config tab, and the code works by class ID.
