### ISSUE TITLE
1.10 Item/Fluiducts dont work 

### ISSUE THREAD

**Issue by DerHirte** [CoFH/Feedback#227]
i play the dw20 1.10 version 1.10
Cofhcore, Foundation, Expansion and Dynamics are on the lastest Version

Yesterday i set up a auto processing line for ore processing, today when i started mc, i noticed that are only half of my Induction smelters are supllied with Pyrotheum, Sand and Ore. Then i broke one of the itemducts and Fluiducts and it worked again. Then i checked chunk boundries and noticed that the machines that weren't supllied, were on the next chunk. After sometime i checked everything was alright. then i went to the Nether and the same issue appeared again

**Comment by KingLemming** [comment]
Yeah we're gonna need screenshots of this. Because they work.

**Comment by JonoColwell** [comment]
Seems like there's a problem at chunk boundaries of some sort. Had the same issue, itemducts going several chunks, the items disappear at a chunk border until a duct is broken and replaced, however the ducts seem to store the items that disappear at world border because on break and replace about 100 stacks of wood showed up on the ground where I broke the duct.

Unsure if this is to do with chunkloading, area should have been loaded but definitely is now.

Disappearing in action:
https://gfycat.com/AgitatedAchingDartfrog

Didn't get a shot of the big pile of wood, should have though, lesson for next time.

**Comment by KingLemming** [comment]
Yeah there was a weird corner case with this. It's been fixed in dev. But saying that "they don't work" is completely false and made no sense.
