### ISSUE TITLE
[1.10.2] Steam Dynamo Steam Texture missing

### ISSUE THREAD

**Issue by blitzyuk** [CoFH/Feedback#228]
I'm currently playing on the WeAllPlayPack and noticed with the Steam Dynamo that the texture for the steam is missing http://i.imgur.com/WzPt2I6.png

Using latest version of Thermal Expansion.

**Comment by KingLemming** [comment]
So, this is crossmod in nature and happens when another mod registers a Steam fluid before Thermal Foundation and then either fails to register textures for it, or does so improperly.

Basically, it's not us, sorry. :/ I'll leave it up here though as a reminder to possibly mitigate the visual impact of this.

**Comment by KingLemming** [comment]
Also, I'm a little confused - there's a WeAllPlayPack for 1.10.2? Can I get a modlist please? I'd like to figure out which mod is at fault here.

**Comment by KingLemming** [comment]
This did seem to happen on the WAPC server, and I assume that's because of canonical fluidsand prioritization, so I made a workaround. :)
