### ISSUE TITLE
Had this little bit of crash today any ideas?

### ISSUE THREAD

**Issue by balcas** [CoFH/Feedback#240]
Crash log

https://pastebin.com/vSi1QNp5

**Comment by KingLemming** [comment]
This is caused by another mod improperly oredicting things. It's not Thermal Expansion's fault, sorry. OreDicts MUST happen in pre-init or init, anybody doing it outside of those bounds will cause things like this to happen.

They're setting up a mine and we are stepping on it.

The crashlog suggests that it's an ore in Extreme Reactors, although I have to mention that they may not be the mod at fault - another mod might be trying to be clever and cross-oredicting things.

**Comment by balcas** [comment]
Thank you for your help
