### ISSUE TITLE
Investigate behavior of Linking Viaducts.

### ISSUE THREAD

**Issue by KingLemming** [CoFH/Feedback#277]
Currently, Linking Viaducts seem to "forget" about connections. The reason for this is basically chunk unloading. Clicking the duct fixes this by doing a scan (which will temporarily load a chunk).

At this point, it needs to be decided if this is "proper" behavior or not. The potential server overhead of never "forgetting" is potentially pretty bad. Will need @rwtema input on this as to design intent.

**Comment by KingLemming** [comment]
Just adding on here - behavior is 100% as described. Chunk loading the Long-Range Links keeps them functional, and Destinations must also be chunk loaded.

As it stands, that may feel unintuitive, but frankly this is probably the best solution. I'll leave this here for any comments, but offhand the behavior of the ducts is not likely to change until 1.12+.

**Comment by Tora-B** [comment]
If linking viaducts must be chunkloaded in order to function, then why not make them chunkload? As is, they can't function in a pure CoFH setup because none of them add a chunkloader.

Why does any of it actually need to be chunkloaded? Is the list of endpoints not actually stored, either locally or in a central location? You do a scan, store the results, and if something gets added or removed, either you update the stored list, or you drop the entity out of the duct when it reaches the breach, which is what already seems to happen. Philosophically, either you guarantee success, and accept the necessary overhead, or you allow failure in exchange for performance. As is, it seems like you're requiring more than is necessary for the current failure behavior. Putting it another way, I think you could relax the restrictions without increasing the failure conditions.

Once you've done a scan and found the other end of the link, presumably you store the location of the other end. Why not temporarily load that chunk when retrieving the list of destinations? This seems more server-friendly than requiring all linking viaducts to be loaded at all times. I'm guessing that breaking long-range viaducts doesn't actually notify the linking viaducts of the breakage, and so the linking ducts don't make any guarantee that they're still connected, and you just drop out of the duct when you reach the breach.

**Comment by KingLemming** [comment]
Blocks which autochunkload themselves are sort of irresponsible, tbh. That's the major issue. At the moment, if you right click a linking viaduct, you do force it to load the connected chunks for a few seconds, and that's enough to initiate travel.

The scan does actually ensure that an actual connection exists, however, and that's something I think we should keep.

The best solution is really to just add a chunkloader block and maybe some info somewhere about how they work.

I agree with you that conceptually, chunk loading is implementation leakage, but it's just something that we as modded players need to be aware of. It's a mechanical quirk of the game.

**Comment by KingLemming** [comment]
Ducts are working as intended. Chunk-loading required.
