### ISSUE TITLE
[TD] Round Robin Vertical Duct Bug?

### ISSUE THREAD

**Issue by kennymoto** [CoFH/Feedback#279]
It seems round robin does not work with vertical ducts?? Please see screen shot. The foreground setup round robins the items correctly. The background setup splits items unevenly.
![2015-03-08_23 02 48](https://cloud.githubusercontent.com/assets/11152546/6549820/33fb4218-c5e8-11e4-8ea6-2f18851ae4a8.png)

**Comment by Tora-B** [comment]
I'm pretty sure what you're experiencing is #185, because it doesn't happen if you leave more space between the chests, and place the output on the other side of the source chest, so that it doesn't have to loop over the top. It's miscounting/misrouting because of the disabled connection on top of the source chest.

**Comment by KingLemming** [comment]
What version are you on?

**Comment by kennymoto** [comment]
Sorry should have placed that info in there. I have all the current updates. When I get home I will update with proper version numbers. Sorry and thanks!

**Comment by KingLemming** [comment]
Anyways, yes this is *sort of* #185. Fact is that round-robin is coded in a computationally efficient manner and is duct-based, not inventory-based. A side effect of this is an implicit assumption that players don't do ridiculous things such as your background setup.

It either needs a rework or a complete removal, and I'm really leaning towards the latter.

**Comment by kennymoto** [comment]
Yeah I know it is ridiculous, I made that sample for simplicity purposes - on  the actual build I had no where else to go with the duct :( thanks sir!

**Comment by kennymoto** [comment]
KingLemming I really hope you decide to keep round robin and that it is changed to distribute evenly to connected inventories as opposed to whatever it is doing now. Sometimes users must route ducts in strange ways due to the complexity of the build and the room they have to build it. It would be hard to have to move a complete build to a larger area - just to make round robin work correctly. Thanks again for all you do!

**Comment by KingLemming** [comment]
If a feature can't be made computationally efficient, it's not something I really want to keep around. We'll see.

**Comment by Tora-B** [comment]
You say that it's duct-based, rather than inventory-based, but then why does it work just fine with crazy duct layouts with multiple paths through them, but put an inventory next to one and wrench the duct so that it doesn't connect and it counts wrong? Shouldn't disconnected ducts that are adjacent to an inventory work just like ones that aren't adjacent to an inventory? It's confusing that something that has explicitly been excluded from the duct network is affecting its operation.

**Comment by kennymoto** [comment]
You fixed it. You are da man!!!!!! Thanks!
