### ISSUE TITLE
Lighting "bug"?

### ISSUE THREAD

**Issue by TheSnowyChickens** [CoFH/Feedback#282]
![light](https://user-images.githubusercontent.com/29357962/27390058-87eb0584-56a0-11e7-8bd1-491405b319ca.png)

Hello
At first , my english is not so good. :)

With an block at any side (without front and back) , 1 block in front or at the side of it , from every machine , the lighting is "buggy" I think (Like the picture).
Is this fixable from my side ,with options , or from your side.
Its just a little Lighting bug ,but it dont look great with all machines in a row :D 

MC : 1.10.2
Optifine D8
Newest Forge and newest version from Team CoFH mods (Core , TE , TF)
(21.06.2017)
Thx

**Comment by KingLemming** [comment]
I see the picture, but I have no idea what you are talking about.

I see no issue. Please explain.

**Comment by covers1624** [comment]
All of TE's blocks are rendered via the standards forge has in place, any dependencies in lighting is entirely up to forge and trust me there are several. From that SS, i can't actually see anything wrong with the lighting. Also, you have Optifine installed so that may also be attributing to the issue.

**Comment by TheSnowyChickens** [comment]
Okay thx , then is something wrong with my screens xD
