### ISSUE TITLE
[1.11.2]Actually Aditions oil generating in caves + question & suggestion

### ISSUE THREAD

**Issue by Ushupiuck** [CoFH/Feedback#294]
I'm not sure which mod (yours or his) is causing this; I assume yours since you added other liquids to worldgen; anyway! if the later is the case, it shouldn't it be supposed to be Thermal foundation oil instead of AA oil? xD

For modlist, see previous issue. haven't changed it at all. In fact, I noticed this before I made that ticket...

Also, I'm wondering... Would it be possible to import/load a 1.7.10 world with the whole "thermal pack" to 1.1X.X? (obviously, excluding NetherOres and MineFactoryReloaded)

Lastly, Support for TechReborn (mainly ores & resin, but I mean in general) would be neat!
Thanks for reading, and have a good day..!

**Comment by KingLemming** [comment]
We generate crude oil, not canola oil. So that's not us, unless somebody has hijacked our block. In which case, still not us.

A world import won't happen, sorry - everything got rewritten and it's absolutely not compatible.

TechReborn should already be supported in terms of ores. If it's not, then they're not using the oredict correctly. As far as resin goes, I'll probably be adding Latex as a fluid and deriving rubber from that.

Not really sure how to classify this issue, so I'm gonna close it down. Feel free to drop by the Twitch channel and ping us for questions though, might be easier. :)

**Comment by Ushupiuck** [comment]
ehrm, it's not Canola oil the one generating in caves, but actual Oil. (Obtained by _**refining**_ Canola oil into oil in a barrel). if you check AA, you have both: Oil, and canola oil.
Will do! you appear with the same name in there?

**Comment by KingLemming** [comment]
I get the semantic difference, the point is that we generate crude_oil, not oil, not canola_oil.

I think you have another mod just trying to generate "oil" and that is the issue.

**Comment by Ushupiuck** [comment]
Hm. Hold on for a second…. CoFH oil supposed to generate in “bubbles” inside caves? Aka semi-round or oval-like formations with no air blocks inside. If not, then it’s galacticraft oil the one getting overwritten, and I apologize xD


De: KingLemming<mailto:notifications@github.com>
Enviado: domingo, 25 de junio de 2017 09:31
Para: CoFH/Feedback<mailto:Feedback@noreply.github.com>
CC: Ushupiuck<mailto:giancarloknd@hotmail.com>; Author<mailto:author@noreply.github.com>
Asunto: Re: [CoFH/Feedback] [1.11.2]Actually Aditions oil generating in caves + question & suggestion (#294)


I get the semantic difference, the point is that we generate crude_oil, not oil, not canola_oil.

I think you have another mod just trying to generate "oil" and that is the issue.

**Comment by Ushupiuck** [comment]
@KingLemming I found the issue. you might want to take a look in it, too!
https://github.com/Ellpeck/ActuallyAdditions/issues/813
