### ISSUE TITLE
Crash on Startup with spongeforge on 1.11.2

### ISSUE THREAD

**Issue by BakermanLP** [CoFH/Feedback#299]
Here is the complete logfile of a start of the server. 
https://pastebin.com/LDUu0ksB

On the server are only 2 mods installed:
CoFHCore-1.11.2-4.2.4.9-universal.jar
spongeforge-1.11.2-2315-6.1.0-BETA-2410.jar

Same spongeforge version and CoFHCore-1.11.2-4.2.3.8-universal.jar seems to work correct

**Comment by KingLemming** [comment]
Historically, we haven't supported Sponge. And this is kind of on them not being able to handle a method being changed from private to public.

So no promises.

**Comment by gabizou** [comment]
Just for reference, making it a point in Mixin that it theoretically can handle this sort of change, since Overwrites do end up changing out the body of the method, it could theoretically cause issues in awkward corner cases where that method is soft overridden by subclasses (looking at fake world implementations) that could technically match the method name. Again, very awkward corner cases, but I'll fix it in Sponge for 1.10.2 as 1.11.2 already seems to have made it public (haven't checked if 1.11.2 is *actually* public, but hell, it's already public in our workspace).

**Comment by KingLemming** [comment]
Well, if it's fixed on your end, then good enough for me.

**Comment by fcpwiz** [comment]
I'm running SpongeForge version 1.10.2-2281-5.2.0-BETA-2422 and CoFH Core 1.10.2-4.1.8.12-universal but I'm still getting a startup issue.

https://gist.github.com/fcpwiz/90f26ced047ca010de63242b1829b362
