### ISSUE TITLE
Suggestion: Fluid Transposer Recipe

### ISSUE THREAD

**Issue by Kodos-Atoz** [CoFH/Feedback#329]
A friend and I were discussing over skype about our distaste for mods that *force* you to go to the nether.

That being said, how do you guys feel about a fluid transposer recipe of a brick and lava creating a nether brick. I'm thinking 250mB of lava per brick?  It won't cover everything in the nether, but at least nether brick would be easier to get without having to find a fortress. And if you want lava in large enough quantities anyway, a trip to the nether is inevitable.

**Comment by KingLemming** [comment]
There's actually a recipe in the Induction Smelter for Nether Brick. Netherrack + Soul Sand.

I'll consider this though. :)

**Comment by Kodos-Atoz** [comment]
Indeed. Though my recipe would not require someone to actually go to the Nether, which is the entire purpose of the suggestion =) Thank you for pointing that out though.  Good info to have, in any case.

**Comment by Entoarox** [comment]
doesnt 1.7+ have vanilla netherrack > netherbrick (item) smelting?

**Comment by Kodos-Atoz** [comment]
You still have to go to the nether for the netherrack though. As I said, this is so there is a recipe for Netherrack that does NOT require an initial trip to the nether. Not to mention, even if you do go to the nether, sometimes nether fortresses are a pain to find.

**Comment by Entoarox** [comment]
@Kodos-Atoz that is my whole point with the 'netherrack > netherbrick' smelting recipe, since 1.7.10 you dont need to find nether fortresses anymore, simply getting to the nether is enough, and requiring people to go to the nether is an easy way for mods to limit certain content to mid-game instead of having it available early-game.

**Comment by Kodos-Atoz** [comment]
As I said, this is so there is a recipe for Netherrack that does NOT require an initial trip to the nether.

**Comment by Kodos-Atoz** [comment]
I'm well aware of what other mods do.

**Comment by KingLemming** [comment]
I added it and then commented it out in dev. I'm on the fence, not for balance reasons, but because of the physics at work here, since it sort of implies that Netherrack is just clay with lava. And at that point, it's a question of why not generate netherrack from clay and lava. Augh :/

**Comment by Kodos-Atoz** [comment]
Let's be honest, Minecraft doesn't have the best track record for realism.  I mean, look at water and lava mixing.  Whether you get cobblestone or obsidian is entirely dependent on which one's source block gets touched first. Or however that works.

**Comment by KingLemming** [comment]
No, it doesn't. But I try to keep everything internally consistent. This sort of opens a can of worms that I'm not sure I want to have to rationalize.

We'll see.

**Comment by zhs2** [comment]
Sounds like an interesting disabled-by-default-in-configuration-files solution for obtaining Netherrack, particularly in skyblocks or barren lands or even no-Nether that don't make use of Ex Nihilo (a tech solution, if you will), but in my opinion I'd think it'd make more sense to be able to farm Netherrack with an early/mid tech solution (induction smelting?) (also disabled-by-default-in-configuration-files) and then have to cook that in a furnace for your bricks. Additionally, all of this is kind of moot since it can also already be done in, say, Modtweaker...

**Comment by KingLemming** [comment]
Alright, so I've added this to the config but it is by default disabled.
