### ISSUE TITLE
[Thermal Expansion] Severe FPS drops when looking at active Tesseracts.

### ISSUE THREAD

**Issue by LanceShield** [CoFH/Feedback#332]
System Specs:

Processor: Intel Core i7
GPU(s): NVIDIA GeForce GT 650M 1024 MB and Intel HD Graphics 4000 1024 MB
RAM: 8 GB
RAM Allocated to Minecraft: 4 GB
Operating System: Mac OS X Yosemite
Java: Latest

Mod List: http://pastebin.com/6A1zQg3J

Whenever I look at an activated Tesseract while using version 1.7.10R4.0.0RC2 of Thermal Expansion, my frame rate drops from 60+ to 15 or less.

**Comment by KingLemming** [comment]
Your modlist isn't helpful as it isn't showing us exactly how out of date you are. (Because you probably are.)

Either way, your computer for whatever reason isn't properly switching your video card over to the nVidia when you play Minecraft. You'll have to figure that one out.

However, you can disable shaders in the /config/cofh/core/client.cfg.
