### ISSUE TITLE
Easy way to see machines affected by the Thermal Mediator 

### ISSUE THREAD

**Issue by alphacentauri7** [CoFH/Feedback#34]
OK, last one to bug you ;) I'm sure you have this one on your roadmap anyway.

Currently the mechanics of the Thermal Mediator are pretty opaque, as is to be expected with no docs yet. It seems to just affect directly adjacent blocks?

Anyway, it's pretty hard to notice the (33% ?) speedup just by looking at the progress arrow, so a better hint would be useful. Maybe just a modified progress arrow?

Keep up the amazing work; love your mods! ❤️️

**Comment by KingLemming** [comment]
It is a bit opaque, yeah. Honestly, that was kind of the intent for TE5. You'll notice I also don't have exact % on tooltips anymore.

I can't really do a modified progress arrow because the way it works is interface based, and other mods are going to use this too. I can maybe do something in the Mediator's GUI to give a rough idea of the amount of speed increase it's giving adjacent blocks though.

**Comment by alphacentauri7** [comment]
Hmm, yeah, I wondered about that. But doesn't that just make it harder for players to get these stats? If you want to get this detail now, you'll have to go look it up on some wiki or just look at the code. I always liked the easily available info that various mods add to item tooltips.

Can you elaborate the reasoning behind that? I'm guessing you want it to be more immersive and less min/maxing? I just feel that's a part that some players like about modded.

**Comment by KingLemming** [comment]
Basically yes, for immersion. But also because too much knowledge makes some players absolutely obnoxious. If I explain everything, I get a different line of comments which say things like, "X mod does Y feature better than you, plz buff," or "I did <whatever> and determined your % is incorrect, plz fix."

And those are just things I don't want to deal with. Also, it gives me the freedom to adjust mechanics without greatly modifying tooltips.

**Comment by SynfulChaot** [comment]
Hmm ... the problem with that reasoning, though, is that obfuscation of the mechanics doesn't alter the mechanics themselves.  Mod X will still do some feature better than Mod Y and some people will still complain.  All obfuscation does is make it harder to determine how much better or worse a feature operates.

Remember that the obnoxious, min-max players will go out of their way to determine the mechanics and complain no matter how difficult you try to make it to do so.  It's just in their nature.  Most of us just want to enjoy the mods and knowing how things work helps us to use them as well as we can.

**Comment by sp-guip** [comment]
I suggest adding a tab with machines effected by it.
and maybe 1.x of the normal speed.

**Comment by ShneekeyTheLost** [comment]
Even simply having a 'this machine is being affected by a Thermal Mediator at this time' flag. It doesn't have to say exactly what is going on, or even generally what is going on, simply a 'this machine is currently under the influence of a Thermal Mediator' notification on the machine's GUI would be awesome.

**Comment by ThorsHammer666369** [comment]
What is the rang of the Thermal Mediator and do other machines have to touch it to get the buff??

**Comment by KingLemming** [comment]
Only adjacent things.

**Comment by KingLemming** [comment]
After giving this some thought and then pondering the extra network overhead and tile logic on the server, it's something I ultimately just don't want to do, sorry.
