### ISSUE TITLE
Gaming Crashing When loading chunks in world

### ISSUE THREAD

**Issue by samiscool51** [CoFH/Feedback#340]
hey, the mod is crashing when i am generating new terrain or loading old ones
i have pinned it down to 2 mods that i have recently updated, COFH and RTG (realistic terrain generation)
i think COFH is causing this issue as reading the crash log, this pops up:
> at cofh.core.world.WorldHandler.populateChunkEvent(WorldHandler.java:141)

this does look to be caused by COFH as i do follow you on twitter and one of your tweets said that you did some hotfixes for thermal expansion and foundation which could cause the core mod to crash if something wasn't handled correctly, it could be possible that you broke something and didn't realize it (not judging you or anything, just examining all possible explanations)

affected COFH version: 1.10.2-4.1.9.13
list of mods
https://pastebin.com/ctXvDbDg
crash log
https://pastebin.com/j32Xbeea

**Comment by ElvenChaos** [comment]
I'm also getting the bug, and I verified that it happens when loaded along-side  RTG-1.10.2-4.1.2.4. _(This is the latest release version, *NOT* the alpha/beta snapshots)._ I've not tested this with the snapshots due to the volatility of the snapshots.

[Crash Log - Pastebin](https://pastebin.com/pw2MTVh3)
[FML Log - Dropbox](https://www.dropbox.com/s/fo76evclfgbhs7m/fml-client-latest.log?dl=0) _Warning: 7MB of loggyness!_

**Comment by KingLemming** [comment]
Honestly no idea what's happening here, but it's definitely xmod and not actually caused by us.

**Comment by samiscool51** [comment]
it could be RTG but the crash log says that COFH is causing the crash, also Pams harvest craft also has a hand in this as both

> com.pam.harvestcraft.worldgen
    at com.pam.harvestcraft.blocks

but the last update for it was 6/2/2017, about half a year ago, i don't think it's being developed for 1.10.2 anymore,
i also looked on RTG's issue page and there is no issue about world loading with COFH, the latest issue (as of this post) was 7 days ago and it talks about a different mod having problems with RTG (RTG structures generating in vanilla worlds), not COFH
and after changing the label to see how many issues has the label of "crash" nothing came up at all

**Comment by KingLemming** [comment]
The crash log doesn't say that CoFH is causing the crash. It say that a null pointer error is happening on that line.

If I hand you a bomb and it explodes, it's not your fault. It's mine, for handing you the bomb. That's how nulls work sometimes.

**Comment by KingLemming** [comment]
Also, just tested with RTG 4.1.2.4. No crashes. So there's a chance that it's another third party interaction which isn't even represented in that crash log at all.

**Comment by samiscool51** [comment]
hmm, i usually check what mod interacts with what other mod and i don't remember any mods that use COFH to generate terrain when it's present...
i will go and post over on the RTG issue page and see what team-RTG can understand from their side...

**Comment by samiscool51** [comment]
wait, thats not the RTG version i'm using, i'm using 4.2.0.0-snapshot-4
try again with that version and see if you can reproduce it, it might be something to do with the snapshot and COFH not agreeing on something

**Comment by ElvenChaos** [comment]
It was the version I was using, however, and I also have the bug. What KL is saying at this point is that a third mod is working with RTG to hand CoFHCore a bad null value, since RTG and CoFHCore don't cause a crash by themselves. I'm going to go through your mod list, find mods that match from my list, and see if I can find a third mod that causes issues with RTG and CoFHCore combined.

**Comment by samiscool51** [comment]
i don't know any mods that i have that use RTG as a parent or core mod as it would say it in it's description or when i was loading my game up

**Comment by ElvenChaos** [comment]
Alright, I've narrowed the crash down to the simultaneous usage of CoFH (and friends), RTG (I'm using 4.1.2.4), and Pam's HarvestCraft 1.10.2j. If one element of this triad is gone, there is no crash, but when all three are present CoFHCore gets handed a null.
_Note: When testing, I had to walk around for approx. 2 seconds to trigger the crash, but it is the same crash that has been reported._

[Crash Log](https://pastebin.com/Y0XPccx1)

**Comment by samiscool51** [comment]
hmm, i will remove pams and see if i get the same result...

**Comment by samiscool51** [comment]
not good, i'm still getting it without pams

**Comment by ElvenChaos** [comment]
Go through your mods and start trying different combinations -- try to eliminate out mods that don't crash from those that do. What I did was split the mods in about half, test one half, then test the other half (make sure you have CoFHCore and RTG in both instances). In whichever half crashes, repeat the process until you narrow down the mods that are causing your crash. When I did this, I determined HarvestCraft was in fact crashing. There may be another mod doing something similar, so get rid of harvest craft and do the process without it.

**Comment by samiscool51** [comment]
for me ars magica 2 causes a crash
crash log: https://pastebin.com/ms0PK9Xv

**Comment by KingLemming** [comment]
Yeah, so this is ultimately on RTG. I've been tracing through and I can get it to crash with only RTG in addition to CoFHCore.

This seems to be an underlying race condition with the way that RTG is firing events, and standard vanilla practices are not adhered to. Given the amount of try/catch blocks in their code, I don't think they are apt to care, however.

I can mitigate this, but I'm a little bit annoyed only because frankly I shouldn't have to. Events should be firing consistently when they are intended to. Either way, I'll resolve it on this end.

**Comment by srs-bsns** [comment]
> and standard vanilla practices are not adhered to.

RTG does not post `PopulateChunkEvent` events any differently than the vanilla chunk generators. Version 4.1.2.4 has been out for many months and this is the ONLY time this issue has arisen and it is only with COFHCore. It's pretty hasty to just outright blame RTG.

> Given the amount of try/catch blocks in their code

The try/catch blocks (irrelevant to this issue) have existed since the 1.7.10 version to swallow `ConcurrentModificationException`s in structure generation that plagued 1.7.10 (caused by recursive chunk generation from mods with bad world generators) but are kind of pointless now since the structure gen methods in Minecraft are now `sychronized`.

> I don't think they are apt to care, however.

Why would you assume this? Team-RTG cares about ALL issues that may be caused by RTG or are caused by some kind of compatibility issue between RTG and another mod, and we look into all of them unless it's apparently not an RTG issue.

> Events should be firing consistently when they are intended to.

Prove that the specific event involved is being improperly posted to the event bus by RTG and we'll fix it. Otherwise, please stop spreading FUD about RTG until the actual cause of the issue is discovered.

Also, perhaps next time you could try contacting us about the issue to help discover the cause and resolve it.

**Comment by KingLemming** [comment]
Fair enough. I apologize. I've been hit with a lot of nonsense lately and this was just further annoyance on top of it. I looked over the file in question, saw the try/catch and sort of assumed that you just expected errors to get thrown extremely routinely and the catching was your mitigation.

In any case, the crashing won't be happening anymore. Feel free to close it out on your tracker.

**Comment by whichonespink44** [comment]
> I found that when certain terrain - large mountains specifically - were generated, the post event would fire (or at least resolve on the event bus) before the pre event for some chunks. 

Thanks for the insight into what's happening, and for adding a fix to CoFH. We'll have a look and see if there's anything RTG can do to optimize its terrain generation. If the post event is resolving before the pre event in some cases, then it's only a matter of time before RTG runs into a problem with another mod.
