### ISSUE TITLE
Client crash on load

### ISSUE THREAD

**Issue by frenzye** [CoFH/Feedback#352]
Not sure if TE or TechReborn 

https://gist.github.com/frenzye/e143449f7b69fb6f3ebf0d40934a2b19

**Comment by KingLemming** [comment]
Might not be either one, as frustrating as that is.

This happens with a mod does OreDictionary registration in PostInit, which is a huge nono. The ore in question is from TechReborn, so that's certainly a good place to start.

However, it's possible that this is actually another mod entirely scanning the oredictionary doing doing registrations on what it feels are appropriate.

**Comment by frenzye** [comment]
your explanation immediately made me realize it was PrimalCore, having updated cofh/thermalexpansion and adding Primalcore at the same time. Thank you

**Comment by KingLemming** [comment]
Yep. Confirmed. PrimalCore does their OreDict registration in PostInit. Definitely not good.
