### ISSUE TITLE
Ore Dictionary default config for Redstone Furnace

### ISSUE THREAD

**Issue by Xiaminou** [CoFH/Feedback#359]
So from what I read when smelting ores or dust what's output by a machine is determined by the ore dictionary and if there are multiple ore dictionary entries and a priority list is not set it will randomly pick one as the default when you start your server.

The Redstone Furnace seems to be fine with most recipes however I have recently found that steel dust to steel ingot doesn't seem to have a priority list and therefore picks a random steel ingot from the ore dictionary whenever I restart my server, making it impossible to be used with Applied Energistics Auto-Crafting.

Someone should take a look at adding more ore dictionary priority list or even better, add a config file so that users can fix it themselves? (include a default config file)

**Comment by KingLemming** [comment]
It doesn't pick a random ingot, it picks the first one registered to the Ore Dictionary. That's not "random" unless your load order is competely random as well.

Frankly, Steel shouldn't have a Dust -> Ingot smelting recipe since that sort of trivializes its acquisition. It should be an induction smelter only recipe. I'll remedy that.

**Comment by Xiaminou** [comment]
Well load order must be random because one time I got Extreme Reactor's steel ingot, next one I got Immersive Engineering's and the one after that I got Mekanism's.

**Comment by KingLemming** [comment]
I've implemented something to address this in 1.12 and up. I won't be backporting it though.
