### ISSUE TITLE
[1.12] Crash Using Debug World Mode

### ISSUE THREAD

**Issue by SnowShock35** [CoFH/Feedback#362]
Hi KL,

I believe I've found a bug with CoFH Mods (Unsure as to which one it was) for Minecraft 1.12. Here are the details of the issue:

### Issue Information

- Minecraft 1.12
- Minecraft Forge 14.21.1.2406
- CodeChicken Lib 3.1.0.278
- Redstone Flux 2.0.0.1
- CoFH Core 4.3.1.6
- CoFH World 1.0.0.5
- Thermal Foundation 2.3.1.5
- Thermal Expansion 5.3.1.6
- Redstone Arsenal 2.3.1.5
- Thermal Dynamics 2.3.16

### Issue Description

When loading a world using the debug world generator type the game crashes immediately as you try to load the world with the below crash report. 

### Issue Reproduction

1. Launch Minecraft
2. Go to create a new world in the single player menu and select More World Options
3. Hold down the shift key and click the World Type button repeatedly until you've selected Debug mode
4. Then click Create New World

### Issue Media

- [Crash Report](https://pastebin.com/vwG6MtUc)

**Comment by KingLemming** [comment]
So, this is basically just a quirk of how Debug Mode works. It places down every single block it can find, even if they are not ready or code complete. That is what is happening here - it is placing down a block which is not obtainable under any typical means, and freaks out because the code for that block isn't finished.

TL,DR: Don't use Debug Mode.

**Comment by KingLemming** [comment]
Nah, no worries. It's just sort of one of those fundamental things where mods are coded for actual real conditions, and debug mode violates some of those.

I tried commenting it out and ended up with another crash elsewhere in a vertex buffer, so I'm just going to say there are a few too many issues here.
