### ISSUE TITLE
Entity registry

### ISSUE THREAD

**Issue by 007lord1** [CoFH/Feedback#374]
hello you'r mod is having a problem with conflicting entity ids
its using the vanilla entity ids which with like 8 other mods doing the same gets the ids over 128 witch crashes the game
so could you try to get the ids to register using forge so it will never conflict

the only entity is the Blizz from thermal foundation but its still better to use the rorge registery so thers no worry of entity conflicts

and I'm not sure if this is the place to post this but I couldn't find any other spots I could

**Comment by KingLemming** [comment]
Check TF's config file. You can force it to use a Forge ID if you want.

**Comment by Adaptivity** [comment]
Why not to just move to mod-specific ID and manually add spawn egg? Global ID bad thing, there are no point to keep it. You have nothing to lose if you'll use mod-specific ID because as I say it is possible to manually add spawn egg. And almost all mods moved to modded IDs. What do you think?

**Comment by KingLemming** [comment]
@Adaptivity - I don't see any way to do that. Spawn eggs require a global ID.

**Comment by Adaptivity** [comment]
You can't automatically add spawn eggs if you are using mod-specific Ids but you can do it *manually* without using a global ID. An example how to do that: https://github.com/portablejim/GraveStone-mod/commit/45510539002664c1a9f8edc5073505cea816e853 I think it's still better to fully move to modded IDs. So, you'll have no conflicts, no reports and nice spawn egg. Config option is not a solution it that place since you can make it better.
