### ISSUE TITLE
[ThermalExpansion] NPE on FluidRegistry.getFluidID

### ISSUE THREAD

**Issue by Jomik1** [CoFH/Feedback#391]
I'm getting this NPE when -creating- a new SinglePlayer world. After the game has crashed and I start up again, the world loads just fine. Just pretty annoying having to restart my game to create a world.
http://openeye.openmods.info/crashes/43cfb842681dd2435348a0a2662d9217
All the information you need should be there. Crash Log and Mod List.

**Comment by KingLemming** [comment]
This is an issue caused by a mod which does not properly register Fluids in accordance with the new Fluid API in Forge 1355.

Either downgrade Forge for the time being, or be a guinea pig. There's nothing actually wrong on TE's end, but the new Forge changed the Fluid API in such a way that certain mods were simply doing it wrong before, and as a result, we're ending up with null fluids.

**Comment by Jomik1** [comment]
Thanks for the quick reply. I didn't think it'd be an issue on TE's end, tbh. But I wasn't able to locate the error myself. Been out of "the loop" for too long.
Do you know what Forge version is "functional"?
