### ISSUE TITLE
(1.12) Poof! crashes (CoFH RF API)

### ISSUE THREAD

**Issue by Migmag789** [CoFH/Feedback#422]
I think it's the cofh api ;)
[crash-2017-07-25_14.58.28-client.txt](https://github.com/CoFH/Feedback/files/1173235/crash-2017-07-25_14.58.28-client.txt)

**Comment by KingLemming** [comment]
It's funny. It's like you read the crashlog and then didn't actually pay any attention to it.

This is an intentional crash, because you have another mod (mininglib) including an outdated version of the API, which the log clearly states. Remove that mod and report the issue to them as they are being very stupid.

**Comment by Migmag789** [comment]
Okay, thank you but I'm not a good crash reader and i'm french, so I don't understand everything ;)

**Comment by KingLemming** [comment]
Fair enough. Your initial post just came across as a little sarcastic, sorry.

**Comment by Migmag789** [comment]
Oops sorry x)
