### ISSUE TITLE
[Suggestion] make florbs more useful?

### ISSUE THREAD

**Issue by Paul17041993** [CoFH/Feedback#434]
you can use tanks instead of buckets to craft with liquids, so why not florbs too? or at least make them drainable in the fluid transposer so you don't have to throw-and-bucket each extra you don't want.

The catch is that they get destroyed completely regardless of the use, basically making them a one-use, stackable bucket that's slightly more convenient than tanks when you want specific amounts of fluid when crafting.

**Comment by KingLemming** [comment]
Florbs aren't coded as FluidHandlerItems, and turning them into such would really screw with worlds where they already exist.

It would also get rid of Magmatic Florbs entirely, due to the special-case logic required by FluidHandlerItems and then there would also be a lot of unwanted bucket-style interactions.

So no, won't be doing this for those reasons, sorry.
