### ISSUE TITLE
[1.11.2] Thermal Dynamics: Strange light behaviour with pipe covers

### ISSUE THREAD

**Issue by PearlCanopus** [CoFH/Feedback#447]
Forge: 13.20.1.2386 f. MC 1.11.2
Thermal Dynamics: 2.2.6.13 f. MC 1.11.2
Optifine: 1.11.2 HD U C3
No shaders or dynamic lights in use and medium to low graphics settings.

When I cover a pipe the texture appears darker than the blocks with same texture around. Lighting the surface i.e. with a torch do not change this behaviour.
There are no differences between vanilla or chiseled textures.

Because I can always see, where pipes are placed, I don't really know whether this is a bug or a feature. :)

**Comment by covers1624** [comment]
Hmm, This is a quite complex issue to solve and should be fixed when i rewrite the rendering backend for the ducts, This is basically next on my list. So for now im going to leave this open as a reminder, i wouldn't consider it a bug because its just an optimization of the current rendering pipeline.
