### ISSUE TITLE
[Thermal Expansion] crash with autonomous activator being placed

### ISSUE THREAD

**Issue by zed-hex** [CoFH/Feedback#454]
When moving an autonomous activate with funky locomotion when it was powered by a Redstone signal would cause a crash. This lead me to an investigation on what was causing the crash and from this testing I found if an autonomous activate is placed near any form of Redstone signal it can randomly crash so I am guessing these crash bugs are related. If you want to replicate my testing just place and breaker an autonomous activator (next to some thign like a redstone block) and within about 10 second there will be a crash. (this was also tested with other machine from the mod and they seem ok)

Also when testing I tried the FTB infinity pack to see if it was just an error my side and I also got the same result a crash when placing an autonomous activator 

Crash report when placing autonomies activator: http://pastebin.com/BGFwWPNq
Whit this crash the world is recoverable^  

Original crash with funky locomotion: http://pastebin.com/3z9Qv6rf 
With the original crash the world could not be recovered by just re opening the world^

Related mods: Thermal expansion build 4.0.1-182, Forge 1373

**Comment by KingLemming** [comment]
Not seeing this. Also not seeing what on that line could possibly be null and the game still be in a valid state.

**Comment by jadedcat** [comment]
I see this a lot on AgSkies issue reports. All of them accompanied by : 

       Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine

I do not know for sure that its optifine, but every one I have seen includes optifine.

**Comment by BoboSims** [comment]
@jadedcat: What that line is actually trying to say, I believe, is that anyone getting this error, should *NOT* report it to the Mantle author, because optifine - a mod that Mantle does not support - is installed in that specific game. They obviously feel that if you include an unsupported mod, the crash is no longer their responsibility. They consider it user error.

I can stand behind such thinking, actually.

**Comment by XFactHD** [comment]
From my understanding those two crashes are completely different. The one with funky locomotion could be that the tile entity isn't completely moved before it gets a redstone signal which would mean that the problem is on the side of funky locomotion. The other crash could be something creating a sync issue between server and client.

**Comment by ikkonoishi** [comment]
Here is a crashlog of this issue without optifine. Happens whenever I place a preconfigured AA next to active redstone.

https://gist.github.com/ikkonoishi/0f377b2e949876a9a4a7

Steps to reproduce.

Place AA, give it power, set it to require a high redstone signal, remove it with a wrench, and place it next to a block of redstone.

**Comment by KingLemming** [comment]
Thanks. That makes WAY more sense.
