### ISSUE TITLE
AIOOBE in SimulatedInv.func_70301_a

### ISSUE THREAD

**Issue by riking** [CoFH/Feedback#470]
Modpack: Agrarian Skies 2

http://paste.linuxmint.com/view/jvzl/
```
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 4/27/15 11:07 PM
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 1
	at cofh.thermaldynamics.duct.item.SimulatedInv.func_70301_a(SimulatedInv.java:70)
	at cofh.lib.util.helpers.InventoryHelper.insertItemStackIntoInventory(InventoryHelper.java:153)
	at cofh.thermaldynamics.duct.item.TileItemDuct.simTransfer(TileItemDuct.java:843)
	at cofh.thermaldynamics.duct.item.TileItemDuct.simTransferI(TileItemDuct.java:757)
	at cofh.thermaldynamics.duct.item.TileItemDuct.canRouteItem(TileItemDuct.java:729)
	at cofh.thermaldynamics.duct.attachments.servo.ServoItem.findRouteForItem(ServoItem.java:353)
	at cofh.thermaldynamics.duct.attachments.servo.ServoItem.getRouteForItem(ServoItem.java:447)
	at cofh.thermaldynamics.duct.attachments.servo.ServoItem.handleItemSending(ServoItem.java:279)
	at cofh.thermaldynamics.duct.attachments.servo.ServoItem.tick(ServoItem.java:194)
	at cofh.thermaldynamics.duct.item.ItemGrid.tickGrid(ItemGrid.java:56)
	at cofh.thermaldynamics.core.WorldGridList.tickEnd(WorldGridList.java:63)
	at cofh.thermaldynamics.core.TickHandler.tick(TickHandler.java:95)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_411_TickHandler_tick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

.
.
.

	CoFHCore: -[1.7.10]3.0.2-262
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182

```

**Comment by KingLemming** [comment]
Have any idea which inventory is lying?

**Comment by riking** [comment]
It seems that we were only using itemducts on the Ex Niliho crucibles.

**Comment by riking** [comment]
Note that there was a while where this was working fine without crashing.

**Comment by riking** [comment]
The truth comes out!

A stone button (vanilla) was in the chest, and the game crashed when the duct tried to put it in the crucible.

**Comment by KingLemming** [comment]
I'm checking to be sure it isn't anything on our end, but offhand it seems like it'd be the Crucible stating it has an inventory of size 1 when it doesn't.

**Comment by Lunatrius** [comment]
Poked at the Ex Nihilo code and `getSlotsForFace` is implemented as (will try to dig deeper into it later today):
```java
public int[] func_94128_d(int side) {
    if (side == 1) {
        return new int[] { 1 };
    }
    return new int[0];
}
```

**Comment by KingLemming** [comment]
Okay first of all - you should be returning predefined things. Somewhere in the code, you need:

public static int EMPTY_INVENTORY = new int[] {};

and then for the slot:

static int CRUCIBLE_INVENTORY = new int[] {0};

By the way, I think that's the problem. It's supposed to return a list of available slots. How many slots are there? Because the code as it stands suggests there are at least 2 slots, and slot 1 is open.

**Comment by Erasmus-Crowley** [comment]
That code says that there is one slot (slot 1), available from the top side and no others. The length of the array is 1. The only available slot is at index 0 in the array.

I don't understand how you could get two slots from that code. There is no functional difference between 'new int[0]' and 'new int[] {};

Or am I not understanding something correctly?

**Comment by riking** [comment]
> By the way, I think that's the problem. It's supposed to return a list of available slots. How many slots are there? Because the code as it stands suggests there are at least 2 slots, and slot 1 is open.

Well, `getSizeInventory()` returns 1, but `getAccessibleSlotsFromSide()` returns either a 0-length array or a 1-length array depending on whether insertion is allowed from that side.

*BUT*

The exception says "Array index out of bounds: **1**", which suggests that you accidentally tried to access the SECOND slot.

**Comment by Erasmus-Crowley** [comment]
In your SimulatedInv class, you are assuming that that the slot ID and the array index are going to be the same. In the case of crucibles, they are not.

You are calling Crucible.getSizeInventory and I'm returning 1.
You are then initializing an array of ItemStack with a size of 1. This is correct, because the crucible only has one visible slot, but the actual item for slot 1 is at index 0 in your array.
Later, you are calling SimulatedInv.getStackInSlot and correctly passing in 1, because the slot ID is 1, but you are looking for your ItemStack index 1 instead of realizing that slot 1 is located at index 0. The index 1 is out of bounds.

Aren't inventory slot numbers arbitrary? No one has ever required them to start at 0 before.

**Comment by KingLemming** [comment]
They are not arbitrary. If you have one slot, the index of that slot is 0. Why would it be anything else?

**Comment by Erasmus-Crowley** [comment]
The crucible doesn't keep a true internal inventory. As soon as an item is inserted it is destroyed. I implemented ISidedInventory in a way that fakes it. At the time I used the slot number as a way to help keep the sides and slots straight on my barrels (side 0 = slot 0, side 1 = slot 1) and carried that convention over to the crucible. It's a fairly easy change, and I've already asked Insaneau if he would include it in his next build, but that code has been that way since the first day I wrote it and it has worked with every other item transport system ever made, including your previous implementation.

**Comment by KingLemming** [comment]
If you have a virtual slot, it should be the same virtual slot every time. :) We do the same thing with the Nullifier.

IMO, it was a bug that it worked before.

**Comment by Erasmus-Crowley** [comment]
It is the same virtual slot every time. That never changes. It's just slot number 1, not slot number 0.

**Comment by jadedcat** [comment]
So far the only mod I don't get this crash with, when putting cobble into a crucibe, is the vanilla hopper and ExU. All other transfer systems so far crash :(

**Comment by KingLemming** [comment]
The vanilla hopper does things as a player would. It is amazingly, horrifyingly, inefficient.

**Comment by Erasmus-Crowley** [comment]
Oh. Well damn. I need to spend more time on IRC apparently.

**Comment by KingLemming** [comment]
k, well if this is being solved, I'll shut this down. :)
