### ISSUE TITLE
Viaduct not working。

### ISSUE THREAD

**Issue by jimmypig9487** [CoFH/Feedback#504]
**I'm from TW ,english is not good :(
Viaduct not working,I didn't press shift or any。
See the video :    https://youtu.be/8buwsG_WBb4
something wrong?

sorry I use cracked ,because I'm a student。

forge version:1.11.2-forge1.11.2-13.20.1.2429** 

mod list: 19 mods
Better-Builders-Wands-Mod-1.11.2
BetterFps-1.4.5
buildcraft-7.99.7
CodeChickenLib-1.11.2-3.0.0.284-universal
CoFHCore-1.11.2-4.2.7.15-universal
ElevatorMod-1.11.2-1.3.2
energyconverters_1.11.2-1.0.1.22
ExtremeReactors-1.11.2-0.4.5.30
industrialcraft-2-2.7.81-ex111
jei_1.11.2-4.5.0.295
OptiFine_1.11.2_HD_U_C3
refinedstorage-1.4.20
ThermalDynamics-1.11.2-2.2.6.13-universal
ThermalExpansion-1.11.2-5.2.6.22-universal
ThermalFoundation-1.11.2-2.2.5.16-universal
TreeCapitator-Mod-1.11.2
VeinMiner-1.11-0.38.1.635+dc28c7d
worldedit-forge-mc1.11-6.1.6-dist
zerocore-1.11.2-0.1.0.6

**Comment by jimmypig9487** [comment]
+1 error whe I use optifine's connected textures the all ducts icon display is incorrect(just like error texture)

**Comment by KingLemming** [comment]
They work. It's specific to your setup and/or mod combination. May have something to do with the cracked game.

And yes, Optifine messes up everything. It's basically a terrible mod.

In any case, this is tech support and not an actual code issue, because we know that the ducts work. And we can't offer support to pirates, sorry.
