### ISSUE TITLE
COFH Core crash with Intel Mobile Series 4 Express graphics

### ISSUE THREAD

**Issue by TheOldOne822** [CoFH/Feedback#509]
I receive a used laptop and am unable to run COFH core and therefor any COFH mods. Minecraft/forge mods works without COFH core but about 9 times out of 10 with COFH will crash with java native code crash and the few times it doesn't the menu background renders in a tiny box in the bottom left of the screen with no menu to click on. Attempting to get a screenshot of that failed. Crash does not happen with RC7 but all newer versions tested did crash.

Tested with forge 1400 1291 and 1352

Tested versions
CoFHCore-[1.7.10]3.0.0RC7-211 Works
CoFHCore-[1.7.10]3.0.1-254 crash
CoFHCore-[1.7.10]3.0.2-262 crash
CoFHCore-[1.7.10]3.0.2-276 crash

logs
Crash full forge log
http://pastebin.com/wCYry9gj
Crash java native (it does not create a minecraft crash log)
http://pastebin.com/RpQY6fus

non crash render error full forge log
http://pastebin.com/j4CPHuPs

**Comment by 3Pixel** [comment]
try installing java 8 and see if that works

**Comment by evknucklehead** [comment]
Also, check to make sure your graphics drivers are up to date. Based on the file listed in the Java crash dump, it looks like you're running an Intel graphics chip, so go to intel.com and download the newest driver for your chip.

**Comment by TheOldOne822** [comment]
I did test with java 8, made no difference.
The drivers are the "newest" ones from the Intel website and the newest ones that supports OpenGL 2. There are newer drivers on windows update than do not support OpenGL 2 so Minecraft will not run at all with them.
I have tested with 4 other computers and COFH Core works fine on them so I am sure it is something with this laptop but as RC7 works I am reporting it hoping whatever it is can be found and perhaps an option added for compatibility.

**Comment by evknucklehead** [comment]
Which graphics chip do you have?

**Comment by ZeethKyrah** [comment]
I have an old Compaq Presario. Its GPU is an Intel Mobile Series 4 Express, and its latest drivers are about two years old now (I updated to the Intel drivers last night before continuing my tests). This chipset does OpenGL 2.2, but it apparently does NOT have the hardware framebuffer that CoFH Core expects. I keep getting Java crashes with CoFH Core; installing Optifine turns it into a Forge error notice instead, with one GL error saying "invalid enum" when CoFH Core loads (this is where Java crashes otherwise) and when Minecraft is loaded, the screen renders badly with a continuous stream of Gl errors regarding the frame buffer.

Please note that this is similar to the rendering issue that Portal Gun had "way back when", and that OpenBlocks makes note of the problem and works around it. So there IS a way to at least kludge or hack around the problem.

**Comment by TheOldOne822** [comment]
I have Intel Mobile Series 4 Express on this laptop. I know it's not a great system but my Macbook Pro died after 7 years of use and I don't have the money to replace it ATM.

**Comment by bochen415** [comment]
@TheOldOne822 Can you uninstall Slysoft AnyDVD for a moment, reboot the pc, and re-check the game?

'0x000000000d440000 - 0x000000000d45b000         C:\Program Files (x86)\SlySoft\AnyDVD\ADvdDiscHlp64.dll'

**Comment by TheOldOne822** [comment]
Still crashing with it removed. As someone who works in IT can I express my dislike for programs that leave things behind when you uninstall then that must me removed manually.

http://pastebin.com/RXCy2yHF

**Comment by evknucklehead** [comment]
My computer has the desktop version of this chipset, so I pulled my Geforce 8600 out to test this. It crashes, but doesn't crash in the same way. Instead of a Java crash report, it triggers a Windows Crash Report saying it was ntdll.dll that had the fault. 

Tested on Intel G45 desktop chipset, Windows 7 x64, Java 8 Update 45, Forge build 1403, CoFH Core build 282. 

fml-client-latest.log: http://pastebin.com/D365JNDX

Windows Crash Report (XML Format): http://pastebin.com/5be03s92

**Comment by Dudblockman** [comment]
I can confirm this crash too. I disabled every mod and added them back one at a time, and then used COFHCore alone. COFHCore is verified to be the source. 

From using FTB Trident pack.

fml-client-latest.log: paste.ubuntu.com/11419723/

**Comment by PawnedSauce** [comment]
I have the same problem in which it only exists in the newer versions of CoFH Core as the OP stated, same results for the same versions listed. I have the desktop version of the Intel G43/G45 Chipset. The only mods that were in my Minecraft environment were those of TeamCoFH.

**Comment by JZELITE** [comment]
I have a similar issue, when I load up COFH mods for forge 355+, the main menu screen is localized to the bottom left of my screen. I can still click buttons to open a world (I do this from memory of their location, as I cannot see them) when the world opens, it is just a light blue/grey. I had this same issue with the 291 versions when they first came out, but it was eventually fixed.

**Comment by PawnedSauce** [comment]
@KingLemming Any feedback or thoughts on this issue? It seems that it has to do with CoFH wanting to check for at least a minimum of higher spec hardware

**Comment by Papapayana** [comment]
was having the same issues it seems the forge page cant be handled   http://www.minecraftforum.net/forums/support/modded-client-support/2430237-issue-with-cofhcore   < fixed the issue

**Comment by KingLemming** [comment]
Unfortunately, the hardware check has to be there. If it's something the Intel chipset can't handle, then disable the splash screen, as the link above states.

**Comment by TheOldOne822** [comment]
Disabling the splash screen does stop the crash but does not the render error that hides the menu and stops the world from rendering if you get in game by clicking where the menu should be.  The JVM argument -Dforge.forceNoStencil=true does fix it. It is a bit of a hassle needing to re add it to the JVM arguments every time I want to play but that is a complaint for the curse team.

**Comment by SupaSpider** [comment]
Hey the old one, how do you get to that, i have this problem too, and i really want to learn how to fix it.
