### ISSUE TITLE
[Thermal Dynamics]

### ISSUE THREAD

**Issue by whitestarx0312** [CoFH/Feedback#513]
Fluid retrievers attached to a tank don't seem to pull from all attached sources. My setup is pulling lava from 8 different containers, but the retriever is only pulling 1mb from the first source.

These screenshots were taken about 2 seconds apart.
http://imgur.com/a/qqYcC#qPftRw2

**Comment by adudney** [comment]
I'm not sure you're supposed to be able to access fluid from the sides of the portable tank, try plugging the retriever into the top of the tank and see if it works then.

**Comment by whitestarx0312** [comment]
I read in a change log that fluids can be manipulated from all sides. I also just tested inserting from top, extracting from bottom and the retriever is still being weird.

**Comment by XFactHD** [comment]
The sense of the model of the tank is to only use the top and bottom.

**Comment by whitestarx0312** [comment]
Lol that's great, however I read in a changelog that all sides should be accessible.

**Comment by Entoarox** [comment]
Originally implementations of iSided fluid transfer systems only worked from top or bottom, but any system that did not use iSided inputs worked from any side (likely as a form of compatibility since few fluid systems originally had iSided-ness functionality to them)
Unless they recently change this, that should still be so, but they might have actually gone "screw logic, we're tired of everyone complaining" and changed it.

**Comment by adudney** [comment]
Note: I just tested it in game, and inputting to the sides works perfectly fine. This bug report is about the fluid retrievers not working on the sides, which may be unrelated.

**Comment by whitestarx0312** [comment]
Haha finally someone understands that this issue is not about whether you can input from the sides, but rather about retrievers working on the tanks.

**Comment by KingLemming** [comment]
We understood from the start, I thought this was just too funny to say anything.

**Comment by whitestarx0312** [comment]
Haha very funny -_-
