### ISSUE TITLE
[Thermal Expansion] Autonomous Activators Charge Inventory Items [Feature Request]

### ISSUE THREAD

**Issue by DrZed** [CoFH/Feedback#524]
Autonomous Activators Charge Inventory Items When used from the internal capacitor... It'd be nice for say my tree farm
http://puu.sh/hOgDo.png
Uses Draconic Axe to fell trees so it'd be nice if it auto charged

**Comment by KingLemming** [comment]
It's been requested before, but it also sort of destroys the purpose of having a dedicated charging machine.

Unsure.

**Comment by RAnders00** [comment]
Ender IO nicely puts a bridge there. It has a RF charge filter (or something like that, I forget what it's called) that lets you charge the item easily. Kind of makes for some more complex builds than one end-all solution.

**Comment by Zyx-2000** [comment]
I think this would just make things worse. A big problem with many minecraft mods is that they basically play the game for you, and you won't have any reason to do the corresponding thing yourself. You *can* currently make a setup that automatically recharges items when needed. But with the change suggested here, the reason to do so would be gone, along with the fun that comes with it. Because the game would do it for you.

**Comment by DrZed** [comment]
Mkay Thanks for the feedback :P

**Comment by KingLemming** [comment]
I'm not ruling it out as a potential Augment, but it definitely won't be built in. ;)

**Comment by DrZed** [comment]
Thanks Lemon ^_^ Maybe recipe along the lines of {Electrum; Energy Cell ; Electrum
conductance coil; transmission coil; conduct coil
electrum; cell; electrum}
