### ISSUE TITLE
[Thermal Dynamics] [Agrarian Skies 2] #2

### ISSUE THREAD

**Issue by whitestarx0312** [CoFH/Feedback#526]
Alright so this crash is a little different. I managed to get into my world via removing Thermal Dynamics, letting it rid the world of its items, and then readding it. Now I can play normally. However if I leave the game for any reason and attempt to join the server, my client crashes with this log. Everything is fine again when I reload my client.

Log: http://pastebin.com/7YT0V58u

Agrarian Skies 2: 1.0.41
Forge: forge-10.13.3.1401
CoFH Core: CoFHCore-[1.7.10]3.0.2-262
CoFH Lib: CoFHLib-[1.7.10]1.0.1-151
Thermal Dynamics: ThermalDynamics-[1.7.10]1.0.0-122
Thermal Expansion: ThermalExpansion-[1.7.10]4.0.1-182
Thermal Foundation: ThermalFoundation-[1.7.10]1.0.0-81
*I am using Fastcraft and Optifine.

**Comment by KingLemming** [comment]
Yeah, you've managed to destroy your world somehow. Do you have any contraptions that move blocks?

**Comment by whitestarx0312** [comment]
Nope, not even any mods in the pack that could move blocks, nor piston machines.
I can still play like normal, but I cannot rejoin after I leave the server until I restart my client.

**Comment by KingLemming** [comment]
Ah. I know what happened here. This is sort of on you, due to your hacky work-around.

By removing the mod, you've basically hosed your game up. The save data now has tiles associated with air blocks.

FML doesn't handle this well, and when you re-add the mod, it'll use a different set of IDs and everything. Pretty unadvisable.
