### ISSUE TITLE
Launch

### ISSUE THREAD

**Issue by BomberMax2000** [CoFH/Feedback#529]
Help. I try to launch Minecraft with Thermal Dynamics 2.1.5. Asks for 2.0.5, then says that there are 2 versions of TD. What do I do?

**Comment by Tahakk** [comment]
Go [here](https://minecraft.curseforge.com/projects/thermal-dynamics/files), select your _Game Version_ and download newest TD version that is available for that version of MC. 

Eventually look trough dependencies for other mods needed (CCL and others) and get their newest version for your MC too. If that still doesn't work try to update your Forge (recommendet version is not newest). 

If that **still** does not work come back and give us your crashlog. Otherwise not sure how to help you. 
btw. you should not have 2 versions of same mod in your _mods_ folder.

**Comment by KingLemming** [comment]
You're doing something very wrong. Also, please use Twitch for tech support. This is for issues with code.
