### ISSUE TITLE
[1.12] [Thermal Dynamics] Itemduct filter keeps disappearing. Has to be recrafted and replaced.

### ISSUE THREAD

**Issue by JaSpr** [CoFH/Feedback#542]
One itemduct connection in particular keeps losing its filter.  Pretty much every time I log in, it is gone again.  Sometimes I don't have to log out for it to disappear.  This causes a bunch of items that shouldn't be in the chest that it's feeding to end up in it.

### VERSIONS

Thermal Dynamics: 2.3.5.12
Minecraft: 1.12.1
Forge: 14.22.1.2478
PACK: All The Mods 3, v3.2b
CofH Core: 4.3.5.13, CofH World: 1.0.1.8
Thermal Foundation: 2.3.5.14, Thermal Expansion: 5.3.5.19

[screenshots](https://imgur.com/a/wG2NK)

**Comment by KingLemming** [comment]
As with your other issue,this is caused by a mod you have smashing the NBT stack on save/load and generally screwing things up. Again, I can't tell you which mod that may be.

**Comment by JaSpr** [comment]
Thanks!

**Comment by KingLemming** [comment]
No problem! Wish I had a better explanation for you.

Also, the 1.12.2 update *just* fixed a long-standing bug with Tile Entities and unloading, so that might also end up helping. It's one of the more sensitive areas of the game, and unfortunately if anybody screws it up, it can break things all over the chunk.
