### ISSUE TITLE
[Thermal Expansion 1.11.2-5.2.7.24] Infinite redstone

### ISSUE THREAD

**Issue by osmarks** [CoFH/Feedback#577]
1. Place a Pulverizer, power it, upgrade it and fill all available augment slots with auxiliary sieves.
2. Pulverize a redstone lamp.
3. Craft what comes out back into a lamp.
If you repeat this enough, you'll find that you have more redstone than you started with.
The problem here seems to be that the auxiliary sieves push the probability of getting redstone (which starts at 100%) above 100%, meaning that sometimes you'll get twice the redstone out.

**Comment by KingLemming** [comment]
Ehhh...please update to 1.12. 1.11 is a dead version.

I'll have a fix for this, but I'm honestly not sure that I'm going to backport it to 1.11.

**Comment by hugeblank** [comment]
1.11.2 is arguably not a "dead version". There are still many mods that have yet to update to 1.12. And why wouldn't you backport it? There's no reason not to, seeing as it's really easy to merge changes from 1 version to another

**Comment by KingLemming** [comment]
It's not actually easy, no. It's annoying. The code change? Sure.

Then I have to edit changelogs, bump build number, etc. Because if I don't do all that, people whine that I didn't do literally everything they could possibly ever ask for.

And that gets *extremely* old when trying to support multiple versions.

**Comment by covers1624** [comment]
Gonna leave this open until the fix is actually live.
