### ISSUE TITLE
[CoFH World] Decoration generator doesn't work

### ISSUE THREAD

**Issue by AfterRebelion** [CoFH/Feedback#586]
If you try to use the decoration generator, like this, it doesn't generate anything:
```
{
	"populate": {
		"testing_1": {
			"distribution": "decoration",
			"generator": {
				"type": "decoration",
				"block": "minecraft:wool",
				"material": "minecraft:air",
				"cluster-size": 5,
				"surface": "minecraft:grass"
			},
			"cluster-count": 5,
			"chunk-chance": 1,
			"retrogen": true,
			"biome": "all",
			"dimension": "all"
		}
	}
}
```
But if you change the generator to other type, like cluster, it works on the overworld.
```
{
	"populate": {
		"testing_1": {
			"distribution": "decoration",
			"generator": {
				"type": "cluster",
				"block": "minecraft:wool",
				"material": "minecraft:air",
				"cluster-size": 5,
				"surface": "minecraft:grass"
			},
			"cluster-count": 5,
			"chunk-chance": 1,
			"retrogen": true,
			"biome": "all",
			"dimension": "all"
		}
	}
}
```

**Comment by KingLemming** [comment]
Okay. Will remove it then, thanks.

**Comment by mankra** [comment]
Don't know wether you're serious about removing it, but I found that it's working perfectly.

There's a generator value called "check-stay" which defaults to true, so if you want to place non-plants or plants from mods (e.g. botania) you'll have to set it to false, otherwise the blocks won't generate.

Don't use cluster, as with a bigger cluster size, it results in plants sitting on top of plants.
