### ISSUE TITLE
Incompatability with Server Sync

### ISSUE THREAD

**Issue by TheQuantumGeneral** [CoFH/Feedback#596]
Having an issue which only arises when I add Thermal Foundation to my instance that has Server Sync active.

Issue in question referenced here - https://github.com/superzanti/ServerSync/issues/11

Crashes to desktop on server connect with a null pointer/ticking screen error. Removing Thermal Foundation or Server Sync resolves the issue. Out of a hundred or so mods these two do not agree with each other.

Here's the crash report it generates - http://pastebin.com/MaN4997N

Here's the full log - https://paste.ee/p/4LBiF

**Comment by KingLemming** [comment]
There's nothing in that log that points to us in any way whatsoever I'm afraid.

I'm fairly confident it's not on our end, but I can't blame ServerSync either. My guess is actually it's another mod altogether and it's causing it due to some sort of strange N-way interaction when a certain combo is installed.

Can you make it happen with *just* ServerSync and CoFHCore/TF?
