### ISSUE TITLE
Cofh Dev

### ISSUE THREAD

**Issue by enterprise12nx** [CoFH/Feedback#597]
It would be extremely helpful if your dev versions, or your updates in general had a changelog...

how am i suppose to check if something was fixed?
just really saying...only mod i haven't seen with a changelog

is this problem even fixed in the dev versions? https://github.com/CoFH/Feedback/issues/475

**Comment by KingLemming** [comment]
Our updates DO have changelogs. They are here:
https://github.com/CoFH/Version
and are always updated and copy/pasted to Curse when we release a new version.

When something is marked as "fixed in dev" that means we haven't officially released that version. It's available as an alpha because things auto-build, but those *really* aren't recommended.

Otherwise, you can find the issue under "Closed" with the label, "Fixed."

**Comment by enterprise12nx** [comment]
it may be a changelog but say Thermal dynamics has one post

**Comment by KingLemming** [comment]
Yes. I wrote the changelog well before the mod came out. The most recently released version is still 1.0.0.

**Comment by enterprise12nx** [comment]
either way, for the issue i referred to which dev version is it fixed in, the chunk is corrupt even after using mcedit, so i need it fixed

**Comment by KingLemming** [comment]
The chunk isn't "corrupt," and from the sounds of it you didn't use MCedit right.

Would I like it released? Yes, unfortunately there's a confluence of events preventing us from pushing one at this time. I'll see if I can get things in motion for a weekend update.

**Comment by enterprise12nx** [comment]
i use mcedit all the time, its possible that it effected multiple blocks around it which is why just removing that block hasnt fixed it, especially since this guys base is a cluster lol.

ty, i hope it gets released soon

**Comment by enterprise12nx** [comment]
noting yet D:
