### ISSUE TITLE
[Minefactory Reloaded] IndexOutOfBoundsException on server startup

### ISSUE THREAD

**Issue by stardustrider** [CoFH/Feedback#600]
http://pastebin.com/Ut6hQMSS

Currently only occurs when starting up the server. Client is fine.

Forge: 10.13.4.1448
All CoFH mods are up to date.

**Comment by KingLemming** [comment]
That means that something has gone wrong with your world. It's not MFR.

You traced the crashlog to MFR, but you traced it too far. It's the fault of one of the lines above it.

The actual crash seems to be caused by om.InfinityRaider.AgriCraft.blocks.BlockModPlant.getRandomFruit(BlockModPlant.java:141)
