### ISSUE TITLE
Can't open the Servo, Filter, nor Retriever GUI's

### ISSUE THREAD

**Issue by LittleWhispers** [CoFH/Feedback#608]
I've searched for countless hours to find out what's wrong by searching online and trying various things, but I still can't seem to edit the settings on any of those parts. The only thing I can find is, with an empty hand, right clicking on one of them when they're placed on either a fluiduct or an itemduct which doesn't work. My character plays the animation of "punching" at it as if I were actually interact with it, but regardless, nothing happens.

I'm currently playing on Minecraft 1.12.2 with ThermalDynamics 1.12-2.3.4.11. Note, I'm also playing with a pretty large list of other mods but everything besides this is working just fine for me.

**Comment by KingLemming** [comment]
Without any sort of logs or videos, we can't really know what you're doing / have done wrong, but it's unique to your setup and is basically tech support - almost certainly caused by another mod.

Please feel free to follow up in twitch chat: https://www.curse.com/invite/SipeCoinsSvalna

I hope you can understand that when you are literally the only report of this in millions of downloads, it's your setup and not the code. But we'd like to help.
