### ISSUE TITLE
Thermal Expansion; Satchel dupe bug

### ISSUE THREAD

**Issue by misio345** [CoFH/Feedback#61]
Mod version: ThermalExpansion-[1.7.10]4.0.0B8-23.jar
Mods I have installed: https://dl.dropboxusercontent.com/u/51182936/neiintegration_loadedmod.csv
Crash log: none as it's a dupe bug not a crash
Beeing descriptive: If you have a satchel and you put something in it and then try to open at the same time you press "q" it will open its gui with items you have put in it, stay in your hotbar and a copy of it will drop on the ground in front of you, so after that operation you have 2 times items you have put in a satchel and two satchels.

**Comment by chrixian** [comment]
My issue seems related to this so rather than create a new issue:

Using ThermalExpansion-[1.7.10]4.0.0B8-23... I updated CoFH Core, Thermal Foundation and CoFH Lib to the latest versions on CurseForge (CoFHCore-[1.7.10]3.0.0B9-106, ThermalFoundation-[1.7.10]1.0.0RC1-35, CoFHLib-[1.7.10]1.0.0B9-69 respectively) and now my satchels are "stuck" with the items that were in them before I updated-- I can pull items out and put items in but when the satchel is closed and reopened it goes back to how it was initially (any new items I put in are gone, any items I pulled out are back again).

**Comment by Revemohl** [comment]
I can confirm that the issue above is still happening on CoFHCore 3.0.0B9-119 and CoFHLib 1.0.0B9-78.
In fact, it seems to have started right after https://github.com/CoFH/CoFHLib/commit/fd877316ec4d65eff2797fb4adcc7abcfef380f3 , on CoFHLib 1.0.0B9-69 (it doesn't happen with B9-68).

**Comment by skyboy** [comment]
Does this still happen in the version that'll be coming out within an hour of this post?

**Comment by Revemohl** [comment]
After just a quick look, nope.
