### ISSUE TITLE
Enchantments do not have description

### ISSUE THREAD

**Issue by C0rn3j** [CoFH/Feedback#619]
![image](https://user-images.githubusercontent.com/1641362/32418939-916f58f6-c272-11e7-9f35-700edb616d7d.png)
Using MC 1.12.2 and forge 2529, latest version of this mod(Don't hate me for saying "latest" please ^^)

**Comment by KingLemming** [comment]
No. There are no descriptions for enchants. You have a mod which adds that feature.

They need to NOT attempt to localize if there isn't one. Go take that back to them please.

**Comment by bookerthegeek** [comment]
Just curious though, reading through the code is the following correct?
- Holding;
  - Comes in levels I - IV
  - Goes onto things that have an internal storage
  - No idea on what it does. Any help here?
- Multishot:
  - Comes in Levels I - IV
  - Only allowed on bows
  - Shoots Multiple Arrows

Neither is allowed on books. Question though, can skeletons spawn in with bows with the Multishot on it?

**Comment by C0rn3j** [comment]
@KingLemming Sorry, I didn't realize this is not a general feature otherwise I'd have worded it better.

I found out this is added by WAWLA. The "No description found" message is only shown upon holding the SHIFT key, so I'd assume behavior on WAWLA's side is correct.

Would you consider adding the localization so mods that support showing it would do so? I'd very much prefer reading about the enchantment in-game rather than hunting it on the web.

@bookerthegeek I have a bow with multishot, so it's either a drop from skeletons (likely) or maybe I looted it from a chest.

**Comment by darkhax** [comment]
Hello @KingLemming , this is my mod adding this message. This message is intentional, as it helps find situations where enchantment descriptions are not supported. I currently have three mods (Enchantment descriptions, Wawla, and Enchanting Plus) which have enchantment description based features. 

I would really appreciate it if you could add support for my mods, and any potential future mods by adding some descriptions to your localization file. If you don't want to it's fine, however it means I have to manually add support for your enchantments in three separate places. 

Here are all the missing localizations.

```
enchantment.cofhcore.holding.desc
enchantment.cofhcore.insight.desc
enchantment.cofhcore.leech.desc
enchantment.cofhcore.multishot.desc
enchantment.cofhcore.smelting.desc
enchantment.cofhcore.vorpal.desc
```

**Comment by KingLemming** [comment]
I'm well aware that the message is intentional. ;) It's just sort of passive-aggressive and sends people off to report issues where there really aren't any.

I'll add the descriptions, but I can't say I approve of your tooltip warning.
