### ISSUE TITLE
Fluid transposer I/O

### ISSUE THREAD

**Issue by DemonfangArun** [CoFH/Feedback#635]
I have found that the fluid transposer cannot pull water in the same side it pushes items out, but the glacial precipitator can.

TD: 1.10.2-2.0.10.16
TE: 1.10.2-5.1.9.23
TF: 1.10.2-2.1.5.12

FTB Beyond v1.11.0

----

On a related note, Aqueous accumulators need to be updated to accept augments and get a new texture.

**Comment by covers1624** [comment]
1.10 isn't supported anymore, try with 1.12. Also there are absolutely no plans for devices to have augments, not sure what you mean..

**Comment by DemonfangArun** [comment]
Unfortunately the pack I am on doesn't have a 1.12 version, else I would try that. While I see a couple of packs on 1.12 in the ftb launcher, most updated ones are 1.10, so I wouldn't call it unsupported. I also note that you're not part of CoFH, so I'll wait for their judgement.

As for the augments, I am referring to the fact that the Aqueous accumulator is dog slow, so I have to "augment" it with a tank as a buffer.

**Comment by covers1624** [comment]
Actually i am apart of CoFH, that's why im listed on the CF pages and why i have the member tag here and yes 1.10 is NOT supported anymore, Please try and reproduce the bug in 1.12 there have been changes a bug fixes since 1.10 that may effect this. The accumulator will increase in the amount of water generated by 1 bucket for each extera water source over the needed 2, There is a possibility of adding a config for the speed of generation but that would be up to lemming.

**Comment by Tahakk** [comment]
@DemonfangArun 
1. next time try to be more polite

2. covers not having "contributor" or another badge doesn't mean that he is not part of CoFH. I fact he is one of the devs that did huge work on many projects and doing huge work even now.

3. as for the **Aqueous Accumulator** being slow, just build more of those or use some kind of buffer. And why it does not have augment? Because it is not that kind of machine. There are two kinds in pack, although I don't remember the exact names for those groups.

**Comment by DemonfangArun** [comment]
My apologies then, I rarely use github, I was just going off of what I could make out from your profile. I'll just have to deal with the issue, as I don't play any 1.12 packs as nobody I play with is interested in them.

----
To tahakk:

1-I don't use github for much of anything, so I am unfamiliar with how all of the systems work, please keep this in mind before attacking me.

2- see 1

**Comment by covers1624** [comment]
I'm going to leave this open until its confirmed not a bug on 1.12, it may very well be an issue.

**Comment by KingLemming** [comment]
It's handled in 1.12. As mentioned, you should update.
