### ISSUE TITLE
Crash on opening the forge lexicon

### ISSUE THREAD

**Issue by BrokenHearted2** [CoFH/Feedback#640]
Using thermal foundation 1.2.0B1.95, when opening the new forge lexicon I get this crash http://pastebin.com/Qzmm5WTq  not sure what is causing it. Any help would be greatly appreciated.

**Comment by KingLemming** [comment]
Bleh...wish I had an answer for you on this one. :(

Can you make it happen with *only* CoFHCore and Thermal Foundation?

**Comment by Kalbuck** [comment]
I have this same crash. Or at least, the same thing happens when opening the Forge Lexicon with the latest versions of CoFHCore, TD, TE, and TF.  I hope it's alright that I add to this issue rather than making my own. http://pastebin.com/TPN0Cam5 There's my crashlog. I also had a ticking memory connection occur (after updating the COFH mods) while viewing my Buildcraft Additions Refinery GUI, which seems odd.

**Comment by KingLemming** [comment]
There's nothing in the stacktrace at all that points to us, unfortunately. That's entirely vanilla code. It's also not something we see at all.

At this point, I think it's pretty likely that it's another mod having a bad interaction. The upgrade of our stuff is largely coincidental I'd think.

**Comment by KingLemming** [comment]
This doesn't seem to be us. Sorry I can't be more helpful. :/
