### ISSUE TITLE
Arboreal Extractors non-functional underground.

### ISSUE THREAD

**Issue by burt666** [CoFH/Feedback#642]
Arboreal Extractors are not extracting from spruce trees grown underground (7l x 7w x 8h area clear. Mob spawn proof through lighting). Grown on grass/dirt, extractor is adjacent with the rear side connecting, tree grows just fine, but the arboreal extractor does not turn on, nor does it extract resin.

**Comment by KingLemming** [comment]
They work, sorry. Just tested.

Either you're attempting to be clever and stack them (that won't work) or you have a non-natural tree.

**Comment by burt666** [comment]
They are naturally grown trees, but are not activating the arboreal
extractor. I've torn the trees down and regrown them, but they do not turn
on underground. They function above ground, but do not work underground. Is
there possibly something I am missing?

**Comment by burt666** [comment]
Nevermind. I found a solution. Exposing the tree to sunlight turns the arboreal extractor on. Seems that either I'm doing something wrong, or they cannot be underground.

**Comment by KingLemming** [comment]
Nope, that isn't anywhere in the conditions.

**Comment by lordgrimm** [comment]
Documenting that I have the same problem: my only arboreal extractor would not activate for naturally-grown trees in an underground hidden base in Survival. Nothing on the surface but grass.

Observed that in [this thread](https://www.reddit.com/r/feedthebeast/comments/60rwr2/breaking_the_new_arboreal_extractorsfor_science/), King Lemming had said something about dirt being a no-go. Based on that, I removed the natural dirt blocks 19-20 y up from the logs in question and replaced them with stone, after which, the extractor activated when placed. 
I was unable to replicate the problem in Creative. 

TE 1.12-5.3.6.20, Forge 14.23.1.2555, for what it's worth.

**Comment by ZeekDaGeek** [comment]
This does appear to be a valid issue with the way that you detect trunks. Here's what I have and it will not work:

![Not working](http://zeekdageek.tv/ss/rC73i.png)

Any time I remove the block above the tree truck it will detect the tree properly.

![Working](http://zeekdageek.tv/ss/0Omhm.png)
*3x3 hole cut in roof, though you only need a 1x1 hole directly above the log.*

The problem seems that it doesn't stop counting the tree trunk after lets say leaves and air it will continue looking up the trunk for quiet some distance:

![Broken again](http://zeekdageek.tv/ss/OrtkX.png)
*A single stone block a significant distance above the tree's trunk will cause it to stop functioning again.*

Problem area: https://github.com/CoFH/ThermalExpansion/blob/5340e2df6e328a1cc140a8b94692c8d09c5f06a7/src/main/java/cofh/thermalexpansion/block/device/TileTapper.java#L295

If you go more than 40 blocks up in the air you can have a roof on your green house though...

**Comment by KingLemming** [comment]
Funny enough, I was actually thinking about this the other day and thought this may have been the case.

However, it *should* only scan up to the Y of the leaves, so this may actually be a problem with getAllInBoxMutable.

**Comment by KingLemming** [comment]
Ah ha. Figured it out. :) Just so happened that my test cases were performed in such a way as to hide the issue.

**Comment by atxmatt2510** [comment]
![issue01](https://user-images.githubusercontent.com/34287030/48152673-80466600-e292-11e8-8c5b-d90f7b7547bf.png)
![issue02](https://user-images.githubusercontent.com/34287030/48152674-80466600-e292-11e8-840b-8557a54b2dda.png)

Also having this issue.
