### ISSUE TITLE
[1.12.2] Thermal Expansion Induction Smelter does not consume all ingredients.

### ISSUE THREAD

**Issue by AcidKat** [CoFH/Feedback#669]
When smelting Bronze in the Induction Smelter only 1 Tin and 1 Copper are consumed to create 4 bronze.

**Note**: Only seems to occur when the 3 Copper are placed in the "Metallurgical Flux" (left) slot and the Tin is placed in the right hand slot.

Tested using a fresh installation with same results.
MC Version: **1.12.2**
Forge: **14.23.1.2556**
Thermal Foundation: **2.3.7.18**
Thermal Expansion: **5.3.7.25**
Thermal Dynamics: **2.3.7.14**
Thermal Cultivation: **0.1.2.8**
CoFH Core: **4.3.7.24**
CodeChicken Lib: **3.1.3.313**

**Comment by KingLemming** [comment]
New version up on CurseForge.

**Comment by angelnc1989** [comment]
@KingLemming I just experienced this bug again in the newest release 5.3.7.29.

**Comment by wesker1213** [comment]
@KingLemming I've too experience this in 5.3.7.29, but it might be worth noting that this only happens if the slots are swapped. For example when I put lead in the left slot and obsidian in the right, it takes 1 lead & 4 obsidian as intended, but if you swap them, its 4 lead and 1 obsidian.

Same holds true for other recipes such as bronze, etc.

**Comment by AcidKat** [comment]
Yeah, same issue persists for me too.

**Comment by KingLemming** [comment]
Yeah, .29 apparently had a reversion due to something on the remote end. I locally built a .30 and uploaded it. It's fixed.
