### ISSUE TITLE
Revisit This Removed Feature Please

### ISSUE THREAD

**Issue by Boolyman** [CoFH/Feedback#694]
With EnderIO not coming to 1.12.2 we have lost Dimensional Transceivers.  They were the only close-enough alternative to Tesseracts from the previous TE days.  Is there any way you can consider adding these back into the COFH arsenal?  I realize there are a lot of options for wireless RF transfer... but it is a challenge to beat the convenience of a Tesseract for Item and Fluid functionality.

**Comment by AnZaNaMa** [comment]
Yes the tesseract was nice and all, but honestly not having magic blocks like these makes the game more interesting. You can use ender chests and ender tanks to transport fluids and like you said there are plenty of ways to transfer RF wirelessly as well. I do appreciate the convenience of the block and always enjoyed having it. I believe the statement on the tesseract was that it just didn't fit into the theme of Thermal Expansion. Correct me if I'm wrong, but I think KingLemming or someone else mentioned they might reimplement it in a different mod. With that said, he also posted recently about a mod that adds some miscellaneous things into the game and was looking for a name for it on twitter and reddit. It just might be in there :)

**Comment by KingLemming** [comment]
Honestly at this point, I'm probably going to do Legacy Tesseracts as a stand-alone mod. There's enough demand for them.

I don't like how Tesseracts were because they trivialized too many things. So I don't want them as part of TE. A standalone will bring them back as they were, and only depend directly on CoFHCore. So that's likely to happen, I just don't have an ETA. Doubt it'll be this year.

**Comment by Xiaminou** [comment]
I'd love to see a mod for a multiblock that can transfer energy or fluid or items across dimensions, similar to what applied energistics has with the quantum bridge.

**Comment by Gorden211** [comment]
As a transport everything anywhere instantly block it's ultimately a very boring thing.
However having tesseracts e.g. for expert mode packs as a very endgame block it is a nice thing to have, since after having automated lots of things and having dealt with a multitude of logistics, tesseracts are a nice rewarding thing to get.
They do trivialize a lot of things, that's why they should be extremely expensive to get.

**Comment by OracleofWuffing** [comment]
@Boolyman Since you were hoping for a different mod before anyways, consider [Mekanism's Quantum Entangloporter](http://wiki.aidancbrady.com/wiki/Quantum_Entangloporter).  It's available for 1.12.2 right now if you're impatient.

**Comment by EmosewaGamer** [comment]
Actualy, EnderIO is coming to 1.12.2...

**Comment by KingLemming** [comment]
Closing this down, unsure if I'll add or not. No ETA if I decide to.

**Comment by Paul17041993** [comment]
Having the tesseracts require power, or a little liquid ender, either per-tesseract or injected into the channel itself is an idea for balance, but when you then consider enderchests and endertanks they end up making the tesseracts redundant again...

Could just make it a config option tbh.

**Comment by Quest79** [comment]
Would really like this added back, @KingLemming. If anything just have it off in configs by default. Why not let the player/pack developers decide what trivializes things? Who knows what limits we might place on getting it. Removing it fully only limits options and we absolutely loved this blocks utility even if relegated to late game where you have to earn it.  Please reconsider. Thank you for the mods!

**Comment by 34486** [comment]
I really hope it is a seperate mod or in the configs!
