### ISSUE TITLE
Suggestion: Ingot, Block Type Prioritization Functionality With Lexicon? 

### ISSUE THREAD

**Issue by RoloEdits** [CoFH/Feedback#696]
If it's even possible could you make it where the ingots and blocks and dust get prioritized to the ones you specified in the lexicon.For example i have a TF copper block but when I craft it to get the ingots I get lets say Industrial Crafts ingots but I want Them to be TF's automatically instead of having to do an extra step to get them to be like how i want them?

And if this is possible would it work with Storage Draws compacting drawers?

**Comment by KingLemming** [comment]
Can't be done, sorry.

The Lexicon acts on pickup on a per-player level. Unfortunately, there's no possible way to enforce that with crafting/autocrafting since it would require changes to the recipe handler. And there's absolutely no way we can interfere with other mods and how they handle oreDict things.

We'll have an automated block version of the Lexicon, though it won't be quite as powerful - there will only be a certain amount of possible conversions available on a given block.

**Comment by RoloEdits** [comment]
OK, thanks for a quick response as always, it's very appreciated.
