### ISSUE TITLE
[Thermal Foundation] Missing ore gen [1.10.2]

### ISSUE THREAD

**Issue by Skillotic0703** [CoFH/Feedback#71]
I don't know if this is intended but some ores aren't generating by default. I looked into the config and didn't find generation for aluminum, platinum, iridium etc... I think they are here to be placeholders but i'm playing with tinkers' construct and in 1.10.2 it doesn't include aluminum by itself so this is a bit annoying.
I know i can add this by myself but I really like how the CoFH team manages balance in the game and I don't know if I'm going to choose the good settings.
Thank you in advance.

**Comment by KingLemming** [comment]
Sorry, but this is intentional. We added those ores at the request of pack makers who make their own ore gen configs, but we don't have any plans on using Aluminum or Iridium, and our current balance for Platinum is that it's produced as a byproduct of Nickel.

If you want to add Aluminum to your own game, it's pretty simple - you can just make a new json file (copy the format from the ores file and run your final version through jsonlint.com to make sure it's valid.

Offhand I don't know how much aluminum is really used, but a good starting point would be to copy the tin setting and maybe cut the cluster-count in half, just to be safe.

Glad you have such faith in us though. :)

**Comment by Skillotic0703** [comment]
Thank you!
