### ISSUE TITLE
Boiler conversion makes Ignition plugs obsolete

### ISSUE THREAD

**Issue by EnderiumSmith** [CoFH/Feedback#713]
In a compression dynamo boiler conversion results in an efficiency of 1.7x while ignition plugs in only 1.5x. Since the boiler conversion is a lot cheaper and available pre-nether i see no reason to use ignition plugs.
I propose reverting the status of refined fuel back to gasoline with 1500KRF/B and making the ignition plugs a 2x bonus.
And btw according to this quote from reddit(by King Lemming) refined fuel used to be gasoline and used the 1500K gasoline standard: 

> ...So if we say 1500000 for gasoline (TE's Refined Fuel), that's about...
0.36 RF / mB for uncompressed hydrogen.

**Comment by KingLemming** [comment]
Dude, get over the gasoline thing. It's getting tiresome.

I may boost the plugs to 2x though, we'll see.

**Comment by EnderiumSmith** [comment]
2000 KRF*1.5=3000 KRF
2000 KRF*1.7=3400 KRF
1500 KRF*2.0=3000 KRF
1500 KRF*1.7=2550 KRF
If you downgrade it the output energy with ignition plugs remains the same while the output energy with boiler conversion output decreases.

**Comment by KingLemming** [comment]
2000 KRFx2.0=4000 KRF
2000 KRFx1.7=3400 KRF
1500 KRFx2.0=3000 KRF
1500 KRFx1.7=2550 KRF

Fixed your math. The change in fuel value has *nothing* to do with it. It's the plug multiplier.

**Comment by KingLemming** [comment]
Also, after doing some testing, your initial assertion isn't even correct (which I thought to be the case, but have confirmed empirically). The multiplier for the Boiler augment is effectively 1.4x, because the 30% fuel penalty happens *before* the steam doubling.

With resonant dynamos augmented for efficiency, yes this will creep up past the fuel value at a ratio of 2.3x to 1.95. I'll likely adjust things to make the final result more competitive, but given that the 2.3x requires multiple dynamos (in a non-trivial ratio actually, lest you waste steam), as well Reinforced or higher tiers (Reinforced will get you to 1.7x vs 1.65x), it's a considerably larger investment.

So, yeah I'll adjust some things. No, I won't be changing the base value of fuel.
