### ISSUE TITLE
Servo-Bug

### ISSUE THREAD

**Issue by ReneMuetti** [CoFH/Feedback#733]
I have the following structure:
Ender Chest => Impulse Itemduct + Resonant Servo (ignoring Redstonesignal)
He did not pump the folgendne Vanilla items from the box:
- Podsol (0003/2)
- Plain Sandstone (0024/2)
- Chiseld Sandstone (0024/1)
You just stay leigen in the box.

**Comment by KingLemming** [comment]
Absolutely does not happen and there is no logical reason whatsoever that our code would have exceptions for these. Your system simply doesn't have anywhere for those items to go.

**Comment by ReneMuetti** [comment]
Although it is now just closed ...
How can I go to the "error" on the ground?
Can it give any one reason for this curious behavior?

**Comment by Tora-B** [comment]
There's likely nothing "curious" about it. A servo will not pull an item from an inventory if there's nowhere for it to go. There was either no space for those items on the duct network, whitelists/blacklists on all otherwise valid destinations, or the destinations were in unloaded chunks, and therefore not part of the visible network.

**Comment by ReneMuetti** [comment]
I have connected to the box with a pipe and a whitelist without filter (overflow box). There, all items are drawn which are not in the white list of the other pipe. It works - up to these 3 items ....
Hence my question - and asking for help in solving ...

**Comment by Tora-B** [comment]
There's a saying: a picture is worth a thousand words. I have connected up a pair of chests with impulse itemducts and a resonant servo, and it has no problem pulling those three items. A picture of your system would really help in understanding and diagnosing the problem.

**Comment by ReneMuetti** [comment]
Ok - if I'm at home, I make the corresponding images. I will "deliver" the settings of Itemfilter with :)
thanks

**Comment by ReneMuetti** [comment]
hello
I once made a bunch of photos ...

http://www.info-panel.net/mc/2015-07-28_18.32.04.png
http://www.info-panel.net/mc/2015-07-28_18.33.13.png
http://www.info-panel.net/mc/2015-07-28_18.33.30.png
http://www.info-panel.net/mc/2015-07-28_18.33.32.png
http://www.info-panel.net/mc/2015-07-28_18.33.33.png
http://www.info-panel.net/mc/2015-07-28_18.33.34.png
http://www.info-panel.net/mc/2015-07-28_18.33.36.png
http://www.info-panel.net/mc/2015-07-28_18.33.37.png
http://www.info-panel.net/mc/2015-07-28_18.33.38.png
http://www.info-panel.net/mc/2015-07-28_18.33.40.png
http://www.info-panel.net/mc/2015-07-28_18.33.41.png
http://www.info-panel.net/mc/2015-07-28_18.33.43.png
http://www.info-panel.net/mc/2015-07-28_18.33.45.png
http://www.info-panel.net/mc/2015-07-28_18.33.58.png
http://www.info-panel.net/mc/2015-07-28_18.33.59.png
http://www.info-panel.net/mc/2015-07-28_18.34.01.png
http://www.info-panel.net/mc/2015-07-28_18.36.17.png

**Comment by Tora-B** [comment]
Your first picture of the servo settings shows a whitelist that considers damage value. The rest show a blacklist that ignores damage value. Either one would cause the problem you're experiencing, given those items in the filter. Do you understand the meaning of the settings?

**Comment by ReneMuetti** [comment]
hello
If it is said, probably not.

**Comment by Tora-B** [comment]
The first button toggles Whitelist/Blacklist. On Whitelist, only those items in the filter window will be pulled/accepted. On blacklist, any items except those in the list will be pulled/accepted.

The second button toggles between "Use Metadata" and "Ignore Metadata". Use Metadata treats items with the same base block or item, but different damage values or metadata as different items. Ignore means treat them the same.

So Podzol (#0003/2) is the same block as Dirt (#0003/0), if you "Ignore Metadata". Chiseled Sandstone (#0024/1) and Smooth Sandstone (#0024/2) are the same as Sandstone (#0024/0) on the same setting.

So if you have a whitelist, that means only those items will be pulled from the ender chest. However, since you have it set to use metadata, it only pulls Sandstone and Dirt, but not Chiseled Sandstone, Smooth Sandstone, or Podzol. When you switched them both, so that it's a blacklist, and ignoring metadata, that means it won't pull any of those items.

If I'm guessing correctly what you want to do, you should change it to Whitelist, Ignore Metadata. Try that.

**Comment by ReneMuetti** [comment]
hello

Thanks for the explanation ...
That was the solution :)
Now it works ....

If it now be a way of "lists" are that Währe perfect :)
Then I could finally break down this "confused" BC-Pipes :)
