### ISSUE TITLE
[Request][Mod Interaction] Method/Interface/API Hook to blacklist certain items as Lexicon output

### ISSUE THREAD

**Issue by ReikaKalseki** [CoFH/Feedback#740]
Basically, two items sharing an OreDict tag may not be functionally equivalent. For example, special metals that are registered in the OreDict as more common names to allow their use there but are not supposed to be actually equivalent.

Also, some items, even though different, might be grouped together under the same tag for convenience. A particularly severe example is ChromatiCraft's crystals, which in addition to color-specific tags also share a general one, yet transmuting them is a very serious balance issue.

**Comment by KingLemming** [comment]
Just making sure, the crystals aren't ingot/block/ore/dust/nugget <something> right?

As long as they aren't, then the whitelist/blacklist option won't enable them by default, so it should be fine.

As far as allowing an API for explicit blacklisting or whitelisting, that gets tricky because I'm not sure if the mod should take precedence over the server admin or not.
