### ISSUE TITLE
Machines and ducts can insert invalid items into Dynamo fuel slots

### ISSUE THREAD

**Issue by Tora-B** [CoFH/Feedback#742]
Steam, Reactant, and Enervation dynamos will only accept certain items as fuel when the player manually attempts to place them in the fuel slot on the dynamo gui. However, they will accept any kind of item if a machine ejects it directly into the dynamo, or via an itemduct.

For example, if you put a pulverizer next to one of those three dynamos, it can output ore dust into the fuel slot. Or a chest with a servo can insert any item into a dynamo via an itemduct.

**Comment by KingLemming** [comment]
Not a super big deal, but an easy enough fix.

**Comment by Tora-B** [comment]
Thanks. It's something that's confusing to new users, and can bring generation to a halt if a non-fuel item gets stuck in a dynamo. I think I had that happen with a hopper once, wrenched a duct and it disappeared into a hopper, eventually clogging it up.

**Comment by Preladon** [comment]
Is this fixed for all items, or just the particular items that Tora-B mentioned? I've got a set of farms (MFR, not that it matters, I guess), that's output harvests into Thermal Dynamics ducts that pass by steam dynamos that I expect to only take the wood, but I often find it blocked up with pumpkin seeds.  It's worth noting, the ducts filter out saplings, so don't try to insert everything, but perhaps there's something quirky about pumpkin seeds?

(P.S. I know I can solve this with filters, but since I can't manually put pumpkin seeds in the dynamo it didn't seem correct)

**Comment by Tora-B** [comment]
Presumably it's been fixed for all items -- but if you'll notice, this issue only has the "fixed in dev" label, not "fixed", which means there isn't a publicly-available build with the changes in it.
