### ISSUE TITLE
Increase Energy Storage from int to long

### ISSUE THREAD

**Issue by AngellusMortis** [CoFH/Feedback#759]
Some mods (*cough EnderIO cough Draconic Evolution cough*) that use the RF API have storage blocks that exceed the INT_MAX of ~2.14 billion RF. The mods have cleverly found ways to work with this by setting max transfer rates of INT_MAX, but it makes `getEnergyStored` and `getMaxEnergyStored` inaccurate because they do not return their proper values. 

Example from Draconic Evolution:

[EnergyPylon](https://github.com/brandon3055/Draconic-Evolution/blob/96be94c7b41de043bde89460feedaac853d729d2/src/main/java/com/brandon3055/draconicevolution/common/tileentities/multiblocktiles/TileEnergyPylon.java#L285) (transfer block in DE)

[EnergyCore](https://github.com/brandon3055/Draconic-Evolution/blob/96be94c7b41de043bde89460feedaac853d729d2/src/main/java/com/brandon3055/draconicevolution/common/tileentities/multiblocktiles/TileEnergyStorageCore.java#L774) (the actually energy storage block)

The Energy Core does not implement the IEnergyStorage, but the Energy Pylon does and just caps the energy stored to INT_MAX. Other mods that read this data are not getting accurate data so it is hard to tell what is inside of these energy storage blocks programmically.

The best use case I found for this is in the Computer Craft add-on OpenPeripherals, which allows you to read block data from a block including the `getEnergyStored` and `getMaxEnergyStored` return values. An issue was created on their Github [here](https://github.com/OpenMods/OpenPeripheral/issues/191) even though it is not really something they can fix. 

Cannot tag this, but I would definitely consider it an enhancement since it is other mods that are kind of pushing past what the RF-API was designed for.

**Comment by KingLemming** [comment]
Sorry, this wouldn't be be an enhancement, but rather a disaster.

This would require rewriting the RF API on a fundamental level and fragmenting the community.

The issue here is that mods which are going beyond INT_MAX are just stupid. They shouldn't do it and there's no sense in it. You're correct that it's pushing past what RF was designed for.

On a computational level, int is cleaner and more optimized. I'm not going to kludge up the API to satisfy mods which should really be using another API *entirely*.

**Comment by AngellusMortis** [comment]
It would not reequire rewriting the RF API entirely. You could make extra interfaces that extends the previous ones like `ILargeEnergyStorage` that has extra methods that return longs. Then mods can implement those interfaces and they would be completely compatible with all the mods that do not use the long versions of the interfaces.

**Comment by XFactHD** [comment]
@AngellusMortis The developer of Draconic Evolution said that he will make a proper CC integration to be able to display accurate values. For EnderIO as far as I know Computronics provides a pretty good integration, better than what OpenPeripherals has to offer.

**Comment by AngellusMortis** [comment]
Exactly, Draconic Evolution returns a double for `getEnergyStored` because DOUBLE_MAX 1.7*10<sup>308</sup>. `getEnergyStored` and `getMaxEnergyStored` should have the ability to return a `double` for items that store more then INT_MAX. Mods should not have to make their own integrations and such just because the API does not allow for a higher storage amount. A second interface that extended the original and had extra methods to return a `double` would not break any compatibility and allow mods (like Draconic Evolution and OpenPeripherals) to give and display proper readings in a more unified way.

**Comment by KingLemming** [comment]
Double is an awful way of handling it, since the maximum stored value is not actually that high. You lose precision after a point, meaning energy gets rounded and clipped.

I agree that long is a better way to handle it, if there were to be a large energy standard. Here's the problem - if I were to add another interface to support this, mods might get the idea that it should be used. It shouldn't be. This ridiculous numerical inflation is a cancer on the modded Minecraft community.

Here's how it will go: You'll have a mod add massive power generation - MassGen, and maybe even a massive load for that generation - MassLoad. And then they'll say, "well this is balanced, you NEED that MassGen for my MassLoad."

And then you start to crunch the numbers and realize that the MassGen is about 50000% more efficient than everything else in the game, because otherwise you'd need to deforest (and charcoal) an entire continent every tick to make it work. So then it's a question of the actual balance impact, and all it will do is obsolete everything else.

And then everyone starts to say, "I have a MassLoad of extra power but nothing to spend it on." And that's because they have multiple MassGens but only a single MassLoad. And why? Because no matter WHAT the requirements for building a MassGen, they'll hit a point where they can have multiple. And the absurd efficiency, which will be required, means that it won't be hard to maintain a lot of them either.

So then, what is the balance point? Make the MassGen so ludicrous to operate that it tanks server TPS so people can't build multiple?

Or, let's all keep the numbers sane.

TL, DR: https://www.youtube.com/watch?v=tleSnj4OD0g

**Comment by bonii-xx** [comment]
Wait, did I read that correctly? Double for RF stored?

**Comment by AngellusMortis** [comment]
A `long` would be better. I only said `double` because that is what Draconic Evolution uses. 

The issue is that there are mods (and have been mods) for a while now that push that boundary. Breaking 2.14 billion RF is really easy with RFTools and Extra Utilities alone. A single Nether Star Generator makes 40KiRF/t and RFTools worlds can easily go well past  100KiRF/t or more for dimensions. I think setting a max extract/receive as an `int` and then energy stored/max energy stored to a long is a good idea. Mods would still not be able to ever exceed that 2.14 billion RF/t input/output but they would easily be able to hold beyond that amount.

**Comment by skyboy** [comment]
Existing interfaces are not changing method signatures. Floating points will not be used in extensions. Even having this discussion is rather asinine, generated by a pointless numbers game: it's at a point where nothing matters, you just have infinity storage for all you can produce.

**Comment by bonii-xx** [comment]
>The issue is that there are mods (and have been mods) for a while now that are pretty standard that push that boundary.
Exactly. The issue lies with the mods, not the API. ;o

**Comment by MrKickkiller** [comment]
@bonii-xx : 
I believe he suggests to change the api since multiple mods are pushing that boundary. 

A change in the api would solve all the Integer.MAX problems etc at once (if any).

I however totally agree with keeping it an int. Is there a reason to go so high with power storage/transfer other than bragging rights and to gain more players on a mod.

The 'problem' has probably started because mod A stored 2x what mod B stored in a single block, but then mod c comes along and doubles that AGAIN. So now DE is like x times 'better' tha

**Comment by rwtema** [comment]
So what you're saying is, I need to nerf the Nether star generator?

Can do.

**Comment by AngellusMortis** [comment]
> I however totally agree with keeping it an int.

The only reason I am suggesting it is because EnderIO and DE are both "official" mods in the FTB packs. While I do not disagree with the virtual power arms race it creates, I do think the benefits would of changing it to an long would be worth it since they are mods in pretty popular mod packs. 

> So what you're saying is, I need to nerf the Nether star generator?
I never said that :( I really like my Wither farm + Nether Star power generation set up.  Though, the higher tiers (x8 and x64) are busted because they generate way too much power.

**Comment by MrKickkiller** [comment]
@AngellusMortis 
This virtual power arms race is what's causing you to drop this issue here.
I do not recall having power storage issues in the times without TE, EIO or DE. 
An IC2 MFSU was plenty to keep a base running. A clever system of gates that allowed for efficient energy usage for my MJ's was enough to keep my quarry going!

The problem all began with the arms race. Mod A wants to out-perform Mod B to attract more players/popularity and so the thing begins.

**Comment by ljfa-ag** [comment]
Buildcraft used to use floating point numbers for MJ amounts too. Not sure if that caused any trouble but well, I guess having a cap of INT_MAX is good in the light of this issue.

**Comment by SoniEx2** [comment]
Workarounds: Negative integer indicates how many times you have to call it. It also causes crashes but that doesn't matter. Then you just rebuild the whole integer based on that.

**Comment by skyboy** [comment]
Using floats fundamentally prevented people from doing what they've done with RF - at a certain point you can no longer use decimals, then only affect values with a value of 2 or higher, and so on. Not as many bits to work with as int has, and no multi-transaction to throughput more.

**Comment by asiekierka** [comment]
@skyboy - that is because MJ originally didn't care about exact values. In fact, most of the tiny issues we keep finding is leftovers from those days.

I still wish it was true. Numbers are the cancer of modding.

**Comment by SoniEx2** [comment]
Well we can always do like Unicode and use the high bit to signal extra data?

```java
int x = getMaxEnergy();
if (x < 0) {
  for (; x < 0; x++) {
    pushBigIntData(x);
  }
}
```

Or something like that.

If Unicode can get away with it, why can't we? :smile:

**Comment by asiekierka** [comment]
@SoniEx2 - Because that's banned under the Anti-CPU Cruelty Act. Keep in mind a lot of mods do a lot of calculation on RF; BigInts are VERY slow.

**Comment by SoniEx2** [comment]
If "x" is -2 you can use longs instead of BigInts.

**Comment by asiekierka** [comment]
@SoniEx2 - more terrible workarounds. Design is not about duct tape.

**Comment by SoniEx2** [comment]
Workarounds are only needed for bad design.

**Comment by asiekierka** [comment]
@SoniEx2 - you're implying that current RF is bad design. No. It's the mods which think TWO BILLION REDSTONE FLUX is not enough. They are bad design.

**Comment by SoniEx2** [comment]
[Relevant](https://plus.google.com/115229808208707341778/posts/BUXfdWqu86Q)
