### ISSUE TITLE
Suggestion for Tome of Knowledge giving/taking a level evenly

### ISSUE THREAD

**Issue by Tmtravlr** [CoFH/Feedback#767]
Hey KingLemming,

I noticed the latest time we updated thermal foundation, the tome of knowledge now gives/takes all levels. I hear it's because of an exploit with partial levels, but I really miss the ability to get just one level out of it!

I remember from playing earlier with openblocks tanks, when you get xp it gives you enough to get to the next level evenly (not leaving any partial levels). The tome of knowledge could do the same, giving and taking xp so you are one level up/down with no leftovers. That would solve any exploits and still allow players to retrieve only one level.

Hope the suggestion is useful!

**Comment by KingLemming** [comment]
The reason the tome works as it does right now is because when I tried doing this, bugs in vanilla code prevented it - basically the way vanilla calculates levels, the correct amount of xp would come out, but not always guarantee a level up.

The tome will get a rework and a GUI, but there's no ETA.
