### ISSUE TITLE
[suggestion] allow toggle satchel to *NOT* deposit item when clicking on inventory

### ISSUE THREAD

**Issue by SevenMass** [CoFH/Feedback#774]
The feature to deposit satchel content when clicking on an inventory is very nice, but it has two problems:

1: Other mods (forestry) do this by shift-clicking on an inventory, maybe would be a good idea if TE  follows this convention. 

2: I've always used satchels as a tool-bag, so a well organized satchel with tools sits on my toolbar all the time. Annoyingly, I end up emptying it when I try to open a chest or a crafting station.
It would be nice if I could toggle this feature of for my tool-bag.

And while I'm talking about it; An option to move inventory content to the satchel would also be a nice addition too.

(updated the phrasing)

**Comment by KingLemming** [comment]
This is coming across as a little bit sassy. I don't know if that's your intention, but it kind of makes me want to close the issue out of hand without further consideration.

Just saying.

**Comment by SevenMass** [comment]
It is not my intention to anger anyone. Least of all the mod author(s) I'm trying to convince to change something.

My intent was to come across as friendly, and a little bit funny. What I typed sounded good in my head. I was trying to make a good first impression.

I'll change my words a bit, I hope that fixes it.

**Comment by KingLemming** [comment]
So, here's the problem with your points. Forestry alone does not constitute a standard. They also don't have configurable filtering on sneak-click, so that's already sort of a non-comparable.

And as you may have surmised, sneak-click already has an action. So giving it a double purpose introduces control inconsistency. So if I were to change it, I'd get probably 3x the reports from other people who prefer it as it is now.

I'm not really sure how to address this or if I should at all, frankly. I'm thinking about it.

**Comment by SevenMass** [comment]
With the newly added reservoir, pressing a key toggles between fill mode and empty mode.
Maybe similar behavior could be added to the satchel, but make the key-press toggle between 3 modes: fill, empty and do nothing.

Either way, I thank you for your attention. 

And I'm sorry for what happened earlier, I usually spend minutes mulling over every sentence I type, and then I still end up derping completely.

**Comment by KingLemming** [comment]
The V key already toggles auto-pickup - it has a use.

**Comment by Tora-B** [comment]
Is this likely something that a player would want to configure frequently? At least from the use case that's been presented, I think it's something a player would generally only set once per satchel, rather than need to toggle between frequently. Either you're using a satchel to keep valuable, rarely used, or special items safe or in a single slot when doing other tasks, which you probably don't want to dump in an inventory accidentally, or you're using it as extended inventory for the sort of things you'd want it to auto-pickup, and consequently want to dump out. I think a toggle on the filter GUI would be sufficient.

**Comment by KingLemming** [comment]
That's kind of what I'm thinking, tbh.

**Comment by KingLemming** [comment]
I've rewritten it a bit to change it to sneak-click. Shouldn't be too confusing.

I don't want to overcomplicate them though, so no plans to allow for mode toggles in GUI or transfer direction.
