### ISSUE TITLE
Bug: Tome of Knowledge gives back levels taken by other sources

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#785]
I don't know how to properly put this into words, so I'll try my best to describe it. In my modpack i used the tome a lot, usually for storing xp and whatnot. Usually i would wonder why my tome has more xp than usual, but i just wrote it off as me being silly.

Recently however i found that this was a probably unheard of bug. 

To duplicate, quite easy.

1.Have a tome of knowledge, either empty or not, difference is none.
2. Check your current level(s). If its greater than 1, continue.
3. Use your level(s) on something. Enchanting, renaming, anything.
4. Drain remaining xp into your book. 
5. Shift right click book for your lost level(s) back.

video demonstration:
https://youtu.be/ho4rOhhg10A

**Comment by KingLemming** [comment]
That's not actually what's happening here....it seems other sources don't actually correctly drain xp in the first place.

**Comment by Akitori** [comment]
what? is there a way to fix it then?

**Comment by KingLemming** [comment]
Probably. But I'm just establishing what the *actual* problem is.

**Comment by loudwhitenoise** [comment]
Since I had this issue the other day and wrote it off as 'I probably did something wrong', I'm putting my updated commentary on this issue rather than reopening my old one, since they are basically the same.

Demonstration using enchantment table and anvil: https://youtu.be/EZg09N8PQFA
Demonstration using another mod: https://youtu.be/5L34NMgFJiI  (this threw me off for a bit, I initially thought it was on their end!)

The videos are a bit potato, sorry, I'm still not good at this whole thing. In hindsight, I should have set the UI scale to large.

Forge v14.23.1.2582, MC 1.12.2

**Comment by KingLemming** [comment]
Mitigation for this actually involved fixing the underlying vanilla issue. No ETA.
