### ISSUE TITLE
Thermal Expansion Version 4.0.0B8-23

### ISSUE THREAD

**Issue by Tristan324** [CoFH/Feedback#80]
For the mods you can go to http://tbdmindcrack.info/index.php?threads/tenno-pack-and-server.2441/. 
The issue I am having is with dynamos. Every single dynamo will not output power to TE machines, any kind of pipes(ender conduits(EnderIO) or Basic Universal Cable(Mekanism). I was wondering if there is a mod confliction or if this indeed a bug. Thanks Tristan

**Comment by KingLemming** [comment]
It is almost certainly a mod issue. Please update all of your mods to the latest versions.

**Comment by Tristan324** [comment]
The only mod out of date is OpenCOmputers and Buildcraft.

**Comment by Tristan324** [comment]
Could it be a config issue? With Thermal Expansion? Because even if the dynamo is next to the Pulverizer it doesnt output power

**Comment by KingLemming** [comment]
I'll need screenshots, because we can't replicate this at all.

Are your mods from http://teamcofh.com/downloads?

**Comment by Tristan324** [comment]
Well i got the mod from the FTB Private pack "Tenno" and as of that everything is up to date

**Comment by Tristan324** [comment]
What do you need screenshots of im not getting any exceptions or errors. Its just smply not transmitting power

**Comment by KingLemming** [comment]
We need screenshots of your actual setup, because:

Dynamos work. Machines work. We know this.

This is specific to either your pack (very possible, if they are using "CurseForge" and not "Curse" versions), or it's just a derp on your end with a stray redstone signal, or lack of fuel or anything.

Not trying to be mean, but if this were an actual code issue on our end, the tracker would be inundated with this bug and we'd have had a fix out long ago.

My guess is that your pack has derped somewhere, hard, and there's an API conflict or they're mis-matching versions or any number of things, but I'm not ruling out you derping either. Point is, I'd like to help you figure it out, but I can tell you with 100% certainty that nothing in our code is incorrect in this regard.

**Comment by Tristan324** [comment]
Oh I have no doubt its not code, Its just im not sure what would be making it throw an exception and without that information i cant fix it. I can give you a list of mods if thats what you need

**Comment by Tristan324** [comment]
Its definitely a mod confliction... Its not working in single player either in a new world in creative. So i think its a pack error... How would i go about fixing this

**Comment by Tristan324** [comment]
I dont mean to sound ignorant or stupid and i hope im not wasting your time

**Comment by KingLemming** [comment]
Join our IRC channel and ask around there. :) Somebody more knowledgeable than I might be around, with regards to the modpack.

**Comment by Tristan324** [comment]
Thanks sorry for wasting your time
