### ISSUE TITLE
[Thermal Innovation] Crash breaking blocks with drill

### ISSUE THREAD

**Issue by temp1011** [CoFH/Feedback#808]
I crashed when breaking a grass block with the TI creative drill in AOE mode in survival mode.
Log: [crash-2018-01-04_00.30.42-client.txt](https://github.com/CoFH/Feedback/files/1602124/crash-2018-01-04_00.30.42-client.txt)
Versions:
- forge 14.23.1.2582
- thermal innovation 0.1.0.1

I know Thermal Innovation is not in release yet and so support is unavailable etc. I am only submitting this to try and help develop the mod - I fully expect crashes from semi-public betas. I hope this helps and I'm sorry if this is due to using outdated versions.

EDIT: Just tested resonant drill and it works fine although the drill sound didn't play while drilling but does now semi-constantly but that's a minor bug. Testing creative drill again to see if this some one off mods not synced thing.

EDIT2: In AOE mode creative drill only breaks one block at the speed of a bare hand. Didn't crash this time though so that might be a one off. There was some sound lag but not as bad.

EDIT3: The creative drill will break blocks that a hand can't (eg-sandstone,stone). I'm going to set up a new reduced mod instance and report back becuase this could just be some weird mod compatibility that's not COFH's fault. Again, sorry if these are annoying issues about a mod that's in dev.

**Comment by KingLemming** [comment]
This kind of stuff is why I didn't want it built. I don't want issue reports on something that isn't done. And in this case the version number doesn't mean anything because it's placeholder. It is *not* a "semi-public" beta.

I appreciate your intentions, but this just isn't really a helpful thing. The error itself makes no sense and I can't make it happen in dev, so it's almost definitely due to something with the build process and refactors which have occurred.

**Comment by temp1011** [comment]
OK, sorry to bother you.

**Comment by KingLemming** [comment]
Again, thank you, but if I start getting reports on code which is clearly in progress, then the most logical thing for me to do is tear down that repo entirely and develop locally in secret.
