### ISSUE TITLE
[Suggestion] Firework recipe with saltpeter.

### ISSUE THREAD

**Issue by Mymy1** [CoFH/Feedback#814]
In the real world, saltpeter was used to make fireworks.

Personally, I think it'd be really cool to be able to do that in MC... Just a tiny suggestion, not to be taken very seriously, simply a thought I came up with.

**Comment by KingLemming** [comment]
From what I can tell, it's used in fireworks because it's used to make gunpowder. And it already does that, so I think that's accurate. I can't find any mention of it used outside of that. :)

Also, the firework recipes are a nightmare and not something I can actually touch - there's no support for it anywhere in the code and Forge hasn't provided any inroads. Even with the move to Ingredients in 1.12, Fireworks are their own little special class of nonsense.

**Comment by Mymy1** [comment]
Ah; understood. For the record, the Chinese used saltpeter in their fireworks before they knew how to make gunpowder. Guess I won't be making a firework factory easily any time soon, haha!

**Comment by laz2727** [comment]
That's because black gunpowder is like 75% saltpeter. But pure saltpeter
doesn't start burning as easily and isn't as powerful.
