### ISSUE TITLE
RSA Crash on launch

### ISSUE THREAD

**Issue by qazwiz** [CoFH/Feedback#835]
the error message is 

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail The game crashed whilst there was a severe problem during mod loading that has caused the game to fail Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: cofh/redstonearsenal/item/tool/ItemWrenchRF

i havent been able to load ANY mods EVER. use to think it was because i only had 4Gig memory but got 8Gig and still no go.

**Comment by covers1624** [comment]
Provide your full log or we cannot help you, posting a blurb is the number one way to get your issue insta closed.

**Comment by qazwiz** [comment]
ok, im here but need to know where log is

**Comment by qazwiz** [comment]
still here

**Comment by covers1624** [comment]
First, This isn't a messaging service, Treat this as a forum.  
Second im going to close this as user error, our mods work and it is likely due to your mods not having the required dependencies, Please join the [Discord chat](https://discord.gg/uRKrnbH) for general support.

**Comment by qazwiz** [comment]
that is the message from copy to clipboard, the View crash report does nothing when i click it.

![graphic_1_10_2018 1_04_38 pm](https://user-images.githubusercontent.com/35308628/34790519-a7f50472-f607-11e7-9bfa-2b96021ed683.jpg)

**Comment by qazwiz** [comment]
and discord will not allow me to access ever since i got new computer

**Comment by qazwiz** [comment]
So? 13 minutes after a request for help some A-Hole prevents anyone else from responding? BECAUSE I WAS ACTUALLY THERE AS HE TRIED TO BUMP HIS ACCESS STATS?

If anyone else sees this please ask that that A-Hole be de-opted.  no help until someone else shows up is better than blocking all  others from being allowed to see when a "gotta up my stats" troll isn't helping....  you want the crash report, i get that BUT THE CLICK LINK DIDN'T WORK.

plus   YOUR DISCORD ISN'T AVAILABLE TO EVERYONE
only to people with two-factor access.... my 2-factor app wasn't allowed on this new micro$hit machine

**Comment by covers1624** [comment]
So my first point was THIS IS NOT INSTANT MESSAGING, this is a forum type deal meaning we DO NOT reply instantly as again its not instant, Exploding here when this isn't Instant Messaging is rude and childish, post your issue and wait for a reply. This is a warning, further slander of me will result in a ban from this repository. Losing access to your discord due and being unable to create a new one and come on are 2 completely different things. Our discord only requires that you have a verified email on your account in order to join.  
I have absolutely no idea what you mean by `Bump his access stats` and `prevents anyone from replying` the issue hasn't been locked only marked as closed. People can still reply as evident by you replying. Please at least take the time to learn the platform you are using before going out of your way to be a absolute asshole when you have no idea how the platform operates.  
Now on to your actual issue, I see from your tiny blurb of no information on mod versions, minecraft version or forge version, you are running on minecraft 1.7 as there is a reference to `cpw.mods.fml`.  
Our general rule about 1.7 now days is its ancient and there is no support, but for this one instance ill make a slight exception to that rule. Finding your crash reports is dependant on what launcher you are using, Using twitch you have the option to view the profile's folder and just using only the native launcher it will be in your `.minecraft` folder. Since you provided no information in your initial report on what launcher you are using ill assume twitch, Simply Right Click your modpack and select `Open Folder` you should see a `logs` folder and inside that a `fml-client-latest.log` file. Post that via a service such as https://pastebin.com/ and i will be able to provide some help.

**Comment by brandon3055** [comment]
@qazwiz I suggest in future you show a little more respect. Mod devs do not exist to serve you and walk you through every issue step by step. Something as simple as how to find a crash report can be easily found via google. We should not have to walk you through the process.

**Comment by qazwiz** [comment]
https://pastebin.com/embed_js/aRHEEpPU is the link... looks correct. thank you for your offer to help. covers.

@Brandon, actually i know how to find logs but it was three months old so not the log of the crash just three minutes earlier,....  so giving a little extra, with a bit of thinking like covers did when he saw how upset i was is a good idea. I WOULD NEVER HAVE FOUND TWITCH FOLDER without the suggestion he figured i needed. (he might be INFJ just like me, one of the smartest 1% of personality types) 
THIS DAMN COMPUTER HAS ALMOST 2 MILLION FILES ON IT ugh, i never thought that the twits at twitch would put their stuff oh well, i digress so i'll just send
 (but Covers, if you not sure your Meyers-Briggs type might be worth your time to google for a self test)

**Comment by KingLemming** [comment]
Top 1% huh? And you buy into Meyers-Briggs?

Here's what the log shows - you have a *ton* of issues, and RSA isn't the only one. At the end of the day, you have a bunch of API problems and you need to get them sorted. But as one of the smartest people on the planet, you knew that already, didn't you?

It's not the fault of our mods, but simply how Forge deals / doesn't deal with APIs properly in 1.7.10.

Time to move up to 1.12.2.

**Comment by qazwiz** [comment]
kk, any suggestions for a skyblock mod that fits the bill... atm, my setup for mods seems to be just whats available through the twits at twitch but would be willing to try hand install anything that isn't screaming "I'm a horsie, pull me in"  LOL

**Comment by covers1624** [comment]
Your continuation of being ignorant, uncoperative and rude is not welcome here, i warned you once, this thread is now locked.
