### ISSUE TITLE
Thermal Dynamics

### ISSUE THREAD

**Issue by Kagien** [CoFH/Feedback#84]
Simple question, sorry if it has already been answered.

Is a new version of Thermal Dynamics being worked on? If so, is there any kind of time frame? I was hoping to do some work on 1.10.2 and all of the CoFH mods are updated except for Dynamics.

**Comment by bookerthegeek** [comment]
Yes, but now it will be another week before they release it because you asked.

**Comment by covers1624** [comment]
Dynamics Is getting almost a complete rewrite, due to work obligations with lemming and how complex the code base is, it may take longer than we anticipated. Rest assured we are working on it.

**Comment by transcondriver** [comment]
I always went on the premise that no mod will ever update or release until it shows up on CurseForge. I even remember at some point Team CoFH stated that they were not going to update at all. Look at it this way: They beat Buildcraft - which isn't hard considering the amount of bloat they've added. They beat Forestry to release for the same reason. And they beat Red Power 2. Let's cut them a little slack. They probably kept silent about it all so they could get Core, Expansion, and Foundation out in the first place. Next we'll be wanting to know when MFR is showing up because Forestry is such a train wreck.

**Comment by KingLemming** [comment]
Please do not misuse the issue tracker for things like this. This isn't an issue, it's a question. We have other avenues for those.
