### ISSUE TITLE
[1.12.2 Thermal Foundation 2.3.10.6 & Redstone Arsenal 2.3.10.4] wrench item interaction with top of Doors

### ISSUE THREAD

**Issue by VallenFrostweaver** [CoFH/Feedback#864]
Upon holding a crescent hammer, omni-wrench, or battle wrench in the main hand and opening a vanilla door by clicking on the top half of the door you cannot enter the open door (you stutter like being pushed back over and over but only like 1-2 pixels). Closing and reopening the door without the tool fixes. Clicking the bottom of the door allows passage/changing the door orientation as usual.

**Comment by KingLemming** [comment]
Hmm. That's interesting because we're deferring to Forge/vanilla on that functionality - the standard rotateBlock() method.

I'm going to see if it *should* be special cased or this is just something they should be fixing in Forge.

**Comment by KingLemming** [comment]
Looked into this a bit and ultimately it's a Forge bug. We can clean up some stuff in our BlockHelper, but as I mentioned, we're actually deferring the rotation call to the door, and the door itself doesn't have proper rotation code.

Sorry for the inconvenience, but this isn't really something we can special case because it won't carry over to modded doors and such. Forge needs to handle it. :/
