### ISSUE TITLE
Steam Dynamos and Mekanism

### ISSUE THREAD

**Issue by roboderpy** [CoFH/Feedback#882]
Yep.
Nobody replied to closed https://github.com/CoFH/Feedback/issues/847 so i reopen it here.

Without any mods with it's own Steam installed dynamos with steam work as intended in Singleplayer, but refuse to work in multiplayer.

In singleplayer if *external* steam liquid is registered, Dynamos in `Boiler` mode are producing right steam liquid (registered before), but Steam Dynamo in Turbine mode refuses to accept it even in singleplayer.

*it is used to work right with all external steam registered AND work in multiplayer, but i can't remember which one version is working right, because i upgraded a long time ago and was using faster and better generators, not dynamos*

Forge Build: 2599
Thermal Expansion: `ThermalExpansion-1.12.2-5.3.10.15-universal`
Lib: `CoFHCore-1.12.2-4.3.10.5-universal`

**Comment by KingLemming** [comment]
Can you make this happen with *only* CoFH mods?

**Comment by roboderpy** [comment]
It works very strange now, investigating

**Comment by roboderpy** [comment]
Anomaly: https://github.com/CoFH/Feedback/issues/847 isn't an issue anymore (NuclearCraft works with Thermal Expansion as intended)

There is a mod/library which messes with stuff, investigating further

**Comment by KingLemming** [comment]
Yes. Aware that it is not TE's fault. That's why there  was no response on the last issue.

I have code in place to remap the fluid properly and it's worked for a long time, so I'm quite sure it is a third party.

**Comment by roboderpy** [comment]
@KingLemming and @aidancbrady - have fun.

Mekanism's steam if conflicting with Thermal Expansion.

**Comment by roboderpy** [comment]
@thommy101 do you got any comment on this?

KingLemming, you can look at https://github.com/aidancbrady/Mekanism/blob/5d8b5c8f915b1f435e156ef3131a1b72d44e2e89/src/main/java/mekanism/common/MekanismFluids.java#L22

**Comment by roboderpy** [comment]
![hmm](https://i.dbot.serealia.ca/2018/01/7121d6553e_javaw_2018-01-25_20-05-42.png)
![supposted to be TE](https://i.dbot.serealia.ca/2018/01/7d3b3f4531_javaw_2018-01-25_20-06-32.png)
After some tests - i found that with ANY mod installed which add Steam fluid, bucket's content with steam is labeled as "Added by: Thermal Foundation" BUT with Mekanism installed bucket displays "Added by: Mekanism"

So it is either bad practice registering steam too early (Mod initialization) on Mekanism's side, or it is bad practice of fluid handling Thermal Expansion side.

**Comment by joselitosn** [comment]
I'm not related to the COFH Team, but since this bug might happen to me, I decided to try and replicate. Unfortunately I couldn't reproduce the bug using the following mods on a clean install (either single or multiplayer):

forge-1.12.2-14.23.1.2599-universal
CodeChickenLib-1.12.2-3.1.5.331-universal
CoFHCore-1.12.2-4.3.10.5-universal
CoFHWorld-1.12.2-1.1.1.12-universal
Mekanism-1.12.2-9.4.3.330
MekanismGenerators-1.12.2-9.4.3.330
RedstoneFlux-1.12-2.0.1.2-universal
ThermalDynamics-1.12.2-2.3.10.4-universal
ThermalExpansion-1.12.2-5.3.10.15-universal
ThermalFoundation-1.12.2-2.3.10.6-universal

Are you using a modpack? Also, how did you get a bucket of Steam? With these mods I didn't see a bucket registered.

**Comment by roboderpy** [comment]
![modlist](https://i.dbot.serealia.ca/2018/01/c3fa03a407_explorer_2018-01-26_08-12-22.png)

**Comment by KingLemming** [comment]
I'm afraid I can't replicate it either.

**Comment by joselitosn** [comment]
I still couldn't reproduce the bug only with the mods you listed, but I was able to reproduce it using the description of the original issue as described [here](https://github.com/turbodiesel4598/NuclearCraft/issues/216#issuecomment-357464010).

You said that the problem didn't occur on singleplayer, that leads me to believe it's because you created a new world and the problem only happens on a existing world which new mods containing the steam fluid (like NuclearCraft and Mekanism) were added later.

 I'm not sure of the side effects of not using Forge events to register fluids, but I think that's worth discussing. I had problems with mods which registered machine recipes outside the Item register event, because another mod replaced one of these items in such event. I suspect the same can happen for fluids.

**Comment by KingLemming** [comment]
Forge issue. I have a workaround, but man this is stupid.

**Comment by roboderpy** [comment]
You didn't saw modding of source games, you can say this phrase each hour there 😁

But what is the issue with forge?

**Comment by pmotaPT1971** [comment]
Perhaps this might help replicating the issue.
I have a world that was created in FTB Revelations (1.12, v1.30), SP. Then I stopped server, added openblocks (and ofc openmodslib) and mekanism (Mekanism-1.12.2-9.4.3.330 and MekanismGenerators-1.12.2-9.4.3.330).
With this in place I later found out I was having the reported issue. (Steam is generated but will not enter the steam dynamo). This would happen in SP , linux MP server, windows MP server.
However, if I generate a brand new world everything will work just fine (again SP and any MP environment).

I don't have the expertise to "remap" whatever is wrong with some ID in the "broken" world, just sending you the information in case you is useful in any way.
