### ISSUE TITLE
Thermal Expansion with Applied Energistics 2

### ISSUE THREAD

**Issue by DaysofKnight** [CoFH/Feedback#902]
Your Thermal Expansion machines register as "Nothing" within Applied Energistics 2's Interface Terminal Screen, EnderIO's machine actually say their name's within AE2's Interface Terminal. Can you fix this?

**Comment by KingLemming** [comment]
"Nothing" ? This sounds like it's on AE2's end.

**Comment by DaysofKnight** [comment]
Actually, I literally just found out the issue. It's that, AE2 doesn't know what it is because Thermal Expansion's machines were set to output into the AE2's interface. When you do that, AE2 instantly knows what they are. So, it's Thermal's issue. As, AE2 knowns what EnderIO's stuff is without having to force the machine to output into it

**Comment by covers1624** [comment]
Now you are comparing apples and oranges, TE and EnderIO work completely differently and its likely due to EIO not properly advertising that the side cannot be accessed or automatically allowing access to the side. While TE properly advertises that the side cannot be accessed untill you set it. So its working as intended.

**Comment by KingLemming** [comment]
That in no way makes it a TE issue. That means that AE2 does some strange/limited detection.

**Comment by DaysofKnight** [comment]
Point is, though. Even before you set it to output (To whatever side) AE2 knows what is what with EnderIO, but doesn't with TE. TE just shows up as "Nothing" within the interface terminal, whereas EnderIO shows the machine's name (Even when it's not set to directly output it into AE2's Interface). So... It *could* be something in EnderIO (Extra line of code or something, planning for AE2), or something missing from TE that *should* be added, for ease of life capabilities that EnderIO does instead (Don't get me wrong, I enjoy using TE (Now what I use 1.12.2 and EnderIO isn't updated to it) but it's just one of those nitpicky things, considering I found a work-around. Just something I'd like to see worked out within TE in the future)

**Comment by KingLemming** [comment]
I'd be fine with working it out, but declaring quite specifically that it is obviously a TE bug/issue is just incorrect.

I'll poke the AE2 team and see what's going on over on there end. Maybe there is an API or maybe I can tell them what they should be looking for instead of making certain assumptions that they are currently making.

But it's absolutely not clear that any solution will be resolved in this codebase nor is the onus on us to necessarily make that happen. Best I can do is investigate why.
