### ISSUE TITLE
Pixelmon Crash

### ISSUE THREAD

**Issue by Yanniclord** [CoFH/Feedback#908]
Hey guys, i have a little 1.7.10 bug, wich apparently has been reported multiple times, but none of the sides want to admit the failure. Pixelmon blames Cofh, and Cofh blames Pixelmon. 

Issue: http://pastebin.com/iJVdPkk3

Now, since people accept the "failure" of the other side instead of trying to work it out, this is the comment i have from the Pixelmon bug tracker:
http://pixelmonmod.com/tracker.php?p=2&t=6152
and
http://pixelmonmod.com/tracker.php?p=2&t=5882

One says "Good luck dude.. We've reported it several times. They pretty much dumped 1.7.10 like a red haired stepchild. They said it was fixed... but fixed in 1.8"

So, i wanna know, did you guys fix it in 1.8 and keep blaming the Pixelmon guys, and if so, could you guys drop a quick fix for 1.7.10? And if not, could you guys tell the Pixelmon guys what the problem is and help them fix it instead?

Regards, -Loke

**Comment by KingLemming** [comment]
We don't have a 1.8 version. We're not going to. 1.9 is our next target.

Having said that, this is 100% on their side. There is absolutely NO GUARANTEE of anything being registered with a Forge system and it is incredibly stupid of them to assume that just because we have a tool material, that it necessarily conforms to some arbitrary enum convention. There is no such requirement in vanilla OR Forge, and there is no such incompatibility with any other mod.

They need to get their house in order, sorry.

**Comment by Yanniclord** [comment]
Hmm well ok, i will open a thread there to and link to this so we can see both sides if you agree.

**Comment by KingLemming** [comment]
You're welcome to do so, but the fact is that they aren't going to fix 1.7.10 and I'm not going to go out of my way to fix their mod for them.

**Comment by Yanniclord** [comment]
Well they are intending to release a last 1.7.10 update to fix issues and add new Pokemon, lets hope they fix this one.
