### ISSUE TITLE
Thermal Foundation suggestion: Simpler generic dust names

### ISSUE THREAD

**Issue by Ithronyar** [CoFH/Feedback#927]
Minor UX issue. Simply put, Thermal Foundation's common (e.g. copper, tin, iron, etc.) dust names are unintuitive, and they don't match up with anything else.
Even in a standalone environment (and if you know what to look for), searching for TF's various dusts is a chore, since they use _two_ naming conventions within the same mod (i.e. "Pulverized [material]" and "[material] Blend").
Even well-configured modpacks that use TF dusts don't quite look right, since they tend to add several other mods' dusts. Most of them work together just fine, since they're almost always "[material] Dust". Then TF breaks the convention and calls everything "Pulverized X" and "Y Blend".

**Comment by KingLemming** [comment]
This can be handled trivially with a resource pack, if you prefer. "Unintuitive" is entirely a matter of opinion, and people have been getting along for 4 years just fine. If anything, *more* information is conveyed with the current naming convention, players simply have to take 13 seconds to learn it.

**Comment by Ithronyar** [comment]
I knew this would be opposed. At the very least, I put the suggestion up so it goes on record.

> This can be handled trivially with a resource pack, if you prefer.
Yes, but requiring a resource pack for every modpack that wants to unify the game's styles and conventions is a hassle (yes it's a minor issue, but good design requires minimal minor issues by definition). It's basically a tacked-on patch that highlights the design disparities, instead of seamlessly working out of the box, so to speak.

The only other solution would be to add a "simple dust names" entry to the config. That way the names would match with most other mods, and the Pulverized/Blend convention can remain.

**Comment by KingLemming** [comment]
>I knew this would be opposed. At the very least, I put the suggestion up so it would go on record.

I left it open, didn't I? I'm giving it some thought, and I will likely put up a Twitter poll and will probably just go with that.

The "Blend" designation is definitely staying though, sorry. It just conveys additional information that's it's an alloy.

**Comment by Tora-B** [comment]
It sounds like you're saying that it's a problem that mods look and feel different from each other, that it's obvious they were made by different people, with different ideas.

A resource pack is absolutely the correct way for a modpack to "unify the game's styles and conventions". You would need one anyway if you wanted all the items or blocks to use a similar style. There should be no expectation that mods, made by different people with different styles, approaches, and ideas on how to expand the base game, should all look and feel similar "out of the box". There is such a wide variety of interesting mods for Minecraft in part because the individual developers are all free to innovate, and aren't subject to some committee that judges their ideas in advance. While agreed-upon conventions are useful, strictly enforcing them means nobody ever has the chance to offer something better, which could become the new convention.

To put it simply, this seems like an attack on developer creativity and individuality, for the sake of user and modpack developer convenience.

For me personally, I use the Thermal mods as much because I like KL's stylistic and design choices as I do the functionality or power. By the same token, there are mods that provide similar functionality, and are often considered "better" by the community, because they're more powerful or convenient, which I choose to avoid because I don't like their style, whether it be "flavor" elements like textures and names, or how their design choices affect the play space.

The names of the "dusts" in the Thermal mods absolutely makes sense within the context of those mods. Pulverized metals are made in a pulverizer. Blends are made by mixing other pulverized metals. They may not make sense in some other mod's context, but that's not the responsibility of either mod to deal with. That's something a pack maker should handle, if they want to create a common context for two different mods to share.

**Comment by Ithronyar** [comment]
@Tora-B Fine, consider me a developer-hating design Nazi who wants creativity and freedom to die in a fire. The fact still remains that it's still more intuitive to name something as a noun. There's a reason the game (and most mods) use that convention. Iron **_Ingot_**, Iron **_Nugget_**, Iron **_Plate_**, Iron **_Dust_**. Oh wait, it's **_Pulverized_** Iron.
If everything were named using that convention, we'd have Compressed Iron (plate), Solidified Iron Brick (ingot), Dismantled Iron Brick (nugget), etc. Not so intuitive, is it. Creativity is good, but its results aren't always objectively better. That's like saying everything painted on a canvas is good, just because art is good.

P.S. You can pulverize alloys and they're still called "[material] Blend". I actually don't mind using the "Blend" naming too much, but it seems more practical to just call it "Dust", to account for all methods of its production (not just mixing other dusts together).

**Comment by KingLemming** [comment]
Let's keep it civil, shall we?

**Comment by PG-Fuury** [comment]
On that issue, the vanilla blocks are called Block of Iron and similar, so there is precedent for that kind of naming scheme

**Comment by KingLemming** [comment]
Poll was taken. Seems like it's a no, sorry.

https://twitter.com/KingLemmingCoFH/status/979402954687074305
