### ISSUE TITLE
Server crash on 1.12.2

### ISSUE THREAD

**Issue by Nimtrod** [CoFH/Feedback#952]
Hello COFH Team,

my Server is crashing which seems to be caused by servos?

Thermal Foundation: 2.3.10.6
Thermal Dynamics: 2.3.10.4
Thermal Expansion: 5.3.10.14
CoFH Core: 4.3.10.5
CoFH World: 1.1.1.12

If this is the wrong place for this I'm sorry, I just don't know where to put this. Thanks in advance!

Crashreport: https://gist.github.com/Nimtrod/a54c6ed4abd4389e4866be8497064ff7

Modlist: https://pastebin.com/QCauHj1P

**Comment by KingLemming** [comment]
You have a null itemstack. Something has been corrupted on your server and the servo crashes when trying to send the corrupted item.

I see Sponge in the stacktrace, which we technically don't support because of potential weirdness like this.

Sorry about your crashing, but strictly speaking, it's not the fault of the servo. It's the fault of whatever made your itemstack null.
