### ISSUE TITLE
[Thermal Expansion]Wrong oreDict in machine recipes

### ISSUE THREAD

**Issue by Usernm0** [CoFH/Feedback#953]
Machine recipes use <ore:thermalexpansion:machineCopper> for gears, but should use <ore:gearCopper>
Tin gears use right oreDict.

**Comment by KingLemming** [comment]
The fact that you're putting ore: at the front suggests to me that you are viewing this in game with no context and as such believe this to be a bug when it isn't. Or do you have a use case?

There is no ore: in front of any OreDict name, it's simply gearCopper and gearTin. The use of thermalexpansion:machineCopper is quite intentional here, as there's an option to change it to be ingots instead. In fact, there is also a machineTin, machineLead, etc.

This is quite intentional.

**Comment by Usernm0** [comment]
My mistake. I find option to use ingot in config.

I use minetweaker and try to make gears from mod Clockwork Phase works in TE machine recipes.
