### ISSUE TITLE
[Thermal Dynamics] Major Crash Harden item duct on a seed analyzer = Boom.

### ISSUE THREAD

**Issue by KaneHart** [CoFH/Feedback#954]
http://pastebin.com/s3qvb9jh

Someone on our server placed the Item Duct to a Seed Analyzer and boom went the server.

ThermalDynamics-[1.7.10]1.1.0-161.jar
AgriCraft-1.7.10-1.4.5.jar

The server keeps crashing when the chunks are loaded.

**Comment by KaneHart** [comment]
I should ping @InfinityRaider in case something he can do this is the Infinity Evolved 2.2.2 Pack!

**Comment by KingLemming** [comment]
Did you also report this to Agricraft? If the block claims to have a 36 slot inventory and then doesn't...welp.

**Comment by KaneHart** [comment]
Well that would explain it... Since your name came up I reported it here but if it claims it has 36 slots I will close this and report it there.

**Comment by KingLemming** [comment]
Well I'm not saying 100% that it isn't us, I just wanted to be sure that you also reported it there as well.

**Comment by InfinityRaider** [comment]
It doesn't have 36 slots, it only has 2, but I'm using the same ID's as for the Container (for consistency) and as such their ID's are 36 and 37 (Because for the Container the first 36 slots are the player's inventory.): 
https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/tileentity/TileEntitySeedAnalyzer.java#L284-L314
https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/container/ContainerSeedAnalyzer.java#L16-L17

I think I implemented the ISidedInventory methods correctly though, but I might be wrong

**Comment by KingLemming** [comment]
Yeah that's not how Minecraft is intended to work. Slots should be 0, 1, 2, etc, corresponding to the array of ItemStacks. A container is a separate mapping of slots and is an arbitrary construct with no relation.

**Comment by InfinityRaider** [comment]
Fair enough, I changed it to use 0 and 1 as ideas, but I think that having to do it this way is a bit limiting.
If you just have an IInventory, its logical that you start from 0, but what if I for instance had a slot which is only accessible via the Container and then some other slots, then it'd only work if that slot has the highest ID.

**Comment by KingLemming** [comment]
Not true at all. Remember that the container is arbitrary - it doesn't have to map to the IInventory at all.

In the case of augments in TE machines, for example, those aren't even in the IInventory slots. There is nothing anywhere that says that slots and inventory match up or mean anything at all.

The only required contract involving IInventory (and things which extend it) is the 0+ ordering. You have complete freedom with your container.
