### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by RustyKnightmare** [CoFH/Feedback#955]
So, to start with here's the list of all the mods I'm using: http://pastebin.com/ZXKUuUCV

I can't tell which of the mods went wrong, but a friend looked through it and cofh.mod.updater.UpdateManager.tickStart caught his eye.  This is the crash log: http://pastebin.com/AyDRwNw7

This crash only happened when I entered the end, never before- and since the world has been unable to load without crashing since I've been trying to figure out how to fix it.

**Comment by KingLemming** [comment]
It's not us, sorry. We're querying a standard Minecraft function. Your game has been put into an invalid state for whatever reason and seems to be corrupt on a pretty fundamental level.

at net.minecraft.server.management.ServerConfigurationManager.func_152596_g(ServerConfigurationManager.java:717)

is where the crash is occurring, because apparently something is not being initialized properly in Minecraft itself. A mod may have done this, or it could be a latent Mojang bug. Either way, we aren't at fault here, sorry.
