### ISSUE TITLE
[Thermal Dynamics] TickEvent$WorldTickEvent lagging the server

### ISSUE THREAD

**Issue by Aphyxia** [CoFH/Feedback#961]
According to LagGoggles, ThermalDynamics is lagging my world heavily https://gyazo.com/46c8649ba898b6282448cb0827802064
I have no idea what this is or how I would even go about solving this or at least finding the cause.
Should I just start removing mods and see if anything changes?
Restarting the server doesn't seem to make this disappear.

**Comment by KingLemming** [comment]
This is one of those things where LagGoggles doesn't quite get it right in terms of telling the story.

The way TD works is that it gets blamed for anything touching it which is laggy, because it hands off interaction responsibility to that tile. So what you see is a sum total of everything.

So, is your server *actually* lagging, or is this just LagGoggles saying it is? If it's the latter, I wouldn't worry. Tick Handling is odd and I'm not sure that it is being correctly timed.

In any case, I'm afraid there's no simple fix here beyond finding the actual cause, which isn't the ducts themselves but rather something connected to them.

**Comment by Aphyxia** [comment]
It was actually lagging, yes. I found the reason to be an empty Refined Storage Interface having a servo and itemduct go up to a locked to empty plant sower from Industrial foregoing. Having it paused disconnected the thermal pipe but the lag still remained. Removing the pipe fixed the lag.
I can't even start to understand why this happened but I'm just glad I got the lag removed. Trying to disconnect all ducts from attached blocks was the right way to go.

**Comment by Shybella** [comment]
https://timings.aikar.co/?id=cb97773f23634a06b561c99a46df8adf
https://sparkprofiler.github.io/?s221McLvlY

VisualVM NPS: https://drive.google.com/open?id=1eus0nOFrcY791rgFZ8e3FDp3SkC54mNy

upwards of 40%+ tick time

I'm trying to narrow this down, do you have any ideas on debugging further? Thank you
