### ISSUE TITLE
[Suggestion] Make smelting work with fortune?

### ISSUE THREAD

**Issue by Akitori** [CoFH/Feedback#981]
Heya. Smelting is kinda useless overall by itself atm. It doesn't stack with fortune, its only useful for shovels mainly...

So would you perhaps be inclined to make it work with fortune? That way it gets more use rather than being a overall unused enchantment?

**Comment by KingLemming** [comment]
I literally don't understand how this would work. Have an example?

**Comment by temp1011** [comment]
I'm guessing something like mining an ore will drop 1-2 of the ingot based on the level of fortune. Maybe even a secondary drop (similar to pulveriser recipe) too, although this would make the pulveriser a bit obselete.

**Comment by Akitori** [comment]
As the user above excluding the secondary drop.

Basically each level of fortune and smelting gives a random chance to drop a bonus ingot instead of one.

Though in my case i would be fine if smelting could smelt the block drops last. See i have this mod, JAOPCA orechunks, and it doesn't work due to you smelting the block itself directly, rather than what the block drops.

**Comment by Tmtravlr** [comment]
What Akitori is suggesting is making the drop event where the drops are smelted run later or even last so it picks up on drop changes from JAOPCA and smelts those.

Like 
```@SubscribeEvent (priority = EventPriority.HIGHEST)
	public void handleHarvestDropsEvent(BlockEvent.HarvestDropsEvent event) {```
to
```@SubscribeEvent (priority = EventPriority.LOWEST)
	public void handleHarvestDropsEvent(BlockEvent.HarvestDropsEvent event) {```

**Comment by KingLemming** [comment]
> it doesn't work due to you smelting the block itself directly, rather than what the block drops

This just simply isn't true. It gets the drops from the event. I can drop priority on it a bit, but what will end up happening is that fortune will simply overwrite it in a lot of cases.

**Comment by Tmtravlr** [comment]
> I can drop priority on it a bit, but what will end up happening is that fortune will simply overwrite it in a lot of cases.

Can you give an example of this?

I don't see that ever happening, since vanilla fortune is calculated before the even is even run, and if mods change drops that depend on fortune (like that JAOPCA), those would happen earlier and then at the end this would smelt them.

Either that or you could make ore smelting directly affected by fortune (maybe going off pulverizer or induction smelter recipes).

**Comment by KingLemming** [comment]
Yeah, I was thinking of coal and lapis, but those will only harvest with Silk Touch, which is already incompatible, so it's not a problem.

So then I guess the real question again goes back to...what does "compatible with fortune" even mean? It's kind of meaningless since things like gold and iron just...don't work with Fortune.

**Comment by Tmtravlr** [comment]
Yeah, like I suggested, you could add your own fortune 'recipes' which could work off of pulverizer/induction smelter recipes, and increase the ore drops for those. 

It would actually be well-balanced like that too, since fortune 3 increases drops 0-3 times, so an average of 1.5. Then by fortune you would on average get 2.5 drops from one ore, making it a bit better than the pulverizer/induction smelter, but not as good as the pulverizer/induction smelter with specializations and rich slag/cinnibar. So smelting on tools would be more useful but processing the ores would still yield more.

That or you could just smelt drops later on so mods that add fortune ore chunks would smelt those.

**Comment by temp1011** [comment]
Pulveriser recipes are in thermal expansion though. So would require thermal expansion as a dependancy which is weird.

**Comment by Tmtravlr** [comment]
Yeah, going off pulverizer recipes probably isn't a good idea, since it would pull in recipes you wouldn't want... it would likely have to be a new set of recipes, or just hard-coded (though that's not as easy to make compatable...)

**Comment by Akitori** [comment]
I would say go with leaving the smelting later. So fortune and smelting in base minecraft won't do anything (as it should), while modded ore chunks will work fine.

**Comment by EnderiumSmith** [comment]
That would be unbalanced. I would be better to have the smelting effect affect the drops after fortune. But i dont think it fits to have both on the same tool. its better if the player has to chose one like its the case with protection/blast/projectiles and sharpness/smite/bane

**Comment by Akitori** [comment]
Smelting as it stands is currently useless. Putting it on a standalone tool will more than anything have that tool by itself and unused (unless you're going for a instant charcoal maker or turning a desert to sand.

By having it affect drops after everything, with the lowest priority, it allows other mods to get the benefit of smelting. However, this is only for other mods. By itself, in a cofh exclusive modpack, this will not affect/change anything majorly.
