### ISSUE TITLE
[Thermal Expansion] [Suggestion/Question] - Removing furnace recipes

### ISSUE THREAD

**Issue by MasterFee** [CoFH/Feedback#99]
So my question pretty much is if I can disable a smelting recipe.
I tried disabling a smelting recipe using MineTweaker but the Redstone Furnace still has the disabled recipe working just fine. Removing a furnace recipe should disable it for the Redstone Furnace, shouldn't it? Also the smelting recipe is not shown in JEI, like others from mods like Immersive Engineering.
Happens to Extra Utilities 2 too where I am still able to smelt the items although they were disable by MineTweaker
__________________________________________
No smelting recipe shown in JEI:
<img width="1440" alt="pic2" src="https://cloud.githubusercontent.com/assets/8414127/23998200/a370c8c2-0a54-11e7-83d8-a36db92390d2.png">

Although still smelting in Redstone Furnace:
<img width="1440" alt="pic1" src="https://cloud.githubusercontent.com/assets/8414127/23998199/a36f9074-0a54-11e7-9fa9-47ec4c98e278.png">

**Comment by KingLemming** [comment]
No, it doesn't work that way. Mod furnaces often keep separate lists for performance reasons, as the vanilla one was coded particularly terribly.

You *are* able to remove recipes from it, there is IMC to handle that. MT simply isn't doing that. Put a feature request in for them.

Having said that, I'm not actually sure what you were trying to show with the screenshot, since you clearly show a recipe that exists and then show it in the Redstone Furnace.
