### ISSUE TITLE
ThermalDynamics: Option to enable Forge Multipart support

### ISSUE THREAD

**Issue by Typhox-** [CoFH/Feedback#994]
Since this mod unfortunately is the only mod that is (partially) incompatible with the Shaders Mod, it would be nice if there was a config option to disable the requirement for using Covers and instead allow the usage of Forge Multipart Panels.

Alternatively, fixing the issue that causes the graphical glitches on the Shader's Mod would also be an option (Shader's Mod doesn't get updated anymore for 1.7.10 and on a different thread I saw that King Lemming said he couldn't do anything on this part, although there must be a reason why the Covers are the only thing out of the 100 mods I'm running including ThermalDynamics that's incompatible with the Shaders Mod).

Right now I'm in this situation that I can not use Itemducts in my base due to this issue (for aesthetic reasons).

**Comment by KingLemming** [comment]
No, sorry. FMP support is not happening.

**Comment by Typhox-** [comment]
So basically, because you don't want to fix the rendering bug nor provide any workarounds, we can't use Thermal Dynamics? That's unfortunate :(

**Comment by XFactHD** [comment]
He wasn't saying that he doesn't want to fix the renderer, he just answered your main question (FMP support). And in terms of "rendering bugs", the problem is that the shaders mod changes how rendering works in a way mods can't account for. This means that the shaders mod would probably need compat code. But to be honest if I were you I wouldn't use the shaders mod in modded Minecraft as it eats performance like nothing else and it should also be possible to use the vanilla shader system for those shaders.

**Comment by skyboy** [comment]
If you value shaders over content, then yes. The mod is changing some fundamental logic deep in the renderer that we need reliable access to for the covers to work as reliably and wide-spread as they do.

You could try finding resourcepacks that replace vanilla's annoying built-in shaders with something usable, but you'll probably not find any.

**Comment by XFactHD** [comment]
If you put a valid shader file into the shader folder in the MC directory, you can, IIRC, switch to this shader too when zapping through the shaders in the pause menu.

**Comment by ferreusveritas** [comment]
I made a tiny patch mod for the Thermal Dynamics duct cover ShadersModCore rendering issue.
http://minecraft.curseforge.com/projects/thermalshade
Hope it works for you. Let me know :)
